### PR TITLE
OCPBUGS-25388: Add RHACM telemetry metric for 4.13

### PR DESCRIPTION
**Pull request by zlayne**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/retitle OCPBUGS-25388: Add RHACM telemetry metric for 4.13

**Comment by zlayne** [comment]
@simonpasquier PR & bug are up to date. Can you please review and add `cherry-pick-approved` label.

**Comment by simonpasquier** [comment]
the PRs need to be merged in order (4.14 > 4.13 > ...).

/cc @juzhao

**Pull request merged**
