### PR TITLE
Bug 1882730: fix cluster:cpu_core_hyperthreading rule for s390x

### PR DESCRIPTION
**Pull request by simonpasquier**
On s390x platforms, the core and package labels of the "node_cpu_info" metric are empty which break some recording rules (namely "node_role_os_version_machine:cpu_capacity_cores:sum").
    
This commit also introduces rule unit tests so we don't regress in the future.

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by paulfantom** [comment]
lgtm from my side

**Comment by s-urbaniak** [comment]
@simonpasquier let's rebase and merge, this lgtm too from my side.

**Comment by paulfantom** [comment]
Seems like there is an issue with generating bindata.

```
 func assetsPrometheusK8sRulesYamlBytes() ([]byte, error) {
 	return bindataRead(
@@ -1803,7 +1803,7 @@ func assetsPrometheusK8sRulesYaml() (*asset, error) {
 		return nil, err
 	}
 
-	info := bindataFileInfo{name: "assets/prometheus-k8s/rules.yaml", size: 100917, mode: os.FileMode(420), modTime: time.Unix(1, 0)}
+	info := bindataFileInfo{name: "assets/prometheus-k8s/rules.yaml", size: 103208, mode: os.FileMode(420), modTime: time.Unix(1, 0)}
 	a := &asset{bytes: bytes, info: info}
 	return a, nil
 }
```

/hold

**Comment by simonpasquier** [comment]
> Seems like there is an issue with generating bindata.

It seems like a stale `jsonnet/vendor` directory...

**Pull request merged**
