### PR TITLE
[release-4.3] Bug 1807141: jsonnet/rules.jsonnet: Add MultipleContainersOOMKilled alert

### PR DESCRIPTION
**Pull request by rphillips**
Backport of 4.4 PR: https://github.com/openshift/cluster-monitoring-operator/pull/676

### CODE REVIEW

**Comment by lilic** [comment]
PR needs rebase before I can review @rphillips

**Comment by lilic** [comment]
@rphillips Needs rebase and regenerate.

**Comment by rphillips** [comment]
the build in docker container doesn't get pinned to a specific container, so it's pulling latest... Which pin is supposed to be use for 4.3?

**Pull request merged**
