### PR TITLE
jsonnet: remove unused file

### PR DESCRIPTION
**Pull request by dgrisonnet**
The cmo.jsonnet file seems to have been added inadvetently. Since we
don't use it anywhere, we should remove it.

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
/hold
waiting for #985

**Comment by paulfantom** [comment]
This doesn't impact #985 as the file is not used

/unhold

**Pull request merged**
