### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by simonpasquier**
We haven't updated our Go dependencies in a while, let's refresh...

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/label qe-approved
/label px-approved
/label docs-approved

adding required labels as it doesn't change any functionality

**Comment by raptorsun** [comment]
Shall we configure a bot to make an update PR every month to remind us of go module upgrades?

**Pull request merged**
