### PR TITLE
MON-3664: chore: avoid issues with std.set* functions

### PR DESCRIPTION
**Pull request by simonpasquier**
Functions like std.setMember() expect the input array to be sorted without duplicates.

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/ cc @machine424 
/cc @jan--f

**Comment by jan--f** [comment]
:+1: 
/lgtm

**Comment by machine424** [comment]
/lgtm
It even caught a bug, thanks!

**Comment by simonpasquier** [comment]
/retitle MON-3664: chore: avoid issues with std.set* functions

**Pull request merged**
