### PR TITLE
Bug 1975281: Remove resource limit from kube-rbac-proxy

### PR DESCRIPTION
**Pull request by PhilipGough**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by juzhao** [comment]
/lgtm
resource limit for kube-rbac-proxy is removed,  influented pods: kube-state-metrics/node-exporter pods

**Comment by PhilipGough** [comment]
```bash
 Kernel Version:             3.10.0-1062.el7.x86_64
 OS Image:                   Red Hat Enterprise Linux Server 7.9 (Maipo)

oc exec node-exporter-4gskm -c kube-rbac-proxy -n openshift-monitoring -- cat /sys/fs/cgroup/cpu/cpu.stat
nr_periods 0
nr_throttled 0
throttled_time 0
```

**Pull request merged**
