### PR TITLE
Bug 1829723: Update and pin jsonnet dependencies for release 4.7

### PR DESCRIPTION
**Pull request by dgrisonnet**
* [x] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
I still need to bump the version of grafana in upstream kube-prometheus to 7.3.5 and bring it downstream before proceeding with this PR.

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Pull request merged**
