### PR TITLE
pkg/client/client: Fix "unavailable" -> "available" typo in daemonset error

### PR DESCRIPTION
**Pull request by wking**
Typo from 62a22a3097 (#240).

### CODE REVIEW

**Comment by s-urbaniak** [comment]
I believe this is even worth backporting, cc @paulfantom do you mind to shepherd this?

**Comment by s-urbaniak** [comment]
Closing in favor of https://github.com/openshift/cluster-monitoring-operator/pull/512

**Comment by paulfantom** [comment]
This would break what we have in other messages where we notify about `unavailable` pods. Instead lets change the source of the value we are passing to a message.

/close

**Pull request closed without merging**
