### PR TITLE
Bug 1800489: Patch kube pv storage alert release 3.11

### PR DESCRIPTION
**Pull request by pgier**
Backport upstream fix (https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/288) of alert KubePersistentVolumeFullInFourDays

### CODE REVIEW

**Comment by paulfantom** [comment]
We can use it to check if https://github.com/openshift/release/pull/9385 allows us to merge PRs into 3.11 by using CI.

**Comment by lilic** [comment]
Sadly we are not in the owners file. @s-urbaniak @brancz this needs an approved label from one of you.

**Pull request merged**
