### PR TITLE
jsonnet/prometheus: remove apiserver service monitor

### PR DESCRIPTION
**Pull request by s-urbaniak**
Fixes MON-670

/assign @paulfantom @brancz

### CODE REVIEW

**Comment by s-urbaniak** [comment]
We need to make sure the following PRs land first:

- https://github.com/openshift/cluster-kube-apiserver-operator/pull/501
- https://github.com/openshift/cluster-kube-apiserver-operator/pull/502

**Comment by brancz** [comment]
I don't think e2e-aws should pass until the PRs on the other repos are merged.

**Comment by s-urbaniak** [comment]
yes, as indicated in https://github.com/openshift/cluster-monitoring-operator/pull/376#issuecomment-501229110 those PRs need to be merged first.

**Pull request merged**
