### PR TITLE
docs(data-collection): add newlines for visibility

### PR DESCRIPTION
**Pull request by georgettica**
this is so reading it will be easier, maybe add a PR to automatically generate this file

* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by RiRa12621** [comment]
/hold
I generally agree that it improves readability **but** the actual on cluster configmap needs to be the same

**Comment by georgettica** [comment]
thanks!
also the spaces are in the wrong place :(

**Comment by georgettica** [comment]
@RiRa12621 now they are similar.. is there anything else that needs to change aside of the configmap?

**Comment by georgettica** [comment]
@RiRa12621 now it only needs a lgtm :) of you think it's ok

**Comment by RiRa12621** [comment]
You need someone from owners 
@s-urbaniak for example

**Comment by georgettica** [comment]
Thanks for helping me on this :)

**Comment by paulfantom** [comment]
Since we are in code freeze this might need to wait until `master` is open for development.

**Comment by georgettica** [comment]
Is code freeze still up?

**Comment by paulfantom** [comment]
Code freeze is till Jan 18.

**Comment by lilic** [comment]
Thanks for the PR, but note code freeze was extended until February 5th. Ping us again then so we can merge it. :)

**Comment by georgettica** [comment]
/hold
Till Feb 5

**Comment by georgettica** [comment]
@RiRa12621 should I fix these now or has the deadline moved again?

**Comment by RiRa12621** [comment]
That's probably only a rebase
/unhold

**Comment by georgettica** [comment]
🤞 🤞

**Comment by georgettica** [comment]
@lilic I think it looks fine for now and ready to lgtm.. can you TAL?

**Comment by RiRa12621** [comment]
nil pointer is from somewhere else
/retest

**Pull request merged**
