### PR TITLE
NO-JIRA: vendor Kubernetes dashboards

### PR DESCRIPTION
**Pull request by simonpasquier**
kubernetes-monitoring/kubernetes-mixin is pinned to the latest upstream commit before the project switched to Grafana v11 since it broke the Kubernetes dashboards in the OCP console (see 2399dc84 for details).

This change removes the Kubernetes dashboards from the jsonnet generation code. Instead their current version is copied to the `0000_90_cluster-monitoring-operator_02-dashboards.yaml` file under the `manifests/` directory. Any future update to these dashboards should be made to the manifest file directly.

A follow-up PR will unpin the kubernetes-monitoring/kubernetes-mixin version.

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold

I want to spin up a test cluster and compare against the current version.

**Comment by simonpasquier** [comment]
/hold cancel
tested locally and it seems working.

**Comment by rexagod** [comment]
/retest
/approve

Unblocks https://github.com/openshift/cluster-monitoring-operator/pull/2422 and resolves [OCPBUGS-35095's comment](https://issues.redhat.com/browse/OCPBUGS-35095?focusedId=25339746&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25339746)

**Review by marioferh — COMMENTED** [review]
/lgtm

**Pull request merged**
