### PR TITLE
AUTH-481: add PSa labels to openshift-user-workload-monitoring namespace

### PR DESCRIPTION
**Pull request by liouk**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by machine424** [comment]
As it's the default profile
/lgtm
to be more explicit.

**Comment by liouk** [comment]
/hold
blocked by https://issues.redhat.com/browse/AUTH-482

**Pull request closed without merging**
