### PR TITLE
Bug 1805317: pkg/manifests/telemeter: bump size limit to 5mb

### PR DESCRIPTION
**Pull request by s-urbaniak**

### CODE REVIEW

**Comment by lilic** [comment]
@s-urbaniak any reason you added the cherry-pick approved on a 4.3 PR, I thought it was only for 4.4 PRs 🤔 
/bugzilla refresh

Putting on hold, feel free to remove if I was wrong.
/hold remove

**Comment by s-urbaniak** [comment]
@lilic i believe my eyes _wanted_ to see 4.4, removed cherry-pick approval and bugzilla to be happy.

**Pull request merged**
