### PR TITLE
Bug 1845445: KubeApiLatency alert firing even though not all conditions are matched

### PR DESCRIPTION
**Pull request by RiRa12621**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by lilic** [comment]
Can you rebase please:)

**Comment by lilic** [comment]
/hold

until rebase :)

**Comment by RiRa12621** [comment]
/cancel hold
rebased

**Comment by RiRa12621** [comment]
/hold cancel
rebased

**Comment by RiRa12621** [comment]
how does a PR get `cherry-pick-approved` label?

**Comment by simonpasquier** [comment]
@RiRa12621 the release manager will evaluate the awaiting bug fixes for 4.5 and make a decision on which ones should be approved.

**Comment by simonpasquier** [comment]
Which is today, we have to wait...

**Pull request merged**
