### PR TITLE
OCPBUGS-2623:  Fix dashboards having container_fs* metrices in queries

### PR DESCRIPTION
**Pull request by slashpai**
Backport of https://github.com/openshift/cluster-monitoring-operator/pull/1554

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by slashpai** [comment]
@juzhao Could you please in reviewing this?

**Comment by juzhao** [comment]
tested with PR,  all "Storage IO" graphs can show data correctly
/label cherry-pick-approved

**Pull request merged**
