### PR TITLE
Bug 1877256: disable grafana telemetry

### PR DESCRIPTION
**Pull request by dgrisonnet**
Backport of #834 to 4.5

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by lilic — COMMENTED** [review]
/lgtm

**Comment by simonpasquier** [comment]
@dgrisonnet you need to do some paperwork :)
* Set target release of Bugzilla 1876830 to 4.6.0 and status to MODIFIED. 
* Clone 1876830 and set the target release to 4.5.z for the clone.
* Modify the title of the PR with the new bugzilla ID.
* Wait for QA to set 1876830 to the VERIFIED status.

**Pull request merged**
