### PR TITLE
OCPBUGS-4069: Prometheus Adatper takes metrics from "kubelet" job only

### PR DESCRIPTION
**Pull request by raptorsun**
* [x] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/skip

Can you propose a patch upstream to allow for additional label selectors in the prometheus-adapter queries?

**Comment by raptorsun** [comment]
> /skip
> 
> Can you propose a patch upstream to allow for additional label selectors in the prometheus-adapter queries?

Of course, will do it tomorrow :)

**Comment by raptorsun** [comment]
PR has been submitted to upstream. Adding optional selectors to container and node queries separately.
https://github.com/prometheus-operator/kube-prometheus/pull/2003

**Pull request closed without merging**
