### PR TITLE
Bug 1937907: etcdInsufficientMembers is wrong when etcd is in a pod

### PR DESCRIPTION
**Pull request by hexfusion**
Manual cherry-pick of https://github.com/openshift/cluster-monitoring-operator/pull/1064 on 4.6

Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

### CODE REVIEW

**Comment by hexfusion** [comment]
cc @simonpasquier

**Review by lilic — COMMENTED** [review]
/lgtm

Thanks!

**Pull request merged**
