### PR TITLE
[MON-720] jsonnet/node-exporter.jsonnet: Prevent ServiceMonitor overriding

### PR DESCRIPTION
**Pull request by LiliC**
Because we were overriding the entire ServiceMonitor Endpoints object, the changes we had in the `instance` relabeling did not get applied to cluster-monitoring-operator node-exporter ServiceMonitor resource.

cc @s-urbaniak @brancz @paulfantom 

This patch needs to be merged into the master-4.3 branch as well.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@LiliC do you mind to also do a merge `master` into `master-4.3` once this is merged?

**Comment by LiliC** [comment]
/hold 

just want to verify something, launching a cluster

**Pull request merged**
