### PR TITLE
OCPBUGS-10895: add startup probe for prometheus-adapter

### PR DESCRIPTION
**Pull request by simonpasquier**
This is the backport of commit 90585d11.

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by slashpai — APPROVED** [review]
/lgtm

**Comment by simonpasquier** [comment]
/hold
until we're sure that it's safe to merge into 4.13.

**Pull request merged**
