### PR TITLE
Add yamllint configuration, run yamllint in Travis

### PR DESCRIPTION
**Pull request by elad661**
This ensures all yaml files we have in cluster-monitoring-operator
will be parsable and consistently indented.

I think this is useful if we're going to get a lot of contributions from the component teams.

/cc @mxinden @brancz

### CODE REVIEW

**Comment by brancz** [comment]
Glad it passes (with just one line break missing) :slightly_smiling_face:

**Comment by elad661** [comment]
@mxinden I think the correct command is approve, not approved (it's confusing, I know).

https://deck-ci.svc.ci.openshift.org/command-help

**Comment by mxinden** [comment]
@elad661 I tried `/` + `approve`. Any other ideas?

**Comment by elad661** [comment]
@mxinden I'm going to go ahead and add the label manually, to see what happens.

**Pull request merged**
