### PR TITLE
Bug 1740373: Add more accurate infrastructure CPU calculations

### PR DESCRIPTION
**Pull request by smarterclayton**
The previous infrastructure usage calculations didn't account for
nodes - create a workload measurement of != openshift-* and then
subtract that from cluster usage to get infra.

### CODE REVIEW

**Comment by fabianofranz** [comment]
LGTM

**Comment by LiliC** [comment]
lgtm

cc @brancz @s-urbaniak I can't approve as I was not in the 4.1 OWNERS file PTAL

**Comment by fabianofranz** [comment]
Needs `cherry-pick-approved`.

**Comment by derekwaynecarr** [comment]
Approved for 4.1.z

**Pull request merged**
