### PR TITLE
Release 3.11.1

### PR DESCRIPTION
**Pull request by brancz**
@squat @mxinden @metalmatze @s-urbaniak

### CODE REVIEW

**Comment by mxinden** [comment]
I am deleting branch _release-3.11.1_, as with this pull request all changes have been merged in _release-3.11_.

**Comment by mxinden** [comment]
Never mind. I don't have permissions to do so. @brancz would you mind deleting the branch if you can?

**Comment by brancz** [comment]
can't delete branches either

**Pull request merged**
