### PR TITLE
TRT-1489: Revert "jsonnet: update crio port to TLS port 9637"

### PR DESCRIPTION
**Pull request by simonpasquier**
Reverts openshift/cluster-monitoring-operator#2229

It might have cause failures with nightly jobs.

### CODE REVIEW

**Comment by stbenjam** [comment]
/retitle TRT-1489: Revert "jsonnet: update crio port to TLS port 9637"

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-gcp-ovn-rt-upgrade

**Comment by rphillips** [comment]
/hold
/lgtm cancel

This should fix it: https://github.com/openshift/machine-config-operator/pull/4168

**Comment by rphillips** [comment]
/lgtm
/hold cancel

The `alert/TargetDown should not be at or above info in ns/kube-system` tests rely on the continued presence of the metrics port. We need this PR to get this test to pass. I'll look into figuring out changing the test.

**Pull request merged**
