### PR TITLE
OCPBUGS-43987: Bump library-go to get latest tls suite changes

### PR DESCRIPTION
**Pull request by slashpai**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by Tai-RedHat** [comment]
I tested this pr with cluster-bot, looks good!  now metrics-server tls-cipher matched with the global.
/label qe-approved

**Comment by slashpai** [comment]
cc @simonpasquier

**Pull request merged**
