### PR TITLE
Bug 1771389: Refactor cpu recording rules

### PR DESCRIPTION
**Pull request by pgier**
This is another attempt to refactor the CPU recording rules since #532 seemed to have a lot of questions around breaking backwards compatibility.  This change attempts to keep the existing metric names and labels while still fixing some issues in the existing queries.

I believe the existing queries are not correctly counting the number of sockets and cores in a cluster.  Installing a default AWS cluster, I get the following infrastructure:
- 3 master nodes each with type="m4.xlarge", sockets=1, cores=2, cpus=4
- 3 worker nodes each type="m4.large", sockets=1, cores=1, cpus=2

So there are a total of:
- 18 cpus (3 * 4 + 3 * 2)
- 9 cores (2 for each master and 1 for each worker)
- 6 sockets/packages (1 on each node)

The current recording rules for example show:
```
cluster:capacity_cpu_sockets_hyperthread_enabled:sum{label_beta_kubernetes_io_instance_type="m4.large",label_node_hyperthread_enabled="true"} | 6
cluster:capacity_cpu_sockets_hyperthread_enabled:sum{label_beta_kubernetes_io_instance_type="m4.xlarge",label_node_hyperthread_enabled="true",label_node_role_kubernetes_io="master"} | 12
```
Which appears to be counting sockets the same the number of CPUs.  And the metrics for the cores are similarly counting the number of CPUs.
With this PR, the number of cores and sockets should be counted distinctly from CPUs.
```
cluster:capacity_cpu_sockets_hyperthread_enabled:sum{label_beta_kubernetes_io_instance_type="m4.large",label_node_hyperthread_enabled="true"} | 3
cluster:capacity_cpu_sockets_hyperthread_enabled:sum{label_beta_kubernetes_io_instance_type="m4.xlarge",label_node_hyperthread_enabled="true",label_node_role_kubernetes_io="master"} | 3
```
```
node_role_os_version_machine:cpu_capacity_cores:sum{label_kubernetes_io_arch="amd64",label_node_hyperthread_enabled="true",label_node_openshift_io_os_id="rhcos"} | 3
node_role_os_version_machine:cpu_capacity_cores:sum{label_kubernetes_io_arch="amd64",label_node_hyperthread_enabled="true",label_node_openshift_io_os_id="rhcos",label_node_role_kubernetes_io_infra="true",label_node_role_kubernetes_io_master="true"} | 2
node_role_os_version_machine:cpu_capacity_cores:sum{label_kubernetes_io_arch="amd64",label_node_hyperthread_enabled="true",label_node_openshift_io_os_id="rhcos",label_node_role_kubernetes_io_master="true"} | 4
```
```
node_role_os_version_machine:cpu_capacity_sockets:sum{label_kubernetes_io_arch="amd64",label_node_hyperthread_enabled="true",label_node_openshift_io_os_id="rhcos"} | 3
node_role_os_version_machine:cpu_capacity_sockets:sum{label_kubernetes_io_arch="amd64",label_node_hyperthread_enabled="true",label_node_openshift_io_os_id="rhcos",label_node_role_kubernetes_io_infra="true",label_node_role_kubernetes_io_master="true"} | 1
node_role_os_version_machine:cpu_capacity_sockets:sum{label_kubernetes_io_arch="amd64",label_node_hyperthread_enabled="true",label_node_openshift_io_os_id="rhcos",label_node_role_kubernetes_io_master="true"} | 2
```

### CODE REVIEW

**Comment by pgier** [comment]
@chambridge @smarterclayton PTAL.  Trying this again without breaking the existing query names this time.

**Comment by chambridge** [comment]
LGTM! Lets get this *merged* asap.

**Comment by s-urbaniak** [comment]
thanks a lot @pgier for the effort :pray: 
leaving @smarterclayton the final call for lgtm.

**Comment by smarterclayton** [comment]
/lgtm

as well

**Pull request merged**
