### PR TITLE
Add telemetry metrics for HyperShift

### PR DESCRIPTION
**Pull request by csrwng**
Initial set of metrics to be reported by the HyperShift operator through telemetry

* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/assign @jan--f 
/assign @bill3tt

A recording rule aggregating away the less-useful labels like `instance`, `pod`, ... would be appreciated. For example:

```
  - name: ...
    rules:
    - record: platform:hypershift_hostedclusters:max
      expr: max by(platform) (hypershift_hostedclusters)
    - record: platform:hypershift_nodepools:max
      expr: max by(platform) (hypershift_nodepools)
```

**Comment by csrwng** [comment]
@simonpasquier I switched the name of the metrics to the name of the recording rules. The rules are now laid down when installing hypershift -> https://github.com/openshift/hypershift/pull/1544

**Pull request merged**
