### PR TITLE
Bug 1941634: allow only /metrics for kube-rbac-proxy in front of UWM

### PR DESCRIPTION
**Pull request by slashpai**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Looks like I wasn't an approver in 4.6.

/cc @paulfantom @simonpasquier

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.40

approved

**Pull request merged**
