### PR TITLE
Add RHODS Usage and Availability metrics

### PR DESCRIPTION
**Pull request by anishasthana**
Relevant request and approval can be found at https://docs.google.com/document/d/1P9TbVXA6MnocUAFjQy0Cfs0dd_JZqvnM1Ao44Ken8t8/edit# 

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
out of curiosity in which project do the rules/metrics live?

**Comment by anishasthana** [comment]
We're working on further consolidating these repos long term, but the rules themselves are defined at https://github.com/red-hat-data-services/odh-deployer/blob/main/monitoring/prometheus/prometheus.yaml#L420-L430. 
The service monitor for federation is defined at https://github.com/red-hat-data-services/odh-manifests/blob/master/monitoring/base/rhods-service-monitor.yaml.

**Comment by anishasthana** [comment]
/retest
Tests seem flaky. Different ones have been failing.

**Comment by anishasthana** [comment]
/retest

@simonpasquier what can we do here? Should I just keep retesting until ci passes?

**Pull request merged**
