### PR TITLE
Bug 1812382: Enable discovery of Podmonitors Custom Resource across namespaces

### PR DESCRIPTION
**Pull request by dgrisonnet**

### CODE REVIEW

**Comment by lilic** [comment]
Seems like generate is failing 🤔 which jb version did you use, I think 4.3 branch uses an older one if I remember correctly. cc @paulfantom

**Comment by dgrisonnet** [comment]
I used `v0.2.0`

**Comment by lilic** [comment]
I think it might have been an older version there, Pawel should know.

**Comment by s-urbaniak** [comment]
@dgrisonnet this generally looks great :+1: 
we need to fix in master first though, then we can trickle down the releases for backports.

**Comment by lilic** [comment]
Master is fixed from what I seen.

**Comment by s-urbaniak** [comment]
ok, then we need to let @juzhao verify master first, then we can clone.

**Comment by lilic** [comment]
sgtm: just think we need to also create jira as tech-debt to add tests for PodMonitors in both prom-operator and this repo. SGTY @s-urbaniak ?

**Comment by lilic** [comment]
/hold

To stop retesting.

**Comment by paulfantom** [comment]
> I used `v0.2.0`

Short: yes, this is what should be used

Long: `ci/prow/generate` is (unfortunately) not locked to any version of jsonnet-bundler and it uses latest version of `quay.io/coreos/po-tooling` image. Right now we have jb `v0.2.0` there [[source](https://github.com/coreos/prometheus-operator/blob/master/scripts/tooling/Dockerfile#L7)], but we will be upgrading to `v0.3.1` after I merge [this PR](https://github.com/coreos/prometheus-operator/pull/3037).

I think this might not be a jb error but a jsonnet one. Could you verify that you are using the same tooling as in https://github.com/coreos/prometheus-operator/blob/master/scripts/tooling/Dockerfile#L3-L7 ?

**Comment by s-urbaniak** [comment]
@lilic 
> sgtm: just think we need to also create jira as tech-debt to add tests for PodMonitors in both prom-operator and this repo. SGTY @s-urbaniak ?

yes, that definitely sounds good to me :+1: I think we cover podmonitors right now only.

**Comment by s-urbaniak** [comment]
beware that we need to make sure that this bug must be first verified in master aka 4.5, then (via a cloned bug) in 4.4, and then (via another cloned bug referenced in this PR) in 4.3

**Comment by lilic** [comment]
Let us know if anything of the above is not clear! :)

**Comment by dgrisonnet** [comment]
@lilic @s-urbaniak @paulfantom I fixed the issue with `ci/prow/generate`. Would you please have another look?

**Comment by lilic** [comment]
This still needs a valid bugzilla, otherwise its ready to go.

**Comment by s-urbaniak** [comment]
/lgtm from my side
QA needs to verify in earlier releases first

**Comment by dgrisonnet** [comment]
@paulfantom I regenerated the manifests using the updated toolchain. Would you mind having another look? Thanks!

**Comment by dgrisonnet** [comment]
PTAL @s-urbaniak @lilic

**Comment by dgrisonnet** [comment]
PTAL @openshift/openshift-team-monitoring

**Pull request merged**
