### PR TITLE
NO-JIRA: use scrape class to avoid TLS config repetitions

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by slashpai — COMMENTED** [review]
/retest-required

**Comment by simonpasquier** [comment]
@slashpai the CI failure looks legit

**Comment by simonpasquier** [comment]
@jan--f this is a small improvement to reduce coupling between the service monitors and the platform Prometheus: instead of hardcoding file paths in all service monitors, we can refer to the scrape class name defined in the Prometheus object. Eventually we can modify other core operators to do the same.

**Comment by jan--f** [comment]
Sorry, lost track of this. Feel free to mark this critical if this should make it into 4.18. I assume though it can wait?
/lgtm

**Comment by simonpasquier** [comment]
> I assume though it can wait?

Totally.

cc @frzifus, if/when this merges, you won't be able to reuse the service monitors without supporting scrape classes in the opentelemetry operator (or a similar mechanism).

**Pull request merged**
