### PR TITLE
Bug 1847318: set TLS min version to 1.2

### PR DESCRIPTION
**Pull request by pgier**
Change the TLS min version in prometheus-operator to 1.2 from the default of 1.3.

* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by pgier** [comment]
/hold 
Creating this PR for testing possible fix for bz1847318

**Comment by s-urbaniak** [comment]
@pgier can you give some references why we need to remove configuring tls cipher suites for the webhooks?

**Comment by pgier** [comment]
@s-urbaniak I noticed that the other validation webhooks currently in openshift do not set any TLS cipher suites, so just wanted to test this.

**Comment by s-urbaniak** [comment]
@pgier we had some issues in CI yesterday. do you mind to rebase and retest?

**Comment by pgier** [comment]
@s-urbaniak please take a look again

**Comment by s-urbaniak** [comment]
@bparees i am very sorry, can you remind me again whom we can ping about the FIPS compliance and verify "we are doing the right thing" here?

**Comment by bparees** [comment]
> @bparees i am very sorry, can you remind me again whom we can ping about the FIPS compliance and verify "we are doing the right thing" here?

Kirsten Newcomer was the PM who might be able to point you to some experts.  David Eads also suggested Simo Sorce as a security engineer who was involved.

**Pull request merged**
