### PR TITLE
MON-3589: Refactor assertExemplarsEnabled check for UWM Prometheus xand add a check for --scrape.timestamp-tolerance on Platform Prometheus

### PR DESCRIPTION
**Pull request by machine424**
…rometheus xand add a check for --scrape.timestamp-tolerance on Platform Prometheus

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by jan--f** [comment]
Nice, thanks!
/lgtm

**Comment by machine424** [comment]
(this only touches e2e tests and `ci/prow/e2e-agnostic-operator ` isn't yelling, I think it's safe to skip the other ones)

**Pull request merged**
