### PR TITLE
add unit test for metric "cluster:capacity_cpu_cores:sum"

### PR DESCRIPTION
**Pull request by raptorsun**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
master nodes also have the `control-plane` role, it would be good to test that the output is correct in this case.

**Comment by raptorsun** [comment]
> master nodes also have the `control-plane` role, it would be good to test that the output is correct in this case.

Thanks for the review :)

The tests about `cluster:master_nodes` and `cluster:infra_nodes` are moved into a separate file. 
`kube_node_role(role="control-plane")` is added to master nodes in the test cases.

**Comment by simonpasquier** [comment]
IIUC this is now obsoleted by #1926? If yes, feel free to close this PR.

**Comment by raptorsun** [comment]
> IIUC this is now obsoleted by #1926? If yes, feel free to close this PR.

Yes. These tests will be obsolete when we merge #1926 This is just for comparing the behavior before and after we modify the recording rule of `cluster:capacity_cpu_cores:sum`.
/close

**Pull request closed without merging**
