### PR TITLE
*/thanos-querier: mount trusted CA bundle

### PR DESCRIPTION
**Pull request by s-urbaniak**
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1787098. I am not setting the bugzilla bot title as we will backport this to 4.3.

Let's see what e2e says, I did not test this in a local cluster.

/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by s-urbaniak** [comment]
ok, those failures seem to be related, looking

**Comment by s-urbaniak** [comment]
@LiliC indeed, yes, my `grep` foobar apparently is rusted due to vacation :grimacing:

**Comment by LiliC** [comment]
I think the failure might be relevant to the thanos part and the deprecated APIs are removed now.

**Comment by s-urbaniak** [comment]
I referenced the wrong container index in the tests, these are passing now locally.

**Comment by s-urbaniak** [comment]
@openshift/openshift-team-monitoring ptal

**Comment by s-urbaniak** [comment]
/rename Bug 1787098: */thanos-querier: mount trusted CA bundle

**Pull request merged**
