### PR TITLE
Bug 1745379: Fix many-to-many matching not allowed

### PR DESCRIPTION
**Pull request by LiliC**
This brings in the changes fixed in master to the release-4.1 branch.

https://bugzilla.redhat.com/show_bug.cgi?id=1745379

cc @s-urbaniak @paulfantom

### CODE REVIEW

**Comment by LiliC** [comment]
/test e2e-aws-operator

seems like its unrelated: 
> level=fatal msg="failed to initialize the cluster: Could not update imagestream \"openshift/cli\" (186 of 349): the server is down or not responding: timed out waiting for the condition"

**Comment by LiliC** [comment]
Okay seems like it was all flaky tests, just my luck, ran into two. 🤷‍♀ 

As Pawel was not in the OWNERS file in 4.1, I think we need either @s-urbaniak @brancz or @squat  to approve this. Thanks :)

**Comment by LiliC** [comment]
This now needs a `cherry-pick-approved label`, the 4.2/master bug was verified https://bugzilla.redhat.com/show_bug.cgi?id=1740559

**Comment by mfojtik** [comment]
@LiliC @s-urbaniak the BZ is set as low priority, I think our backport policy require the BZ to be at least medium.  @jwforres @eparis can you confirm? (other than that, I don't see any other formal requirement not met for approving this backport)

**Comment by brancz** [comment]
I would urge this to be included as this is a very important alert to be working, as it ensures the health of the alerting pipeline, ultimately ensuring that people actually receive notification. I think priority is higher than "low", so I think this should be included.

**Comment by mfojtik** [comment]
BZ is now medium priority and agree with @brancz.

**Pull request merged**
