### PR TITLE
Provide an explicit list of allowed labels for the kube_node_labels metric

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
We should rather wait until we can configure a wildcard list for the `kube_node_labels` metric in our downstream kube-state-metrics (https://github.com/kubernetes/kube-state-metrics/pull/1403).

**Comment by dgrisonnet** [comment]
Agreed, but we should still allow the labels used in Telemetry, otherwise they won't be shown.

**Pull request closed without merging**
