### PR TITLE
Bug 1804825: Report system manufacturer via telemetry

### PR DESCRIPTION
**Pull request by smarterclayton**
Include system and baseboard manufacturer and product name fields
as reported for bare metal systems to assist in debugging hardware
related failures.

### CODE REVIEW

**Comment by smarterclayton** [comment]
https://github.com/openshift/cluster-monitoring-operator/pull/646 must merge before this

**Comment by lilic** [comment]
@smarterclayton PR needs rebase and the linked PR was merged.

**Comment by lilic** [comment]
/hold
doing hold to stop reseting.
This needs a rebase @smarterclayton

**Comment by smarterclayton** [comment]
I think we can wait for 4.4

**Pull request closed without merging**
