### PR TITLE
manifests: remove default cluster monitoring config

### PR DESCRIPTION
**Pull request by s-urbaniak**
Currently, any changes done to the configuration of cluster monitoring operator
will be reconciled by the cluster version operator.

As the current default configuration (manifested in code in the operator)
is supposed to work anyways, there is no need to ship a default configuration at all.

That way the user can create this config post-install, disabling telemeter,
or changing any other operational parameters of the cluster monitoring operator.

Fixes Bugzilla 1666626
Fixes Jira MON-515

cc @smarterclayton @brancz @squat @juzhao

### CODE REVIEW

**Comment by juzhao** [comment]
@s-urbaniak 
cluster monitoring is enabled by default, I think this change will not install cluster monitoring by default now

**Comment by brancz** [comment]
superseeded by #200

**Pull request closed without merging**
