### PR TITLE
Bug 1807100: pkg/manifests: rename shared config's keys to include 'Public'

### PR DESCRIPTION
**Pull request by simonpasquier**
cc @openshift/openshift-team-monitoring @benjaminapetersen

### CODE REVIEW

**Comment by paulfantom** [comment]
/lgtm
/hold
putting on hold as I don't know what is the status of the discussions around it.
/cc @s-urbaniak

**Comment by jhadvig** [comment]
So the thing is that console consumes  those URLs from the `shared-config` configmap, and since we are consuming variety of [different variables](https://github.com/openshift/console/blob/master/pkg/serverconfig/types.go)  and we like to be as explicit about the naming of the keys as possible. We talked about the names over the console [PR](https://github.com/openshift/console/pull/4309/files#diff-ed200cd740647bdf9f4f1330679865bc) and we agreed that best would be to already consume configmap with explicit key names.
Logging operator (which `shared-config` we are consuming as well) is already using this explicit naming in https://github.com/openshift/cluster-logging-operator/pull/374 and now they are backporting to [4.4](https://github.com/openshift/cluster-logging-operator/pull/382)
ccíng @benjaminapetersen

**Comment by s-urbaniak** [comment]
let's have a final :ok: from @bparees on the naming part, then we can un`/hold` this PR.

**Comment by bparees** [comment]
@s-urbaniak looks fine to me.  I think there's a follow up for @openshift/openshift-team-user-interface to figure out where to document best practices for publishing information like this (whether to do it in a configmap vs a status field of a resource, as well as naming patterns for URLs)

**Comment by kyoto** [comment]
/hold cancel
(per Ben's comment)

**Pull request merged**
