### PR TITLE
Bug 1955483: [4.6] Drop high-cardinality metrics from kube-state-metrics which aren't used

### PR DESCRIPTION
**Pull request by arajkumar**
Cherry-picked https://github.com/openshift/cluster-monitoring-operator/pull/1141 and https://github.com/openshift/cluster-monitoring-operator/pull/1163

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.00

approved

**Pull request merged**
