### PR TITLE
add verticalpodautoscalers to kube-state-metrics

### PR DESCRIPTION
**Pull request by matthyx**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by matthyx** [comment]
@fpetkovski I would like to add vpa metrics to OpenShift in order to use existing dashboards:

The documentation is here: https://github.com/kubernetes/kube-state-metrics/blob/master/docs/verticalpodautoscaler-metrics.md#examples

Do you see how this could integrate within the Operator? Should we detect [an existing VPA](https://docs.openshift.com/container-platform/4.8/nodes/pods/nodes-pods-vertical-autoscaler.html) and configure `kube-state-metrics` accordingly?
Or maybe this should be an option in the [ConfigMap](https://docs.openshift.com/container-platform/4.8/monitoring/configuring-the-monitoring-stack.html#creating-cluster-monitoring-configmap_configuring-the-monitoring-stack)?

Thanks in advance for your guidance.

**Comment by matthyx** [comment]
@PhilipGough can you have a look?

**Review by PhilipGough — COMMENTED** [review]
Hey @matthyx - I understand where you are coming from with this PR, but in short, we generally don't accept patches like this in this project from external contributors. 

The process here generally requires prioritisation from a PM perspective etc so if this is a requirement for you, I suggest opening a support ticket which can become an RFE.

**Comment by matthyx** [comment]
@PhilipGough it's https://issues.redhat.com/browse/RFE-2009

**Comment by PhilipGough** [comment]
@matthyx - thanks for both the link and your willingness to help on the implementation.

It won't make 4.10 because it is already cut but let's see if we can get some eyes on the RFE for 4.11

cc @jan--f

**Comment by matthyx** [comment]
Thanks 👍

**Pull request closed without merging**
