### PR TITLE
Bug 1766181: trustedCA bundle support for prometheus and its sidecars

### PR DESCRIPTION
**Pull request by paulfantom**
Same as https://github.com/openshift/cluster-monitoring-operator/pull/529 but for prometheus. 

~This won't work until upstream prometheus-operator has support for `VolumeMounts` in prometheus CRD (https://github.com/coreos/prometheus-operator/pull/2871).~

Part 3/3 of fixing oauth-proxy problems with trustedCA budle :)

### CODE REVIEW

**Comment by LiliC** [comment]
> This won't work until upstream prometheus-operator has support for VolumeMounts in prometheus CRD (working on it).

Is this really the case, we do merges there so it should work just fine without the VolumeMounts, no?

**Comment by s-urbaniak** [comment]
@LiliC we do merges, but as discussed upstream @brancz mentioned in a previous discussion that we should avoid them and rather should prefer explicit settings. This would also align it with the Alertmanager CRD.

**Comment by s-urbaniak** [comment]
@paulfantom @LiliC that's a fair assertion. Let's go with a patch-approach at least here, but let's also discuss where we want to go with VolumeMounts support upstream and the general patch-approach midterm, as it was considered not best-practice by @brancz (unless I misunderstood).

**Comment by s-urbaniak** [comment]
@paulfantom @LiliC I added the patch-merge approach on top, PTAL

**Comment by s-urbaniak** [comment]
I was able to reproduce the failing e2e-aws-operator e2e test locally. It is quite flaky but not related to this PR per se:

```
$ go test ./test/e2e -run TestPrometheusAdapterCARotation --kubeconfig=$KUBECONFIG -v
=== RUN   TestPrometheusAdapterCARotation
--- FAIL: TestPrometheusAdapterCARotation (302.11s)
    prometheusadapter_test.go:280: getting new api auth secret failed: secrets "prometheus-adapter-6bchksl8hfufm" not found
FAIL
2019/11/21 16:27:48 tests failed
FAIL	github.com/openshift/cluster-monitoring-operator/test/e2e	312.325s
```

Investigating on why we are flaking here.

**Comment by s-urbaniak** [comment]
sorry, the above failure was because I disabled CMO on the cluster. I believe something changed in origin which reconciles away the changes we do on `requestheader-client-ca-file` of `kube-system/extension-apiserver-authentication` so I suggest to disable that test for now.

**Pull request merged**
