### PR TITLE
OCPBUGS-33955: remove deprecated logtostderr argument

### PR DESCRIPTION
**Pull request by marioferh**
related: https://github.com/openshift/cluster-monitoring-operator/pull/2077

### CODE REVIEW

**Comment by danielmellado** [comment]
Shouldn't we also remove [this one](https://github.com/openshift/cluster-monitoring-operator/blob/master/hack/ocp-images.sh#L96)?

**Comment by simonpasquier** [comment]
> Shouldn't we also remove [this one](https://github.com/openshift/cluster-monitoring-operator/blob/master/hack/ocp-images.sh#L96)?

I'm not even sure if this script is still in use by someone (at least not me).

I've found other occurrences of the argument in manifests/ directory and for openshift-state-metrics.

**Comment by marioferh** [comment]
> > Shouldn't we also remove [this one](https://github.com/openshift/cluster-monitoring-operator/blob/master/hack/ocp-images.sh#L96)?
> 
> I'm not even sure if this script is still in use by someone (at least not me).
> 
> I've found other occurrences of the argument in manifests/ directory and for openshift-state-metrics.

I've removed the ones in use, that script seems old and used by no one.

**Comment by marioferh** [comment]
The ones from state-metrics:
```
assets/openshift-state-metrics/deployment.yaml:        - --logtostderr
assets/openshift-state-metrics/deployment.yaml:        - --logtostderr
```

come from some jsonnet but I cannot find where :S

**Comment by simonpasquier** [comment]
from https://github.com/openshift/openshift-state-metrics/blob/59b8a0ffc0a472e819e0c30911201c34c85a4684/jsonnet/openshift-state-metrics.libsonnet#L149-L173 so you'd need a PR to openshift/openshift-state-metrics first.

**Comment by marioferh** [comment]
> from https://github.com/openshift/openshift-state-metrics/blob/59b8a0ffc0a472e819e0c30911201c34c85a4684/jsonnet/openshift-state-metrics.libsonnet#L149-L173 so you'd need a PR to openshift/openshift-state-metrics first.

right, thanks

**Comment by marioferh** [comment]
openshift-state-metrics related https://github.com/openshift/openshift-state-metrics/pull/114

**Comment by simonpasquier** [comment]
@marioferh can you bump the openshift-state-metrics jsonnet version?

**Comment by marioferh** [comment]
> @marioferh can you bump the openshift-state-metrics jsonnet version?

facing some issues with make generate:
```
+ echo 'Created temporary directory at /tmp/tmp.0T9ndBqxqH'
Created temporary directory at /tmp/tmp.0T9ndBqxqH
+ jsonnet -J jsonnet/vendor -J tmp/json-manifests jsonnet/main.jsonnet
RUNTIME ERROR: Field does not exist: rows
        jsonnet/main.jsonnet:190:149-163        thunk from <object <anonymous>>
        jsonnet/main.jsonnet:190:81-164 object <anonymous>
        jsonnet/vendor/github.com/brancz/kubernetes-grafana/grafana/grafana.libsonnet:100:25-79 object <anonymous>
        jsonnet/components/dashboards.libsonnet:63:43-60        thunk from <object <data>>
        jsonnet/components/dashboards.libsonnet:63:29-61        object <data>
        jsonnet/components/dashboards.libsonnet:66:18-25        object <anonymous>
        jsonnet/components/dashboards.libsonnet:82:43-67        thunk from <object <anonymous>>
        jsonnet/components/dashboards.libsonnet:82:24-76        object <anonymous>
        jsonnet/components/dashboards.libsonnet:123:43-60       thunk from <object <data>>
        jsonnet/components/dashboards.libsonnet:123:29-61       object <data>
        jsonnet/components/dashboards.libsonnet:133:15-22       object <anonymous>
        jsonnet/components/dashboards.libsonnet:138:43-67       thunk from <object <anonymous>>
        jsonnet/components/dashboards.libsonnet:138:24-76       object <anonymous>
        Field "cluster-total.json"
        Field "data"
        Array element 0
        Field "items"
        Field "dashboards/consoleDashboardDefinitions"
        During manifestation

make: *** [Makefile:153: build-jsonnet] Error 1
```

**Comment by marioferh** [comment]
now it works :D

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Pull request merged**
