### PR TITLE
Bug 1875470: Include OS, arch labels for node, core count

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
As OpenShift becomes heterogeneous, it is ideal to get a feel of how many nodes
belong to a certain OS type, arch etc via telemetry. Especially with OpenShift
supporting Windows nodes in 4.6, the Windows Containers team would like to get
- Total number of Windows nodes used by all customers
- Total number of cores on the Windows nodes

This commit adds OS and arch labels to following rules:
- cluster:capacity_cpu_cores:sum
- cluster:node_instance_type_count:sum

which will help us in telemetry

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@ravisantoshgudimetla please rebase, the e2e tests should be fixed now.

**Comment by Anandnatraj** [comment]
We will need to capture the core count for licensing purposes.

**Pull request merged**
