### PR TITLE
MON-2222: Enable validating webhook for AlertmanagerConfig custom resources

### PR DESCRIPTION
**Pull request by PhilipGough**
Fixes https://issues.redhat.com/browse/MON-2222

* [x] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by PhilipGough** [comment]
cc @juzhao for qe input

**Comment by PhilipGough** [comment]
/label docs-approved

Have chatted to @bburt-rh about this one and the overarching epic

**Comment by PhilipGough** [comment]
cc @sferich888 for px-approval

**Comment by jan--f** [comment]
/retitle MON-2222: Enable validating webhook for AlertmanagerConfig custom resources

**Comment by juzhao** [comment]
the alertmanagerconfig validation is enabled on the cluster, only one low severity bug: https://bugzilla.redhat.com/show_bug.cgi?id=2064705
since it is a low severity error, we can merge code first
/label qe-approved

**Pull request merged**
