### PR TITLE
Bug 1995699: Get insights on series churn during upgrades

### PR DESCRIPTION
**Pull request by arajkumar**
Cherry-picks #1313

The following metrics will be sent to the telemeter,

scrape_samples_post_metric_relabeling: reports the numbers of samples that the target produced, after metric_relabel_configs is applied.
scrape_series_added: reports how many new series were created in a given scrape.

The above metrics would help us to gather information about series churn during upgrades since it will be helpful to know the additional memory usage that Prometheus will have to handle after the update.

This may also be helpful to detect high-cardinality metrics and malicious targets.

Co-authored-by: Simon Pasquier <spasquie@redhat.com>
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by arajkumar** [comment]
/retitle Bug 1998969: Get insights on series churn during upgrades

**Comment by arajkumar** [comment]
/retitle Bug 1995699: Get insights on series churn during upgrades

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by juzhao** [comment]
tested with the PR, issue is fixed.
/lgtm
/label qe-approved

**Pull request merged**
