### PR TITLE
MON-2981: alertingrule and relabel: promote to v1

### PR DESCRIPTION
**Pull request by jan--f**
`AlertingRules` and `AlertRelabelConfigs` APIs have been promoted to v1 in https://github.com/openshift/api/pull/1406. This PR updates CMO's `openshift/api` and `openshift/client-go` dependencies to pull this promotion and add the necessary changes in CMO.
These changes are mostly around renaming imports, dropping the `TechPreview` checks and renaming a role, that adds rbac rules for CMO to manage the new resrouces.

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by jan--f** [comment]
/hold
I want to reword the commit message at least.

**Comment by jan--f** [comment]
@bburt-rh We have docs but we need to remove the tech-preview note. Just making sure we track that. And please feel free to add `docs-apprived`.
@juzhao for `qe-approved`.
@Senthamilarasu-STA for `px-approved`.

**Comment by bburt-rh** [comment]
@jan--f - The doc work to remove the tech preview verbiage from the content for the main feature is being tracked as a `must-have` for the 4.14 release in the following issue: https://issues.redhat.com/browse/RHDEVDOCS-4844

**Comment by jan--f** [comment]
/hold
for 4.14 feature freeze

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn

**Pull request merged**
