### PR TITLE
Expose CMO metrics over TLS

### PR DESCRIPTION
**Pull request by paulfantom**
as in title

### CODE REVIEW

**Comment by s-urbaniak** [comment]
implementation side note: TLS rotation is handled in-process inside kube-rbac-proxy

**Comment by s-urbaniak** [comment]
@paulfantom potential follow-up though: can we make CMO listen on `127.0.0.1` only?

**Comment by paulfantom** [comment]
@s-urbaniak that's a good idea :+1: I'll take care of it in a follow-up PR.

**Pull request merged**
