### PR TITLE
Bug 2008911: Revert "Configure prometheus operator TLS based on the cluster APIServer config"

### PR DESCRIPTION
**Pull request by stbenjam**
This bug is blocking release payloads. See https://bugzilla.redhat.com/show_bug.cgi?id=2008911 .  Based on timing and the area of the change, openshift/cluster-monitoring-operator#1380 looks like a likely candidate.  

Reverts openshift/cluster-monitoring-operator#1380

### CODE REVIEW

**Comment by stbenjam** [comment]
/hold

Pending investigation by the monitoring team.

**Comment by deads2k** [comment]
Mostly blocked payload promotion has a broad impact.  If this change looks plausible to the monitoring team as well, we should merge the revert early and fix the problem alongside an unrevert in a later PR.

**Comment by dgrisonnet** [comment]
This change sounds plausible considering the bug that we are seeing. We have not yet found out the exact root cause, but let's proceed with the revert first and resume the investigation afterward.

/cc @fpetkovski 

/lgtm
/unhold

**Comment by stbenjam** [comment]
/hold

Let's try to land the fix https://github.com/openshift/cluster-monitoring-operator/pull/1409 first

**Comment by fpetkovski** [comment]
/hold

We already have a fix that will likely fix this issue: https://github.com/openshift/cluster-monitoring-operator/pull/1409 Do we want to merge that one instead?

**Comment by deads2k** [comment]
> /hold
> 
> We already have a fix that will likely fix this issue: #1409 Do we want to merge that one instead?

I'd like the fix too, but its current upgrade job didn't run, so it cannot land before the next payload is ready.  I'd like to see the upgrade job here overridden (the last run failed on an etcd alert failure, but fixed the generation problem) and have this land for our next payload.

Since #1409 has to rerun CI anyway, please unrevert in that PR.

/hold cancel

**Comment by deads2k** [comment]
nothing has merged since this PR was opened.  the failed upgrade job from above upgraded fine and failed on an etcd high grpc count, but the cyclical deployment was fixed.  I'm merging this to free our payload promotion.

**Pull request merged**
