### PR TITLE
[release-4.5] Bug 1906081: jsonnet: remove apiserver_request:availability30d

### PR DESCRIPTION
**Pull request by dgrisonnet**
Backport of #980 to release-4.5.

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by juzhao** [comment]
tested with cluster-bot
`launch openshift/cluster-monitoring-operator#1016 aws`
apiserver_request:availability30d record rules are removed

/lgtm

**Comment by markmc** [comment]
(patch manager) seems to be significantly impacting real-world users

**Pull request merged**
