### PR TITLE
Bug 1773246: Add a rule that sums the nodes reporting virt_platform types

### PR DESCRIPTION
**Pull request by smarterclayton**
This will be sent via telemetry to allow us to distinguish virt with no
cloud provider from bare metal with no cloud provider unambiguously and
better serve our users.

/hold

Waiting for node_exporter change and telemetry change

### CODE REVIEW

**Comment by LiliC** [comment]
You need a different bugzilla, the https://bugzilla.redhat.com/show_bug.cgi?id=1773243 is set for 4.3.

**Comment by LiliC** [comment]
It's a valid failure, guess we need the changes in node-exporter first:

> fail [github.com/openshift/origin/test/extended/operators/images.go:139]: Nov 18 17:53:25.721: Pods found with invalid container images not present in release payload: openshift-monitoring/node-exporter-dct5c/init-textfile image=openshift/prometheus-node-exporter:v0.16.0

**Comment by smarterclayton** [comment]
/hold cancel

Trivially rebased, will tag if this goes green.

**Comment by smarterclayton** [comment]
Rebased, everything is green, restoring LGTM

**Pull request merged**
