### PR TITLE
Bug 1987197: hack,jsonnet: Better version checker

### PR DESCRIPTION
**Pull request by paulfantom**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

I had some unfinished code on my laptop so I decided to finish it now and here is a result :)

We had issues with shipping a component in a version that is not correctly reflected in manifests labels. To prevent this we implemented a central place for keeping version numbers in the form of `jsonnet/versions.json` file. Sadly the first version of a script generating that file was able to be run only in interactive mode, so it couldn't be enforced and checked in CI. This PR refactors the logic behind keeping `versions` file in sync.

What changed:
- versions.json moved to YAML format with a slightly different schema. YAML was chosen as it allows comments.
- jsonnet version was updated to allow using `std.parseYaml` function
- script `hack/generate-versions.sh` now parses the version file and prints what has changed
- script `hack/generate-versions.sh` can be run in a non-interactive mode. It then uses whatever is set in local `jsonnet/versions.yaml` file. This behavior will cause that grafana and prometheus-adapter <0.8.5 versions cannot be verified in CI.
- few dead scripts were removed from `hack/` directory.

After this is merged it would be good to add a non-blocking CI job that runs `INTERACTIVE=false make versions && git diff --exit-code`

/cc @simonpasquier @dgrisonnet

### CODE REVIEW

**Review by PhilipGough — APPROVED** [review]
/lgtm assuming we go green

This works for me on mac and makes a nice addition IMO

/hold for someone else to review

**Comment by paulfantom** [comment]
/retest
/unhold

unholding as there is no lgtm label :)

**Review by dgrisonnet — APPROVED** [review]
/lgtm

**Comment by paulfantom** [comment]
Rebased to fix merge conflicts.

**Pull request merged**
