### PR TITLE
OCPBUGS-22917: jsonnet: pin commits

### PR DESCRIPTION
**Pull request by jan--f**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by jan--f** [comment]
Can I
/label backport-risk-assessed
my own PRs?

**Comment by juzhao** [comment]
tested with PR
`launch 4.14,openshift/cluster-monitoring-operator#2143 aws,single-node`
there are transient error for kube-state-metrics, no such error later, could ignore the error
https://privatebin.corp.redhat.com/?37771e2865b3879d#6ND4Y6o3aV6b3F4gFLw1vbiqfQX12TWL1Rrddx7azAqg
/label cherry-pick-approved
/label qe-approved

**Pull request merged**
