### PR TITLE
readme: Point UWM docs link to 4.10 version

### PR DESCRIPTION
**Pull request by danielm0hr**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by jan--f** [comment]
/lgtm

Not sure why non of the checks are running...
/retest

**Comment by petr-muller** [comment]
This bit is weird:

```
$ PWD=/home/prow/go/src/github.com/openshift/cluster-monitoring-operator  git fetch https://github.com/openshift/cluster-monitoring-operator.git 3a9d0e37baf27fe2995c6dcfd5098c23901943e0
fatal: remote error: upload-pack: not our ref 3a9d0e37baf27fe2995c6dcfd5098c23901943e0

```

I can reproduce even locally... Looks like some GitHub gotcha, possibly related to the incidents they had recently? Could you try force-pushing so that we get a new SHA?

**Comment by petr-muller** [comment]
Maybe even simply trying to push again could help, without the force

**Comment by petr-muller** [comment]
@simonpasquier pls see https://github.com/openshift/cluster-monitoring-operator/pull/1593#issuecomment-1075450526 and https://github.com/openshift/cluster-monitoring-operator/pull/1593#issuecomment-1075454315

**Comment by jan--f** [comment]
@danielm0hr can you push a new SHA1?

**Pull request closed without merging**
