### PR TITLE
Bug 1904161: Use alertmanager_integrations metric instead of alertmanager_notifications_total for AlertmanagerReceiversNotConfigured

### PR DESCRIPTION
**Pull request by RiRa12621**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by RiRa12621** [comment]
/assign @simonpasquier
the bots want what the bots want

**Comment by RiRa12621** [comment]
@simonpasquier should I hold until the tests are fixed? Those seem unrelated but I guess that's becoming a bit noisy

**Comment by simonpasquier** [comment]
/hold
waiting for #985

**Comment by simonpasquier** [comment]
@RiRa12621 you'd need to resolve conflicts (` pkg/manifests/bindata.go ` is gone now!).

**Comment by simonpasquier** [comment]
/retitle Bug 1904161: Use alertmanager_integrations metric instead of alertmanager_notifications_total for AlertmanagerReceiversNotConfigured

**Comment by s-urbaniak** [comment]
@RiRa12621 ping, this just needs a rebase i guess :)

**Comment by RiRa12621** [comment]
/hold
depends on #1010

**Pull request merged**
