### PR TITLE
[MON-808] add ignoreNamespaceSelectors field

### PR DESCRIPTION
**Pull request by pgier**
Prevents service and pod monitors from selecting namespaces other than
their own.

### CODE REVIEW

**Comment by pgier** [comment]
rebased to fix bindata conflict

**Comment by paulfantom** [comment]
nit: Could we not include manually changed and generated stuff in the same commit, but split them into 2?

**Comment by pgier** [comment]
@paulfantom yeah, that makes sense, it would make the actual changes more clear and easier to rebase.  I'll do that in the future.

**Pull request merged**
