### PR TITLE
Unpin and update jsonnet dependencies

### PR DESCRIPTION
**Pull request by raptorsun**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

This PR upins jsonnet dependencies and update them to latest version.
The new version of admission-webhook library requires input of a secret name for its TLS certificate. So there is a modification on `admission-webhook.libsonnet`.

### CODE REVIEW

**Comment by raptorsun** [comment]
Test fails for the error consistently. Checking on which upgraded component brings us this behavior...
```
: [sig-arch] events should not repeat pathologically expand_less | 0s
{  1 events happened too frequently  event happened 4347 times, something is wrong: ns/openshift-kube-apiserver-operator deployment/kube-apiserver-operator - reason/PrometheusRuleUpdated Updated PrometheusRule.monitoring.coreos.com/v1 because it changed}
```

**Comment by raptorsun** [comment]
Tests can pass when prometheus-operator stays at version `release-0.60`. 
https://github.com/openshift/cluster-monitoring-operator/pull/1822

**Comment by JoaoBraveCoding** [comment]
/lgtm

/label px-approved
/label docs-approved
/label qe-approved

This is as usual after a new release branch is cut, we switch back tracking the master/main branches for each upstream project.

**Pull request merged**
