### PR TITLE
OCPBUGS-641: grafana: bump to 7.5.11

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by jan--f** [comment]
The version bump is in https://github.com/openshift/grafana/pull/88

**Comment by juzhao** [comment]
tested with PR, OCP 4.9 grafana version is 7.5.11 and no regression issue
/label qe-approved

**Pull request merged**
