### PR TITLE
hack: scripts: lint shellscripts and remove unused jenkins scripts

### PR DESCRIPTION
**Pull request by paulfantom**
Without it `make` is broken as shell scripts don't pass shellcheck.

Additionally I moved `deploy-on-openshift.sh` script to `hack/` directory to remove confusion between `scripts/` and `hack/`. It was easier to move this one remaining script to `hack/` than to move everything to `scripts/`

/cc @s-urbaniak @smarterclayton

### CODE REVIEW

**Comment by s-urbaniak** [comment]
I am wondering, why wasn't this catched in CI runs? Also, can we add shellheck on all `sh` files as a follow-up?
/lgtm

**Comment by squat** [comment]
Actually, if we want to ensure this doesn’t break again, we need to make spellcheck part of the ci test stage

**Comment by paulfantom** [comment]
Shellcheck as part of CI: https://github.com/openshift/release/pull/4437

**Pull request merged**
