### PR TITLE
WIP: Add CRI-O metrics as own ServiceMonitor

### PR DESCRIPTION
**Pull request by saschagrunert**
Adding CRI-O metrics in dedicated namespace rather than a kubelet mapping.

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by paulfantom** [comment]
Why should this be deployed by CMO and not MCO (Machine Config Operator)?

**Comment by saschagrunert** [comment]
> Why should this be deployed by CMO and not MCO (Machine Config Operator)?

It seemed to fit better here since we have all of the monitoring resources in place.

**Comment by paulfantom** [comment]
> It seemed to fit better here since we have all of the monitoring resources in place.

I disagree. CMO is the monitoring operator responsible for the shipping monitoring framework. This PR isn't adding anything to the framework, but only data collection from one specific component (CRI-O).

**Comment by saschagrunert** [comment]
@paulfantom Thank you for the input, I think that we can move over the logic into the MCO, too :upside_down_face:

**Pull request closed without merging**
