### PR TITLE
MON-3921: Revert "Revert "Merge pull request #2392 from machine424/f-…

### PR DESCRIPTION
**Pull request by machine424**
…alert""

This reverts commit e1fc00bd763d1c7e6d27b5b008eb3b322f06f057.

To re-introduce changes in https://github.com/openshift/cluster-monitoring-operator/pull/2392

This will be merged once the new e2e-hypershift-conformance test is green.

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by Tai-RedHat** [comment]
pr tested with cluster-bot

**Comment by machine424** [comment]
/payload-job-with-prs periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn-conformance https://github.com/openshift/hypershift/pull/4348

**Comment by machine424** [comment]
/payload-job-with-prs periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn-conformance openshift/hypershift#4348

**Comment by machine424** [comment]
/payload-job-with-prs periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn-conformance openshift/hypershift#4348

**Comment by machine424** [comment]
/payload-job-with-prs periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn-conformance openshift/hypershift#4348

**Comment by machine424** [comment]
> @machine424: trigger 1 job(s) for the /payload-(with-prs|job|aggregate|job-with-prs|aggregate-with-prs) command
> 
>     * periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn-conformance
> 
> 
> See details on https://pr-payload-tests.ci.openshift.org/runs/ci/53aafae0-4d88-11ef-8cf8-0a6efb8fedbc-0

With the hypershift fix, `shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured` check in hypershift tests is no longer failing.

strangely `ci/prow/e2e-hypershift-conformance` is also passing without the hypershift fix, the reason is that `shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured` may be checked before the alert is firing (I was expecting the check to run at the end)

**Comment by machine424** [comment]
/hold
until https://github.com/openshift/hypershift/pull/4348 or a similar fix is merged.

**Comment by machine424** [comment]
/hold cancel
https://github.com/openshift/hypershift/pull/4348 was merged.

**Pull request merged**
