### PR TITLE
jsonnet/components: remove PDB patches

### PR DESCRIPTION
**Pull request by simonpasquier**
All patches have been incorporated in upstream jsonnet projects.

Signed-off-by: Simon Pasquier <spasquie@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/label px-approved
/label qe-approved
/label docs-approved

This is only a refactoring of the jsonnet code without any impact on the generated manifests.

**Review by slashpai — COMMENTED** [review]
/lgtm

**Pull request merged**
