### PR TITLE
remove limits for pods

### PR DESCRIPTION
**Pull request by sjenning**
@smarterclayton @brancz 

follow on to my previous PR to make components run as Burstable, without limits

### CODE REVIEW

**Comment by sjenning** [comment]
ugh, i did it again.  these are generated files that i can't find the source for.

**Comment by sjenning** [comment]
doing this in https://github.com/openshift/prometheus-operator/pull/20

**Comment by squat** [comment]
@sjenning this one is a little more tricky :p 
These manifests are likewise all generated from jsonnet, however they come mostly from kube-prometheus, a distribution of monitoring components that we put together and are a dependency of this project [0]. The correct way to do this would be to write a mixin that removes limits for any object used in cluster monitoring operator. (We don’t want to remove the limits upstream in the kube-prometheus distro and other projects we are importing as they have valid use cases for limits). Please let me know if you need any help or want me to take over this and I can make a PR tomorrow. 

[0] 
https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/main.jsonnet#L1

**Comment by squat** [comment]
Note: kube-prometheus is being imported from the upstream repo, not the openshift repo 
https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/jsonnetfile.json#L7

**Comment by squat** [comment]
finished this in #273

**Pull request closed without merging**
