### PR TITLE
OCPBUGS-1062: update webhook configuration only if required

### PR DESCRIPTION
**Pull request by simonpasquier**
This change uses the `ApplyValidatingWebhookConfigurationImproved` method from the github.com/openshift/library-go module instead of the previous custom implementation.

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
The audit logs from the latest e2e-aws-ovn run show an improvement in terms of update frequency

````
$ kubectl-dev_tool -f registry-build01-ci-openshift-org-ci-op-lm26kgc5-stable-sha256-512cd85c0443d448916b2282d49163771fb319b1abb6bd18e75b2b42ca3064af/audit_logs/ audit --resource=validatingwebhookconfigurations.* --user=system:serviceaccount:openshift-monitoring:cluster-monitoring-operator --verb update
had 83757 line read failures
10:18:31 [UPDATE][     2.987ms] [200] /apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/prometheusrules.openshift.io     [system:serviceaccount:openshift-monitoring:cluster-monitoring-operator]
10:18:31 [UPDATE][     2.987ms] [200] /apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/prometheusrules.openshift.io     [system:serviceaccount:openshift-monitoring:cluster-monitoring-operator]
10:18:31 [UPDATE][     2.942ms] [200] /apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/alertmanagerconfigs.openshift.io [system:serviceaccount:openshift-monitoring:cluster-monitoring-operator]
10:18:31 [UPDATE][     2.942ms] [200] /apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/alertmanagerconfigs.openshift.io [system:serviceaccount:openshift-monitoring:cluster-monitoring-operator]
````

**Comment by juzhao** [comment]
@simonpasquier tested with cluster-bot cluster with PR
`launch openshift/cluster-monitoring-operator#2065`
watched prometheus-operator-admission-webhook pod logs for a few minutes, still see 1-2 error logs `remote error: tls: bad certificate`, much more less than 4.12, see http://pastebin.test.redhat.com/1107240

**Comment by simonpasquier** [comment]
@juzhao yes I'm quite sure that it won't fix all `remote error: tls: ...` log messages but it should definitely help.
Chatted with @rexagod and we want to apply the same optimization to all the create/update operations performed by CMO.

**Pull request merged**
