### PR TITLE
Bug 1750283: Backport metric for core capacity by node role and operating system.

### PR DESCRIPTION
**Pull request by chambridge**
Backport the following to 4.1: https://github.com/openshift/cluster-monitoring-operator/pull/466

### CODE REVIEW

**Comment by LiliC** [comment]
First we have to merge this https://github.com/openshift/kube-state-metrics/pull/17

**Comment by LiliC** [comment]
@chambridge now that this is merged we need a PR in telemeter to whitelist this.

**Comment by chambridge** [comment]
@LiliC I have created the whitelist PR for telemeter here:
https://github.com/openshift/telemeter/pull/252

**Pull request merged**
