### PR TITLE
Bug 1862896: bring back containerized generate target

### PR DESCRIPTION
**Pull request by paulfantom**
To simplify one time contributions and remove the need for installing tooling on the host. This target is slower than having tools on the host but deals with installing dependencies.

Note: Inline building of a container image is necessary to prevent generating all assets with root ownership.

~This PR depends on https://github.com/openshift/cluster-monitoring-operator/pull/887 so putting on hold
/hold~ apparently it doesn't :shrug: 

/cc @openshift/openshift-team-monitoring 

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by lilic** [comment]
/hold

Lets add this to the contributing section maybe as well, that this exists?

**Comment by paulfantom** [comment]
> Lets add this to the contributing section maybe as well, that this exists?

My thinking was that this is a last resort target and that we should point users towards `make generate` to catch problems with our tooling. Hence no entry in docs.

**Comment by lilic** [comment]
How will they know to resort to this?

**Comment by paulfantom** [comment]
Closing in favor of #895

**Pull request closed without merging**
