### PR TITLE
OCPBUGS-39126: disable user-defined monitoring per object

### PR DESCRIPTION
**Pull request by simonpasquier**
Before this change, a project owner could only disable user-defined monitoring per namespace/project (typically to prevent the `PrometheusOperatorRejectedResources` alert from firing).

To provide greater flexibility, it is now possible to exclude individual objects (e.g. `ServiceMonitor`, `PodMonitor` and `PrometheusRule`) by adding the `openshift.io/user-monitoring="true"` label to them.

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold
need to update the e2e tests

**Comment by simonpasquier** [comment]
I've tested the PR to see if it could help with issues like 

After deploying the compliance operator and otel operator + enabling user-defined monitoring, I see the PrometheusOperatorRejectedResources active (as expected):

image

image

After labeling the 2 service monitor objects with `openshift.io/user-monitoring="false"`, the alert went away:

image

**Comment by machine424** [comment]
/lgtm
But I’m concerned this might discourage users from addressing the root cause of the issue: deploying operators in the wrong ns.
Also, this could create confusion (I don't know if we want to document it or not) as now looking at the ns labels isn't enough to be sure a resource would be considered.

nit: I think you meant `openshift.io/user-monitoring="false"` in the PR desc.

**Pull request merged**
