### PR TITLE
Bug 1859791: alert is firing KubeJobCompletion and KubeJobFailed at the same time

### PR DESCRIPTION
**Pull request by drpaneas**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/retitle Bug 1859791: alert is firing KubeJobCompletion and KubeJobFailed at the same time

Changing the title because 1859791 is the bugzilla ticket targeting 4.5.z. We need 185973 to be fixed first and this should be done once we update the mixin dependencies as part of https://github.com/openshift/cluster-monitoring-operator/issues/847.

**Comment by RiRa12621** [comment]
/hold
maybe let's stop the pinging until the depending bug is moved ahead

**Comment by lilic** [comment]
Seems like this now needs a rebase as something else was merged.

**Comment by drpaneas** [comment]
Is there anything needed here?

**Comment by s-urbaniak** [comment]
@drpaneas this is now out of our control. This PR is now enqueued for cherry-picking. There is another team responsible for this.

**Comment by RiRa12621** [comment]
@s-urbaniak is it possible that the PR is still missing "LGTM"?

**Comment by lilic** [comment]
/hold
This needs a rebase.

**Pull request merged**
