### PR TITLE
Add cluster:vmi_request_cpu_cores:sum into Telemetry

### PR DESCRIPTION
**Pull request by erkanerol**
OpenShift Virtualization team wants to know how much CPUs are requested by VMIs to get more insights about VMIs sizes.

Origin of the recording rule: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1530

Signed-off-by: Erkan Erol <eerol@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/lgtm

did you get the acknowledgement from @smarterclayton to add this metric?

**Comment by simonpasquier** [comment]
/hold
until explicit approval

**Comment by dgrisonnet** [comment]
We also need to hold until https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1530 is merged.

**Comment by erkanerol** [comment]
@sthaha  @simonpasquier  @dgrisonnet I had a comment in my PR and I need to update the name of the metric. The question: Can we use different prefix other than "cnv"?  "cnv"   refers downstream while we are adding this metric into our upstream repo. Therefore, we want to use something different like "vmis"? Can we use different prefixes according to domain even all of them belong to same organization ("kubevirt") ?

**Comment by dgrisonnet** [comment]
Usually, the prefix that we use downstream is the scope of the recording rule, so it can be something `cluster` or `openshift`. But since you already added a telemetry rule with `cnv` as a prefix, I think it would be better to stick with that downstream. That said, you can always have different naming downstream and upstream, you just have to map the upstream recording rule to a downstream one in: https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/cluster-monitoring-operator/prometheus-rule.yaml.

You could add a new recording rule similar to:
```yaml
    - expr: your_upstream_recording_rule
      record: cnv:vmi_request_cpu_cores:sum
```

Also, if it doesn't really make sense to have the recording rule upstream, you can have it strictly downstream. This is also an option.

**Comment by erkanerol** [comment]
@dgrisonnet Thanks for the explanation. I changed the prefix as "cluster" and the PR in hyperconverged-cluster-operator is merged now.  Could you please review this PR again?

**Comment by dgrisonnet** [comment]
/lgtm

Still waiting for @smarterclayton approval before unholding.

**Comment by erkanerol** [comment]
@smarterclayton May I get a review?

**Comment by smarterclayton** [comment]
Approved for this metric with cardinality one.

**Comment by erkanerol** [comment]
@dgrisonnet is "versions" test broken?

**Comment by dgrisonnet** [comment]
No, it is just an informative job that isn't required.

/label px-approved
/label qe-approved
/label docs-approved

No user-facing changes, this PR adds metrics to telemetry that are only available to Red Hat employees.

**Comment by erkanerol** [comment]
@dgrisonnet  The bot seems trying to fix that job.

**Pull request merged**
