### PR TITLE
Bug 1814840: node-exporter: add systemd enable restart metrics

### PR DESCRIPTION
**Pull request by rphillips**
Enables `--collector.systemd.enable-restarts-metrics` to add `service_restart_total` metric

### CODE REVIEW

**Comment by rphillips** [comment]
weird... an automatic approved label?

**Comment by rphillips** [comment]
This PR looks correct. Not sure why the generate CI failed.

/assign @lilic

**Comment by s-urbaniak** [comment]
no concern once green
/cc @paulfantom

**Comment by lilic** [comment]
The generate job failed because you need to pull the latest image or rebase the PR:
`docker pull quay.io/coreos/jsonnet-ci && make clean && generate-in-docker  `

**Comment by paulfantom** [comment]
`ci/prow/generate` was failing due to outdated `jsonnetfile.*` files. This should be already fixed on master branch and issue should go away after rebasing.

**Comment by rphillips** [comment]
@lilic this adds one metric per slice

**Comment by rphillips** [comment]
rebased, read for review

**Comment by rphillips** [comment]
/retitle Bug 1814840: node-exporter: add systemd enable restart metrics

**Comment by lilic** [comment]
> This is a useful metric to know if slices are restarting a number of times.

Why is it a bug and not an RFE? :)

 > this adds one metric per slice

In total in a number cluster how many series do we have, do you mind checking. Thanks!

**Comment by rphillips** [comment]
Enabled the option to test this out and retrieve the count for Lili, but found out the container node_exporter runs in doesn't have the permissions to pull the systemd information: `Failed to get D-Bus connection: Operation not permitted`. I'll have to figure that out first.

/hold

**Comment by rphillips** [comment]
node_exporter is running as nobody with an SCC [[source]](https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/node-exporter.jsonnet#L42-L65). We won't be able to get the systemd metrics unless we increase the privileges for the node_exporter to run as root.

**Comment by brancz** [comment]
The systemd collector both needs to be privileged and is resource intensive, I don't think we should be enabling it to get a single metric that might be useful. Do we have an incident or something that even describes why we would want this metric? I suspect this is a case of cause vs symptom based alerting.

**Comment by rphillips** [comment]
@smarterclayton, was asking for a metric to count when services were crashing.

**Comment by smarterclayton** [comment]
systemd restarts are probably the #1 non container failure indicator.  I was horrified upon realizing we didn't collect it.

If the collector is intensive, we should figure out how to make it not so.  If it's high cardinality, again we should probably have a much more streamlined one.  The privileged issue is somewhat of a problem, but if that's a concern we could isolate it by having a sidecar track it (just that) and expose that on filesystem in a shared volume.

I would rather have systemd restart than 90% of the metrics node_exporter gathers right now :). Agree we should do it the right way.

**Comment by lilic** [comment]
As said on slack:
I understand the importance of this metric, agree we should have it, my main concerns are:
1. that node-exporter would be privileged - its not today, it would be better to keep it that way, maybe we could use the separate systemd exporter (https://github.com/povilasv/systemd_exporter)
2. the amount of series it would produce
3. its resource intentive which is why its off by default in node-exporter
I think this needs a bit more thought, maybe an RFE would be better than a bugzilla, as not having a metric is not a bug. :)

**Comment by smarterclayton** [comment]
Note that node exporter init has privilege so that we can read dmidecode, so a sidecar is not unreasonable (but should be isolated).

If systemd collector is not the right tool for the job, how do we make it or an alternative the right tool for the job?  Running a standalone collector won't address cardinality issues or resource issues.  A minimal sidecar loop for node_exporter for just restart metrics would be the simplest condition, but that is going to be associated more closely with node exporter than something else (the pod for node exporter should contain the things that export metrics for openshift).  If we have another systemd metric in the future, we would add it to the same place.

**Comment by lilic** [comment]
> Note that node exporter init has privilege so that we can read dmidecode, so a sidecar is not unreasonable (but should be isolated).

Not sure that is enough, but not my level of expertise, but I think the entire node-expoter container might need to be privileged for this. Can we verify this? @rphillips 

> Running a standalone collector won't address cardinality issues or resource issues.

Sorry, let me clarify: running standalone collector can address the privilege issue yes. From what I heard the standalone systemd collector is less resource heavy and would work better than the built in node-exporter systemd collector. But @pgier might know more about that.

**Comment by rphillips** [comment]
@lilic yeah, I was testing out with cluster-bot... the correct directories get propagated into the container, but then we get selinux denials trying to access the socket. It does look like we need to escalate the privileges to be able to get the metrics.

**Comment by rphillips** [comment]
Closing in favor of the enhancement: https://github.com/openshift/enhancements/pull/255

**Pull request closed without merging**
