### PR TITLE
jsonnet: remove ksonnet

### PR DESCRIPTION
**Pull request by paulfantom**
Removing ksonnet dependency. Tracked in [MON-1294](https://issues.redhat.com/browse/MON-1294).

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by paulfantom** [comment]
I removed ksonnet and changed `assets/prometheus-k8s/kube-rbac-proxy-secret.yaml` to be printed in human-readable form instead of base64.

**Comment by s-urbaniak** [comment]
No docs, or CEE training needed as this affects asset generation at build time only, no functional changes during runtime.

Nevertheless pinging @juzhao for QE ack.

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Pull request merged**
