### PR TITLE
jsonnet/kube-state-metrics.jsonnet: Increase scrape interval

### PR DESCRIPTION
**Pull request by lilic**
As discussed with @brancz we can increase this to 1 minute for now, to have more precise metrics. This will not increase the amount of series we track, but just the number of samples in it, which gets more optimal the more samples we add.

cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by paulfantom** [comment]
> Increase scrape interval

More like "decrease" :P

/lgtm

**Comment by lilic** [comment]
Sorry meant increase frequency, make sense in my head :D

**Comment by lilic** [comment]
> ci/prow/generate — Pod pending timeout.
:O

**Comment by lilic** [comment]
/hold

quay is down so can't pull the CI image...

**Pull request merged**
