### PR TITLE
Bug 1805116: Use aggregated up metrics

### PR DESCRIPTION
**Pull request by s-urbaniak**
I also want to bump telemeter-client here, hence WIP

### CODE REVIEW

**Comment by bparees** [comment]
skipping this one for approval this week due to bug severity and the number of other changes already accepted.

**Comment by s-urbaniak** [comment]
@bparees sounds good, thanks for the heads-up!

**Comment by lilic** [comment]
> 2020/03/06 07:46:26 Container setup in pod e2e-aws-upgrade completed successfully
2020/03/06 08:22:15 Container test in pod e2e-aws-upgrade completed successfully
2020/03/06 08:30:50 Container teardown in pod e2e-aws-upgrade completed successfully
2020/03/06 08:30:50 Pod e2e-aws-upgrade succeeded after 1h17m9s

But then it says failed 🤔

**Pull request merged**
