### PR TITLE
Bug 1791200: Add alert for no routes configured in alertmanager

### PR DESCRIPTION
**Pull request by paulfantom**
Backporting #585

/cc @s-urbaniak @LiliC @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
/hold

This doesn’t seem to be firing on 4.4 on CI clusters

**Comment by LiliC** [comment]
Just seen on latest 4.4 cluster, think we can remove the hold
> Alerts are not configured to be sent to a notification system, meaning that you may not be notified in a timely fashion when important failures occur. Check the OpenShift documentation to learn how to configure notifications with Alertmanager.

**Comment by LiliC** [comment]
Ah the failure makes sense:
>             s: "promQL query: ALERTS{alertname!~\"Watchdog|UsingDeprecatedAPIExtensionsV1Beta1\",alertstate=\"firing\"} >= 1 had reported incorrect results: ALERTS{alertname=\"AlertmanagerReceiversNotConfigured\", alertstate=\"firing\", severity=\"warning\"} => 1 @[1579875925.783]",

We need to merge the origin PR for 4.3 first :)

**Comment by paulfantom** [comment]
Rebased. Blocking origin PR is merged now.

/hold cancel

**Pull request merged**
