### PR TITLE
Bug 1773665: add cluster cpu recording rules

### PR DESCRIPTION
**Pull request by pgier**
This backports commit 68dccbeb39ce32c36a18089031e47d90be113a93 which
updates cluster cpu recording rules to more accurately track
number of cores and hyperthreading cpus.

### CODE REVIEW

**Comment by pgier** [comment]
Backport of #544

**Comment by chambridge** [comment]
@pgier don't you need to backport this change first? or in the PR also?
https://github.com/openshift/cluster-monitoring-operator/pull/498

**Comment by pgier** [comment]
@chambridge Ah you're right, I was thinking that was already backported.
/hold

**Comment by pgier** [comment]
This depends on new build of node_exporter after changes in https://github.com/openshift/node_exporter/pull/46

**Comment by pgier** [comment]
/hold cancel
The new build of node_exporter is available

**Comment by pgier** [comment]
@chambridge Does this look ok?

**Comment by chambridge** [comment]
Do we need this update?
https://github.com/openshift/cluster-monitoring-operator/pull/498/files#diff-ea42f2a19bba3e07005d6b437ed1a902R27

Would have also expected a change to `pkg/manifests/bindata.go `

**Comment by chambridge** [comment]
LGTM!

**Pull request merged**
