### PR TITLE
Update jsonnet bundler v0.3.1

### PR DESCRIPTION
**Pull request by pgier**
The update to the jsonnet-ci image seems to be causing failures in other PRs (#701, #702).

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@pgier we should have a look at https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/703/pull-ci-openshift-cluster-monitoring-operator-master-e2e-aws-operator/1812, it seems to be a legit failure.

**Comment by s-urbaniak** [comment]
let's see if it is consistent.

**Comment by pgier** [comment]
I'm guessing it's still a flake even though it's one of our tests.  There aren't any changes to CMO sources in this PR.  It only changes the vendored build code which is used only in local builds (not in CI) to generate the same assets that are already committed.

**Pull request merged**
