### PR TITLE
[MON-1786] Document Prometheus Adapter audit log configuration

### PR DESCRIPTION
**Pull request by sthaha**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by sthaha** [comment]
/px-approved
/qe-approved


Since the code changes are already merged.

**Comment by simonpasquier** [comment]
/label docs-approved

since @bburt-rh already approved in https://github.com/openshift/cluster-monitoring-operator/pull/1490#issuecomment-982052543

**Pull request merged**
