### PR TITLE
MON-3789: add a golangci-lint-fix makefile target to fix golangci-lint errros when possible

### PR DESCRIPTION
**Pull request by machine424**
…hen possible

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by danielmellado — COMMENTED** [review]
/lgtm althought we could use a small note on the dev docs

**Comment by machine424** [comment]
> /lgtm althought we could use a small note on the dev docs

I don't see any section about linting, I could take care of that but in another PR.

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by machine424** [comment]
/retitle MON-3789: add a golangci-lint-fix makefile target to fix golangci-lint errros when possible

**Pull request merged**
