### PR TITLE
CFE-551: Allowlist metrics related to Routes to be sent via telemetry

### PR DESCRIPTION
**Pull request by arkadeepsen**
Added recording rules for metrics related to routes to be sent via telemetry. Also allowlisted them in the config file.

The list of metrics can be found in this doc under the section `Metrics to be sent via telemetry`: https://docs.google.com/document/d/1Ojlpm2OTmGPY-5aHcP80HF7deBf1DRWARLrsSkrWneA/edit#heading=h.8glj3h3fewji

The approval for the same was obtained here: https://coreos.slack.com/archives/C03SXF61V50/p1663331554761249

Signed-off-by: Arkadeep Sen <arsen@redhat.com>
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by arkadeepsen** [comment]
/hold
until  https://github.com/openshift/cluster-ingress-operator/pull/779 is merged

**Review by jan--f — CHANGES_REQUESTED** [review]
Normally https://github.com/openshift/cluster-ingress-operator should own recording rules along with the metrics.
Any reason these rules here should not live in the ingress operator repo?

**Comment by arkadeepsen** [comment]
> There are existing recording rules related to openshift-ingress in this repo itself. https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/cluster-monitoring-operator/prometheus-rule.yaml#L332-L355. Some of them are from openshift router and some from cluster ingress operator. Added the new ones here as these are also related to openshift-ingress.

As per the discussion (https://coreos.slack.com/archives/C0VMT03S5/p1665485502376879) removed the recording rules from here.

**Comment by jan--f** [comment]
/label docs-approved
/label px-approved
/label qe-approved
Adding labels for a telemetry addition.
/lgtm

**Pull request merged**
