### PR TITLE
Enable the /api/v1/series endpoint on the Thanos tenancy port

### PR DESCRIPTION
**Pull request by simonpasquier**
Follow-up of #1299

* [X] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold 
the operator e2e failure looks legit

**Comment by jan--f** [comment]
/lgtm
/label px-approved
/label docs-approved
/label qe-approved
Adding labels since this doesn't change any core functionality but rather exposes an optional feature.

**Pull request merged**
