### PR TITLE
Bug 1772564: Bring in new alert via dependency 

### PR DESCRIPTION
**Pull request by lilic**
Also cleans up telemeter deployment which we don't need anymore.

cc @openshift/openshift-team-monitoring 

FYI @p0lyn0mial

### CODE REVIEW

**Comment by lilic** [comment]
/hold 

Will bring this into master first, copy bugzilla, then we can merge this...

**Comment by sttts** [comment]
> Will bring this into master first, copy bugzilla, then we can merge this...

Is there a master PR now?

**Comment by lilic** [comment]
@sttts  Yes there is a master PR now for this https://github.com/openshift/cluster-monitoring-operator/pull/673 that will bring in the alert.

**Comment by lilic** [comment]
> failed to acquire lease: resources not found


🤷‍♀ 
/retest

**Pull request merged**
