### PR TITLE
MON-2654: Add a cluster advance feature usage metric

### PR DESCRIPTION
**Pull request by aruniiird**
Adding an advance feature usage in the cluster to telemetry.

Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by aruniiird** [comment]
Metric name is finalized: `ocs_advanced_feature_usage`
Updated and ran `make doc` command

OCS-Operator PR for reference: https://github.com/red-hat-storage/ocs-operator/pull/1772

Removing the WIP for further review

**Comment by aruniiird** [comment]
OCS-Operator PR has been approved and merged.
Need some review on this PR. @sthaha , @JoaoBraveCoding , please take a look.
Thanks

**Comment by JoaoBraveCoding** [comment]
/skip
/retest
@simonpasquier or @jan--f can you please take a look

**Comment by jan--f** [comment]
@aruniiird Can you outline what this metric would look like for a typical cluster? I had a look at your ocs-operator PR and the label names worry me a little. By your estimation how many ceph cluster/namespace combinations do you expect per cluster and how many cluster will ship this metric?

**Comment by aruniiird** [comment]
> @aruniiird Can you outline what this metric would look like for a typical cluster? I had a look at your ocs-operator PR and the label names worry me a little. By your estimation how many ceph cluster/namespace combinations do you expect per cluster and how many cluster will ship this metric?

Hi @jan--f ,
The metric-name is `ocs_advanced_feature_usage` and this is a per ceph-cluster metric.
The metric will have a value of `1.0` if the ceph cluster is using any of our advanced features like encryption or external cluster mode etc. If the cluster is NOT using any of the above said features, the metric will be set to `0.0`. It will not hold any other values.

There will be only one Ceph cluster per namespace and at present, on a default installation (through Operator Hub), we only have ONE ceph-cluster installed under `openshift-storage` namespace. Eventhough we support/allow a custom namespace ceph-cluster installation, I'm not aware of setups using a lot of different namespaces (under one single Openshift Cluster) and installing ceph-clusters in each of those namespaces. So AFAIK, there will be only one ceph-cluster/namespace combination present. Thus there will be only one metric per that combo.

**Comment by simonpasquier** [comment]
Would it make sense to sum the metric per cluster to control the cardinality?

```
# Sum of Ceph clusters using advanced features
record: cluster:ocs_advanced_feature_usage:sum
expr: sum(ocs_advanced_feature_usage)
```

**Comment by mulbc** [comment]
The added metric is `ocs_advanced_feature_usage` with two labels:
1) `ceph_cluster` <- cluster for which we check for advanced features
2) `namespace` <- namespace where the cluster is installed

The ODF product, for which this is for, only supports deploying a single ceph cluster in the `openshift-storage` namespace. Thus we expect to only ever get a single set of ceph_cluster/namespace combination for this metric per OpenShift cluster, avoiding high cardinality as much as possible.

Do you still want us to aggregate?

**Comment by jan--f** [comment]
This issue still persists since this metric will be reported for (almost) every ODF cluster. This means the number of label values is essentially unbounded. Also from your description it sounds like the `namespace` label is not needed at all.
You have two options to move ahead with this:

1. Limit the cardinality of the metric to ~10 time series or less. A time series is one distinct label value set. We can approve this without further consultation.
2. If you absolutely need the current label set, please get approval from the Observability Group leadership team. You can ping @eparis to start this process.

Ultimately budget concerns and telemetry value has to be balanced.

**Comment by mulbc** [comment]
I understand - @aruniiird - can we please remove the `ceph_cluster` and `namespace` labels, since these are not important for us.
It sounds like after that, we are good to merge this PR?

**Comment by jan--f** [comment]
> It sounds like after that, we are good to merge this PR?

Yes indeed.

**Comment by aruniiird** [comment]
I've opened an OCS-Operator PR to remove the labels: https://github.com/red-hat-storage/ocs-operator/pull/1801
Please check

**Comment by aruniiird** [comment]
> I've opened an OCS-Operator PR to remove the labels: [red-hat-storage/ocs-operator#1801](https://github.com/red-hat-storage/ocs-operator/pull/1801) Please check

OCS-Operator PR is now merged. @jan--f , @mulbc , please take a look

**Comment by aruniiird** [comment]
@jan--f , @JoaoBraveCoding , @mulbc , ready for another review.
This PR and [rhobs/configuration#302](https://github.com/rhobs/configuration/pull/302) are needed for EPIC: [RHSTOR-3173](https://issues.redhat.com/browse/RHSTOR-3173)
Please take a look

**Comment by jan--f** [comment]
/label docs-approved
/label px-approved
/label qe-approved
For a telemetry addition.

**Pull request merged**
