### PR TITLE
MON-1659: adding relatedObjects to cluster operator manifest

### PR DESCRIPTION
**Pull request by prashbnair**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by prashbnair** [comment]
/retitle MON-1659: adding relatedObjects to cluster operator manifest

**Comment by simonpasquier** [comment]
Do we still need the cluster monitoring operator to [update](https://github.com/openshift/cluster-monitoring-operator/blob/a6bc9824035ceb8dbfe7c53cf0c138bfb2ec5643/pkg/client/status_reporter.go#L49-L63) the relatedObjects field?

**Comment by prashbnair** [comment]
> Do we still need the cluster monitoring operator to update the relatedObjects field?

I dont think it is required but I see that it is being set in 2 places
1. When the operator is being setup
2. When the operator conditions are set

Do we want to remove both of them?

**Comment by simonpasquier** [comment]
After looking at what other operators are doing, it is fine to have CMO updating the `relatedObjects` field.

/lgtm

**Pull request merged**
