### PR TITLE
manifests: add cluster_installer to whitelist 

### PR DESCRIPTION
**Pull request by crawford**
This series will allow us to determine whether a cluster was created
using IPI or UPI. Once Hive and CI are updated, we'll also be able to
determine if a cluster was created by CI or if it was created by Hive.

### CODE REVIEW

**Comment by squat** [comment]
I’ll push to your branch to fix the commit if that’s alright, @crawford

**Comment by crawford** [comment]
@squat all of CI is currently blocked. I'll move this through one the issue is resolved.

**Comment by crawford** [comment]
There's a lull in the CI environment. I'm going for it.

/retest

**Pull request merged**
