### PR TITLE
Bug 2011359: Backport Application Services metric to 4.9 release

### PR DESCRIPTION
**Pull request by kenfinnigan**
Relevant request and approval can be found at:
https://docs.google.com/document/d/1o4UZ3QeRheL-xZqfYWRRtJOZ2I3uJPdZXWUfY_sy8Dc/edit?usp=sharing

Associated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2011359

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by PhilipGough — APPROVED** [review]

**Comment by simonpasquier** [comment]
@kenfinnigan it will resolve by itself once 4.9 is GA (hopefully soon).

**Comment by PhilipGough** [comment]
@kenfinnigan - timing, we just missed the cutoff unfortunately. If your BZ targets a `.z` release then it is a back port to a patch release.

Setting the target to `4.9.0` would mean you are targeting GA, but if you have missed the cutoff, that is not an appropriate target for a bug that is not a blocker, which is the scenario here, so you have got it all correct :)

**Pull request merged**
