### PR TITLE
pkg/manifests: allow to configure enforced limits on PrometheusK8sConfig

### PR DESCRIPTION
**Pull request by fgouteroux**
Hello

These limits should be available also on ClusterMonitoringConfiguration and not only for UserWorkloadConfiguration:

- enforcedLabelLimit
- enforcedLabelNameLengthLimit
- enforcedLabelValueLengthLimit
- enforcedSampleLimit
- enforcedTargetLimit

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
:wave: thanks for the PR! Can you open a JIRA ticket [here](https://issues.redhat.com/projects/OBSDA/summary) and provide more details about your use case?
Feature requests like this need to go through our product management first.

**Comment by fgouteroux** [comment]
> wave thanks for the PR! Can you open a JIRA ticket [here](https://issues.redhat.com/projects/OBSDA/summary) and provide more details about your use case? Feature requests like this need to go through our product management first.

sure, will do it.

**Comment by fgouteroux** [comment]
Hello, any chance to get this PR merged ? @simonpasquier

**Comment by fgouteroux** [comment]
Any update ?

**Comment by fgouteroux** [comment]
@raptorsun One test is failed due to Cluster operator csi-snapshot-controller. Could we move forward without this test as it is not required ?

**Comment by raptorsun** [comment]
> @raptorsun One test is failed due to Cluster operator csi-snapshot-controller. Could we move forward without this test as it is not required ?

Thanks for your PR :) 
No worries about the non-required test `e2e-aws-single-node`. 
As @simonpasquier mentioned, we need check with product manager on this new feature PR.

**Pull request closed without merging**
