### PR TITLE
Bug 1753091: Inject http_proxy vars

### PR DESCRIPTION
**Pull request by paulfantom**
Inject http_proxy variables into oauth-proxy containers as this is necessary in proxied environments.

/cc @LiliC @s-urbaniak

### CODE REVIEW

**Comment by s-urbaniak** [comment]
looking good! :+1: How about the trusted CA bundle?

**Comment by paulfantom** [comment]
> How about the trusted CA bundle?

wip :)

**Comment by paulfantom** [comment]
Tests will fail until #472 is merged as we need Volume support in CRDs first.

**Comment by paulfantom** [comment]
trustedCA support will be done in separate PR

**Pull request merged**
