### PR TITLE
Bug 1810424: jsonnet/jsonnetfile.json: Pin kubernetes-mixin to master

### PR DESCRIPTION
**Pull request by lilic**
This is so we can bring the alert the apiserver wants to 4.4 by tomorrow with https://github.com/openshift/cluster-monitoring-operator/pull/669/files as my PR to pin everything to master most likely won't be merged by today.

### CODE REVIEW

**Comment by lilic** [comment]
cc @openshift/openshift-team-monitoring

**Comment by lilic** [comment]
@sttts @p0lyn0mial do you have a bugzilla for master for https://bugzilla.redhat.com/show_bug.cgi?id=1772564 as we need that to have a bug aiming 4.5 to be in modified state.

**Comment by p0lyn0mial** [comment]
> @sttts @p0lyn0mial do you have a bugzilla for master for https://bugzilla.redhat.com/show_bug.cgi?id=1772564 as we need that to have a bug aiming 4.5 to be in modified state.

seems like Stefan have already created a BZ.

@lilic btw have you seen my comments in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/358 ?

**Comment by lilic** [comment]
@p0lyn0mial judging by your comment we need to remove it then and only introduce it when we are at 1.18, correct?
 https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/358#issuecomment-593336947

**Comment by p0lyn0mial** [comment]
@lilic  it's not an issue for Openshift `4.4` (we backported the fix `origin`).
@lilic it might be an issue for people that use `release-0.3` branch since it is bounded with is Kube `1.17`. That version doesn't have the fix and the alert will likey fire for them.

**Comment by lilic** [comment]
Had to rebase @s-urbaniak PTAL thanks

**Comment by lilic** [comment]
flakes:
> Mar  6 08:13:13.325: INFO: At 2020-03-06 07:58:41 +0000 UTC - event for redhat-operators-b68f7559-57fx6: {kubelet ip-10-0-150-156.us-west-2.compute.internal} Unhealthy: Readiness probe failed: command timed out
Mar  6 08:13:13.325: INFO: At 2020-03-06 07:58:41 +0000 UTC - event for redhat-operators-b68f7559-57fx6: {kubelet ip-10-0-150-156.us-west-2.compute.internal} Unhealthy: Liveness probe failed: command timed out

/retest

**Comment by lilic** [comment]
/retest

flakes :(

**Comment by lilic** [comment]
There is an outage it seems with the test platform, so this and in turn the 4.4 PR is blocked until that is resolved. I already asked @s-urbaniak to bring this up with someone to make sure it ends up in 4.4 as it was out of our control.

**Comment by lilic** [comment]
/retest

now CI should be fixed

**Comment by lilic** [comment]
meh KubeletPodStartUpLatencyHigh is very low and its failing, will fix it in the mixin and update the PR.

**Comment by lilic** [comment]
Alert that was causing the test to fail was adjusted upstream.

**Pull request merged**
