### PR TITLE
Add scrapeInterval to operator configurables.

### PR DESCRIPTION
**Pull request by bostrt**

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@bostrt thanks for the contribution! we should be careful about adding a scrape interval as this affects SLA expectations of the cluster observability stack. If the user configures i.e. 5 days of scrape intervals we can give no guarantees about the cluster health.

Nevertheless, please file an RFE in jira (cc @sichvoge) so we can evaluate this deeper and plan accordingly.

**Comment by bostrt** [comment]
I've filed https://jira.coreos.com/browse/RFE-347 and will update there with user justification for the RFE.

**Comment by paulfantom** [comment]
Closing this as RFE was rejected.

/close

**Pull request closed without merging**
