### PR TITLE
jsonnet: remove duplicate alertmanager down alert

### PR DESCRIPTION
**Pull request by squat**
This PR bumps the kube-prometheus jsonnet dep to remove the duplicat AlertmanagerDown alert and regenerates assets.

cc @sichvoge @brancz 

targeted for 3.11.z

### CODE REVIEW

**Comment by squat** [comment]
Hold until 3.11 release is out.

**Comment by squat** [comment]
@mxinden @metalmatze as discussed OOB regarding https://github.com/openshift/cluster-monitoring-operator/pull/117, it is not possible to apply this patch to remove the one duplicate AlertmanagerDown alert without bumping all of kube-prometheus. If we really want this patch in 3.11.z, then it may mean we have to bump it entirely

**Comment by mxinden** [comment]
I would vote for not including this patch in Openshift 3.11, what are your thoughts @metalmatze @squat?

**Comment by metalmatze** [comment]
As it only removes a duplicate I don't either see a reason to patch this.

**Comment by squat** [comment]
Good. It sounds like we all agree that this should not be applied to 3.11.z, since applying the patch produces too large of a footprint.

**Pull request closed without merging**
