### PR TITLE
OCPBUGS-12488: go.mod: update golang.org/x/net to v0.7.0

### PR DESCRIPTION
**Pull request by machine424**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by machine424** [comment]
It's normal that `ci/prow/versions` fails as we don't systematically upgrade components on z versions, I'll create a ticket to improve it.

**Comment by simonpasquier** [comment]
> I'll create a ticket to improve it.

I've just closed a ticket yesterday about it that I filed a while ago. The `versions` job is only informing and I'm not sure that we have time to "fix" the glitch...

**Comment by danielmellado** [comment]
Should we just disable it once we cut a branch then? Either that or just ignoring it for z releases.

**Review by marioferh — COMMENTED** [review]
/lgtm

**Pull request merged**
