### PR TITLE
Bug 1800513: assets,jsonnet,pkg: Fix generate check

### PR DESCRIPTION
**Pull request by LiliC**
We seem to have not run jb update and make generate-in-docker, this was due to lack of the generate job. This should fix it. ™️ 

cc @openshift/openshift-team-monitoring 

FYI @smarterclayton this should fix your PR, I checked by updating the file and running make generate-in-docker manually and it worked fine after this change.

### CODE REVIEW

**Comment by LiliC** [comment]
FYI @pgier the bugfix of prom-operator is in here as well.

**Comment by LiliC** [comment]
/bugzilla refresh

I dislike bugzilla so much 🙄

**Comment by smarterclayton** [comment]
Overriding approvals, blocks other fixes.

**Pull request merged**
