### PR TITLE
Merge v0.0.2 into release-0.0 release branch

### PR DESCRIPTION
**Pull request by mxinden**
@ironcladlou I would wait for your "ok" here, in regards to the e2e tests or a quick manual check.

### CODE REVIEW

**Comment by brancz** [comment]
I think you meant v0.0.2?

**Comment by mxinden** [comment]
> I think you meant v0.0.2?

@brancz right, thanks, updated.

**Comment by ironcladlou** [comment]
I've been bouncing back and forth between this and another higher priority issue, so haven't got a test run yet.

**Comment by mxinden** [comment]
The Rule CRD feauture is merged into the Prometheus Operator master branch,
but is not yet released. We are still missing a migration path between old
configmaps and the new CRDs, as well as improved documentation.

**Comment by ironcladlou** [comment]
I think we need to bring in https://github.com/openshift/cluster-monitoring-operator/pull/19, because without the prometheus-config-reloader version bump master is broken by default.

**Comment by ironcladlou** [comment]
Just did a manual test of this, looks good

**Comment by ironcladlou** [comment]
Found one more we'll want to go ahead and bring in.

https://github.com/openshift/cluster-monitoring-operator/pull/20

**Comment by ironcladlou** [comment]
Not sure how you want to handle the version cut commit since I dragged in more changes, but this is ready to go.

**Pull request merged**
