### PR TITLE
Bug 1821666: thanos ruler secret cleanup

### PR DESCRIPTION
**Pull request by pgier**
Fix cleanup of thanos rule grpc tls secret.

### CODE REVIEW

**Comment by pgier** [comment]
@lilic PTAL, the previous PR (#762) was failing to clean up one of the secrets, this seems to fix it in my local testing.

**Comment by s-urbaniak** [comment]
lgtm module the rebase.

**Comment by lilic** [comment]
While you need to rebase anyways do you mind doing us a favour, in the Makefile we forgot to pin the jsonnet-ci release:
In here https://github.com/openshift/cluster-monitoring-operator/blob/master/Makefile#L30 in do you mind adding `quay.io/coreos/jsonnet-ci:release-0.38` the version. To avoid needing a bugzilla for master PR, as that is purely for local development anyways. Thanks!

See PR for background: https://github.com/openshift/release/pull/8118/files

**Comment by pgier** [comment]
@lilic done, PTAL

**Pull request merged**
