### PR TITLE
MON-2065: jsonnet: exclude `kubernetes-storage` rules

### PR DESCRIPTION
**Pull request by jan--f**
These alert rules are now hosted in the cluster-storage-operator. See https://github.com/openshift/cluster-storage-operator/pull/477.

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by duanwei33** [comment]
Storage QE tested https://github.com/openshift/cluster-storage-operator/pull/477, see
https://github.com/openshift/cluster-storage-operator/pull/477#issuecomment-2219620402.
Just FYI

**Review by marioferh — COMMENTED** [review]
/lgtm

**Pull request merged**
