### PR TITLE
Bug 2019992: Bump jsonnet dependencies to latest

### PR DESCRIPTION
**Pull request by arajkumar**
This PR bumps jsonnet dependencies to latest which also fixes Bug 2013920 and Bug 2019992.

Removal of kube-proxy alerts shall be found in https://github.com/openshift/cluster-monitoring-operator/pull/1444/files#r732821044

Alertmanager SM has been renamed from alertmanager to alertmanager-main.

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by arajkumar** [comment]
It started failing after https://github.com/openshift/telemeter/pull/398 and should have been fixed after https://github.com/openshift/cluster-monitoring-operator/pull/1451.

**Review by PhilipGough — APPROVED** [review]
/lgtm on green

**Comment by simonpasquier** [comment]
[e2e-agnostic-operator](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/1455/pull-ci-openshift-cluster-monitoring-operator-master-e2e-agnostic-operator/1457580719168557056) fails because the Alertmanager service monitor has been renamed from `alertmanager` to `alertmanage-main`. If we want to carry the upstream change (which makes sense IMHO), the e2e test needs to be updated and the cluster monitoring operator's task deploying Alertmanager should take care of removing the old service monitor.

**Comment by simonpasquier** [comment]
For the record, it also fixes https://bugzilla.redhat.com/show_bug.cgi?id=2019992

**Comment by arajkumar** [comment]
> [e2e-agnostic-operator](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/1455/pull-ci-openshift-cluster-monitoring-operator-master-e2e-agnostic-operator/1457580719168557056) fails because the Alertmanager service monitor has been renamed from `alertmanager` to `alertmanage-main`. If we want to carry the upstream change (which makes sense IMHO), the e2e test needs to be updated and the cluster monitoring operator's task deploying Alertmanager should take care of removing the old service monitor.

Thanks @simonpasquier. This PR is becoming bigger day by day :) Let me fix this.

**Comment by arajkumar** [comment]
/retitle Bug 2019992: Bump jsonnet dependencies to latest

**Comment by juzhao** [comment]
the result for "instance:node_memory_utilisation:ratio" is correct in grafana page, it shows a percentage used and not a very large negative number, see https://bugzilla.redhat.com/show_bug.cgi?id=2019992#c2
/lgtm

**Pull request merged**
