### PR TITLE
Bug 1799541: Node exporter init collectors must be privileged

### PR DESCRIPTION
**Pull request by smarterclayton**
dmidecode (used by the VM type detection) requires access to
/dev/mem which requires privileged. Only the init container gets
that permission. Blocks being able to read physical machine BIOS
info.

### CODE REVIEW

**Comment by lilic** [comment]
> I0312 13:04:23.971552       1 tasks.go:46] ran task 4 of 11: Updating Prometheus-k8s
W0312 13:05:54.582599       1 reflector.go:302] github.com/openshift/cluster-monitoring-operator/pkg/operator/operator.go:172: watch of *v1.ConfigMap ended with: too old resource version: 18501 (19807)
I0312 13:05:55.582869       1 reflector.go:160] Listing and watching *v1.ConfigMap from github.com/openshift/cluster-monitoring-operator/pkg/operator/operator.go:172
I0312 13:08:31.151582       1 operator.go:201] ConfigMap to configure stack does not exist. Reconciling with default config every 5 minutes.
I0312 13:09:01.566506       1 tasks.go:46] ran task 6 of 11: Updating node-exporter
I0312 13:09:01.566549       1 operator.go:321] Updating ClusterOperator status to failed. Err: running task Updating node-exporter failed: reconciling node-exporter DaemonSet failed: updating DaemonSet object failed: waiting for DaemonSetRollout of node-exporter: daemonset node-exporter is not ready. status: (desired: 0, updated: 0, ready: 0, unavailable: 0)
E0312 13:09:01.581334       1 operator.go:267] Syncing "openshift-monitoring/cluster-monitoring-config" failed
E0312 13:09:01.581367       1 operator.go:268] sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating node-exporter failed: reconciling node-exporter DaemonSet failed: updating DaemonSet object failed: waiting for DaemonSetRollout of node-exporter: daemonset node-exporter is not ready. status: (desired: 0, updated: 0, ready: 0, unavailable: 0)

Seems like valid failure 🤔

**Comment by smarterclayton** [comment]
/close

I think we can skip this now.

**Pull request closed without merging**
