### PR TITLE
Bug 2021097: Set Upgradeable: false when HA workloads are incorrectly spread

### PR DESCRIPTION
**Pull request by jan--f**
… spread (#1431)

* Merge pull request #1330 from dgrisonnet/ha-upgradeable

Bug 1995924: Set `Upgradeable: false` when HA workloads are incorrectly spread

* pkg/rebalancer: sort resources for deletion

The resources that are marked for deletion are sorted by their PVC
creation timestamp, from the newest to the oldest to make the deletion
consistent.

Signed-off-by: Damien Grisonnet <dgrisonn@redhat.com>

* pkg: improve rebalancer logging

Signed-off-by: Damien Grisonnet <dgrisonn@redhat.com>

* pkg/rebalancer: sort based on pod names

Sort PVCs by their creation timestamps, from the newest to the oldest to
make sure that the oldest PVC is retained in case all of them are
annotated. If some PVCs have the same creation timestamp, they will be
sorted based on their pod name.

Signed-off-by: Damien Grisonnet <dgrisonn@redhat.com>

* pkg/rebalancer: split annotation removal

Add EnsurePVCsAreNotAnnoted function that makes sure that none of the
PVCs of the given workload have the
openshift.io/cluster-monitoring-drop-pvc annotation after the
rebalancing is done. In case one of the PVC has the annotation, it will
be removed to prevent deleting the PVC in a future cycle.

Signed-off-by: Damien Grisonnet <dgrisonn@redhat.com>

* pkg/rebalancer: sort resources to delete by age

Signed-off-by: Damien Grisonnet <dgrisonn@redhat.com>

* test/e2e: fix framework

Signed-off-by: Damien Grisonnet <dgrisonn@redhat.com>

Co-authored-by: OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
(cherry picked from commit 8500e0f812d34643a5e7c33cee763d4b00a171b2)

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by jan--f** [comment]
/hold
Investigating a CI issue with the master PR and still resolving backport issues.

**Comment by jan--f** [comment]
/unhold
I think this is ready to review and merge.

**Comment by simonpasquier** [comment]
I'll add this at the top of my review list :)

**Comment by juzhao** [comment]
tested with PR, bound PVs for prometheus, and schedule prometheus pods to one same node, Upgradeable is False now
/lgtm

**Pull request merged**
