### PR TITLE
MON-2567: enable AlertmanagerConfig v1beta1

### PR DESCRIPTION
**Pull request by simonpasquier**
https://issues.redhat.com/browse/MON-2567

* [X] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by raptorsun — APPROVED** [review]
/lgtm

**Comment by simonpasquier** [comment]
@Senthamilarasu-STA for PX approval
@juzhao @lihongyan1 for QE approval

**Comment by juzhao** [comment]
tested with PR, version is v1beta1 now
```
# oc explain AlertmanagerConfig
KIND:     AlertmanagerConfig
VERSION:  monitoring.coreos.com/v1beta1
```
create AlertmanagerConfig with v1alpha1, can create the AlertmanagerConfig and apiVersion is changed to v1beta1 automatically.  create AlertmanagerConfig with v1beta1, it is the same behavior with v1alpha1 version

**Comment by juzhao** [comment]
find a bug with AlertmanagerConfig v1beta1, maybe related to prometheus operator
https://bugzilla.redhat.com/show_bug.cgi?id=2097716

**Pull request merged**
