### PR TITLE
Bug 1858010: Backport fix for KubePodCrashLooping alert

### PR DESCRIPTION
**Pull request by paulfantom**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by paulfantom** [comment]
/hold

needs https://github.com/openshift/cluster-monitoring-operator/pull/945 for CI to work correctly.

**Comment by s-urbaniak** [comment]
@paulfantom #945 is merged, i guess we can move forward here :+1:

**Comment by paulfantom** [comment]
Rebased to include #945

**Comment by juzhao** [comment]
launch cluster with cluster-bot with the PR `launch openshift/cluster-monitoring-operator#952 gcp`
issue is fixed
```
alert: KubePodCrashLooping
expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",namespace=~"(openshift-.*|kube-.*|default|logging)"}[5m])
  * 60 * 5 > 0
for: 15m
labels:
  severity: warning
annotations:
  message: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }})
    is restarting {{ printf "%.2f" $value }} times / 5 minutes.
```

**Pull request merged**
