### PR TITLE
Bug 1974830: Update KubeDeploymentReplicasMismatch alert

### PR DESCRIPTION
**Pull request by PhilipGough**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by PhilipGough** [comment]
@simonpasquier, would you mind taking a look? I added unit tests to cover all cases and also had a successful run from `test upgrade 4.8.0-rc.2  openshift/cluster-monitoring-operator#1261`: see https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1410993213489025024

**Review by simonpasquier — COMMENTED** [review]
/lgtm
:crossed_fingers:

**Pull request merged**
