### PR TITLE
Bug 1773246: Bump telemeter to get whitelist changes for virt_platform

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
/assign @pgier 
@bparees this is required for this release (same as the other two, we had to bump the vendor after the other merge)

**Comment by bparees** [comment]
/lgtm

@knobunc not sure if you did your final patch manager pass already, can you approve this one?

**Comment by bparees** [comment]
> (same as the other two, we had to bump the vendor after the other merge)

@smarterclayton what other two?

**Comment by smarterclayton** [comment]
The other two under 1773246 for release-4.2 that merged today.

**Pull request merged**
