### PR TITLE
Bug 1945500: Bump thanos version to v0.20.2

### PR DESCRIPTION
**Pull request by arajkumar**
The following PR bumps thanos to v0.20.2

https://github.com/openshift/thanos/pull/58

Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by arajkumar** [comment]
/hold

This PR is blocked by https://github.com/openshift/thanos/pull/58.

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Pull request merged**
