### PR TITLE
Adjust priority class of core platform prometheus

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Reviving https://github.com/openshift/cluster-monitoring-operator/pull/1060

We can look into this after https://github.com/openshift/kubernetes/pull/575

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by lilic** [comment]
Nice! Thank you! Ping when the other PR is merged 🎉

**Comment by s-urbaniak** [comment]
/hold
as this relies on api changes.

**Comment by ravisantoshgudimetla** [comment]
/close

As this has been already handled

**Pull request closed without merging**
