### PR TITLE
OCPBUGS-25389: Add RHACM telemetry metric for 4.12

### PR DESCRIPTION
**Pull request by zlayne**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/retitle OCPBUGS-25389: Add RHACM telemetry metric for 4.12

**Comment by zlayne** [comment]
@simonpasquier PR & bug are up to date. Can you please review and add `cherry-pick-approved` label.

**Pull request merged**
