### PR TITLE
Enable honor timestamps overriding for user workload

### PR DESCRIPTION
**Pull request by paulfantom**
With this option prometheus-operator handling user workload monitoring will configure prometheuses to disallow honoring timestamps in each scrape config.

/cc @s-urbaniak

### CODE REVIEW

**Comment by LiliC** [comment]
This is blocked on https://github.com/openshift/prometheus-operator/pull/43

**Comment by LiliC** [comment]
PR has been merged https://github.com/openshift/prometheus-operator/pull/44#issuecomment-545027408

Not sure if this is already part of the payload or not?

I am guessing the CI is not failing because we do not have e2e tests for this cc @s-urbaniak?

**Comment by paulfantom** [comment]
prometheus-operator from https://github.com/openshift/prometheus-operator/pull/44 should be now a part of payload. 

/hold cancel

**Comment by LiliC** [comment]
/hold

This will not work yet. Working on fix to update Prometheus CRD.

**Comment by LiliC** [comment]
/hold cancel 

this should be possible to be merged now, that the deps are updated.

**Pull request merged**
