### PR TITLE
Duplicate Grafana configmaps from monitoring to console

### PR DESCRIPTION
**Pull request by paulfantom**
- Configmaps are deployed by CVO (dumped in `manifests/` directory)
- Every configmap from `manifests/` is using `openshift-config-managed` and has `console.openshift.io/dashboard=true` label added

I think there was some change in `jb` and it regenerated `jsonnet/jsonnetfile.*` files, which I am attaching here in a separate commit. There are changes in ordering and sum outputs.

/cc @kyoto @s-urbaniak

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@paulfantom e2e says something:
```
level=fatal msg="failed to initialize the cluster: Could not update configmaplist \"0000_90_cluster_monitoring_operator_01-dashboards.yaml\" (515 of 574)"
```

ptal, might be a legit failure :thinking:

**Comment by paulfantom** [comment]
Turns out CVO won't accept `ConfigMapList`, but it accept an invalid yaml with a "list" of ConfigMaps created by magic bash one-liner at https://github.com/openshift/cluster-monitoring-operator/pull/635/files#diff-c92e0d4cd5002a9ca161eb6d594f5987R42

I don't see any other way apart from deploying dashboards via CMO and not CVO.

**Pull request merged**
