### PR TITLE
Bug 1912430: [Backport 4.6] Set resources to the native spec field

### PR DESCRIPTION
**Pull request by lilic**
Backport of https://github.com/openshift/cluster-monitoring-operator/pull/1023. 

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

cc @openshift/openshift-team-monitoring PTAL thanks!

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by juzhao** [comment]
tested with the PR, issue is fixed
/lgtm

**Pull request merged**
