### PR TITLE
MON-3380: adjust prometheus-k8s service openshift.io/description

### PR DESCRIPTION
**Pull request by machine424**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by machine424** [comment]
cc @simonpasquier

**Review by simonpasquier — APPROVED** [review]
Thanks for spotting this!

**Comment by simonpasquier** [comment]
/retitle MON-3380: adjust prometheus-k8s service openshift.io/description

**Pull request merged**
