### PR TITLE
[release-4.14] OCPBUGS-34023: fix KRP permissions for Thanos Querier

### PR DESCRIPTION
**Pull request by rexagod**
fix KRP configuration for thanos-querier in order to enforce restricted access only to entities allowed to [http-verb] for pods.metrics.k8s.io

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by rexagod** [comment]
Surfaced in build [`4.14.28`](https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.14.28) originally.

**Pull request merged**
