### PR TITLE
[release-4.9] Bug 2038406: Add custom profile metric for Node Tuning Operator to telemetry

### PR DESCRIPTION
**Pull request by dagrayvid**
To help prioritize future plans for NTO, we want to better understand how it is being used. One way we can do this is by sending metrics through telemetry to see how often NTO is being used to manage custom TuneD profiles on nodes. This is available on 4.10 but not older versions

Signed-off-by: David Gray <dagray@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by dagrayvid** [comment]
@juzhao could you please add the cherry-pick-approved label if this change looks okay to you?

**Comment by dagrayvid** [comment]
Ping. Assuming this PR looks okay, please add the cherry-pick-approved label needed for merging. Thanks.

/cc  @juzhao @lihongyan1 @wzheng1

**Pull request merged**
