### PR TITLE
Bug 1929278: [4.7]: jsonnet/prometheus.jsonnet: Apply openshift-user-critical class to cluster Prometheus 

### PR DESCRIPTION
**Pull request by lilic**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by lilic** [comment]
/retest

🤷‍♀️

**Comment by s-urbaniak** [comment]
the recent test failure is a flake. the creation of the example app namespace failed:
```
    user_workload_monitoring_test.go:373: Post "https://api.ci-op-hmsqmfyh-0330d.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces": dial tcp 52.55.159.103:6443: connect: connection refused
```
https://github.com/openshift/cluster-monitoring-operator/blob/5f45259e887e6a9454bea52e247b389711641ed5/test/e2e/user_workload_monitoring_test.go#[

**Comment by lilic** [comment]
Upgrade tests passed -> https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1362053382700797952

**Comment by simonpasquier** [comment]
/hold cancel

I tested this PR on a cluster with 3 x 8GB worker nodes. I generated fake series to increase Prometheus memory usage and eventually the Prometheus pods got OOM-killed because they put memory pressure on the node. Meanwhile all worker nodes remained available.

My understanding is that the `e2e-agnostic-operator ` job failures are flakes unrelated to this change (the tests don't retry on 5xx responses or on network blips).

image

image

**Comment by lilic** [comment]
Thanks Simon, we had a call and I looked at the results and agree could see the OOM kill.

**Comment by simonpasquier** [comment]
Also from the worker journal logs, we can see that prometheus got an oom score of -997.

```
Feb 17 17:31:29.921848 ip-10-0-140-75 kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=crio-7dcef32630af0c3b6e68c081bba5d5550096b1ed830373ed36e7f8cdea85d439.scope,mems_allowed=0,oom_memcg=/kubepods.slice,task_memcg=/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2b8bb6dc_1260_4705_9756_73d16e1a8e50.slice/crio-9fdfefd3d6ab1c6c510a4d3ff988011fcb01f0e819c64ec3a95c7a72daa75a35.scope,task=prometheus,pid=321919,uid=65534
Feb 17 17:31:29.921904 ip-10-0-140-75 kernel: Memory cgroup out of memory: Killed process 321919 (prometheus) total-vm:7137916kB, anon-rss:5890416kB, file-rss:14912kB, shmem-rss:0kB, UID:65534
Feb 17 17:31:29.922014 ip-10-0-140-75 hyperkube[1441]: I0217 17:31:29.863731    1441 oom_watcher_linux.go:76] Got sys oom event: &{321919 prometheus 2021-02-17 17:31:29.876503113 +0000 UTC m=+30428.478171430 / / }
Feb 17 17:31:30.322060 ip-10-0-140-75 kernel: machine-config- invoked oom-killer: gfp_mask=0x600040(GFP_NOFS), order=0, oom_score_adj=-997
```

**Comment by lilic** [comment]
/retest

Different failure, but nothing related to tests.

**Pull request merged**
