### PR TITLE
build: various fixes for the makefile

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
From [ci/prow/vendor](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/372/pull-ci-openshift-cluster-monitoring-operator-master-vendor/19):

```
go mod tidy
go: modules disabled inside GOPATH/src by GO111MODULE=auto; see 'go help modules'
make: *** [vendor] Error 1
```

I'm guessing that job wasn't actually verifying anything before this change.

**Comment by paulfantom** [comment]
It is verifying, but only in CI where it runs as `GO111MODULE=off make vendor`. This should be fixed also in Makefile.

/lgtm

**Comment by paulfantom** [comment]
hold until https://github.com/openshift/cluster-monitoring-operator/pull/374 is merged
/hold

**Comment by brancz** [comment]
With #374 merged, this needs a rebase then it should be ready to go.

**Comment by crawford** [comment]
@squat looks like that LGTM was lost. Can you do that again?

**Pull request merged**
