### PR TITLE
Bug 1887354: Backport fix checking if ClusterRoleBindings need update

### PR DESCRIPTION
**Pull request by paulfantom**
Backporting following PRs:
- https://github.com/openshift/cluster-monitoring-operator/pull/932 (was merged in 4.6)
- https://github.com/openshift/cluster-monitoring-operator/pull/942 (was merged post-4.6 and backport to 4.6 is in https://github.com/openshift/cluster-monitoring-operator/pull/955)

Those two should be considered as one fix.

~This is not a clean backport due to changed client-go post-4.5 which added the necessity of passing `context` to Get/Create/...~

### CODE REVIEW

**Comment by paulfantom** [comment]
This has to be based on top of https://github.com/openshift/cluster-monitoring-operator/pull/945. Putting this on hold until dependency PR is merged.

/hold

**Comment by s-urbaniak** [comment]
@paulfantom #945 seems to be merged :+1:

**Comment by paulfantom** [comment]
rebased

**Comment by s-urbaniak** [comment]
@paulfantom where you able to verify this in a running 4.5 cluster?

**Comment by s-urbaniak** [comment]
as discussed oob the verification was done in 4.6.

**Comment by bparees** [comment]
https://github.com/openshift/cluster-monitoring-operator/pull/955 is not merged so i don't understand how this was verified on 4.6 already.

**Comment by bparees** [comment]
(as such i am holding off tagging it until we have a clear indication of how these changes were vetted in master/4.6 before backporting them)

**Comment by s-urbaniak** [comment]
@paulfantom ping, can you please elaborate? I believe indeed that the bug was not fully verified in 4.6, hence I am not sure why this is supposed to land in 4.5. I believe we need to land #955 and verify it first before we can proceed here.

**Comment by sdodson** [comment]
/bugzilla refresh
I've added the bug from #955 to the dependencies of the bug this PR is tied to, I expect this to transition to bugzilla/invalid-bug

**Comment by s-urbaniak** [comment]
@sdodson indeed, yes, i think it is reasonable to verify #955 first :+1:

**Comment by paulfantom** [comment]
For completion, verification of #955 in 4.6 was done by starting a 4.6 cluster from that PR and working on that.

**Pull request merged**
