### PR TITLE
Bug 1918202: jsonnet: remove Ceph block devices in rules

### PR DESCRIPTION
**Pull request by dgrisonnet**
Backport of https://github.com/openshift/cluster-monitoring-operator/commit/7bcd7270fa817e51d4412c95564640abc9bb14a4 to release-4.6.

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by juzhao** [comment]
tested with the not merged PR, rbd device is removed
/lgtm

**Comment by s-urbaniak** [comment]
@dgrisonnet this needs a rebase i guess

**Comment by dgrisonnet** [comment]
@s-urbaniak thank you for the heads-up :)

**Pull request merged**
