### PR TITLE
Bug 1845444: KubeApiLatency alert firing even though not all conditions are matched

### PR DESCRIPTION
**Pull request by RiRa12621**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
@RiRa12621 you need a rebase (sorry).

**Comment by RiRa12621** [comment]
/hold
i screwed up with git 
hold until i fixed

**Comment by RiRa12621** [comment]
can  i get an other review here please @simonpasquier ?

**Pull request merged**
