### PR TITLE
Bug ????: improve CMO reconciliation alert

### PR DESCRIPTION
**Pull request by paulfantom**
Make alert name more descriptive and improve alert message. Additionally
extend `for` clause to 30m to give some time for CMO to recover.

`sum()` is removed as we only have one metric.

This is based on incident which happened in our CI cluster on 24.10.2019 at around 19:00 UTC

@stevekuznetsov this still needs BZ to be backported :)

/cc @LiliC @s-urbaniak @stevekuznetsov

### CODE REVIEW

**Comment by paulfantom** [comment]
Should we also degrade this alert severity to `warning` instead of `critical`?

**Comment by s-urbaniak** [comment]
let's get also some pair of eyes from @brancz

**Comment by brancz** [comment]
Critical severity seems a little extreme, we don't know that anything is actually not working because of it, I think we should lower it to warning. Extending the for sounds good, most likely if this alert fires it's a constant situation anyways.

**Comment by paulfantom** [comment]
> For 3.11 don't think we need it, we can merge things ourselves.

Yes, we can merge it, but will this be then included in release when there is no errata?

---

degraded severity to `warning`

**Pull request merged**
