### PR TITLE
jsonnet/jsonnetfile.lock.json: Update dependencies 

### PR DESCRIPTION
**Pull request by LiliC**
This brings in dropping of deprecated k8s metrics.

cc @brancz @s-urbaniak

### CODE REVIEW

**Comment by LiliC** [comment]
Just to verify all is good, launching a cluster :)

**Comment by LiliC** [comment]
cc @rafael-azevedo made adjustments to the SRE rules, as those metrics are being removed.

**Comment by LiliC** [comment]
/hold cancel 

verified all good from our side

cc @brancz PTAL

**Comment by LiliC** [comment]
/hold

meh, found a problem

**Comment by LiliC** [comment]
@brancz PTAL thanks

**Comment by brancz** [comment]
Let's also launch a cluster after this merge and verify that there are no deprecated metrics left that we are collecting.

**Pull request merged**
