### PR TITLE
pkg/operator: reduce duplication in CSR controllers

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

cc @marioferh I remember that we discussed this particular point during one of our meetings. It's probably worthwhile linking to the cluster-policy-controller code for the future.

### CODE REVIEW

**Review by marioferh — APPROVED** [review]
Good simplification. Thanks!

**Comment by jan--f** [comment]
/lgtm
/label docs-approved
/label px-approved
/label qe-approved
Adding labels for code cleanup.

**Pull request merged**
