### PR TITLE
Bug 1751706: Removing KubeVersionMismatch alert

### PR DESCRIPTION
**Pull request by paulfantom**
Result of discussion from https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/289

/cc @brancz @s-urbaniak @mfojtik @deads2k

### CODE REVIEW

**Comment by s-urbaniak** [comment]
let's just verify by @deads2k and @mfojtik that this is the wanted way to go.
/hold

**Comment by LiliC** [comment]
Judging by this bugzilla they want that. :) https://bugzilla.redhat.com/show_bug.cgi?id=1751706

**Comment by mfojtik** [comment]
Yes, this alert does not have much sense as having different levels of Kubernetes components running is supported scenario.

**Pull request merged**
