### PR TITLE
rename rhel dockerfile to follow current standard

### PR DESCRIPTION
**Pull request by pgier**

### CODE REVIEW

**Comment by s-urbaniak** [comment]
(I was distracted by the green ci/prow/rhel-images, but it says "Context retired without replacement.") I'll retry ...

**Comment by brancz** [comment]
We were instructed to get explicit approval for Dockerfile changes. So pinging @smarterclayton for approval here.

**Comment by smarterclayton** [comment]
We can delete this - at this point it’s unused.  Most people are going to get their rhel dockerfile deleted soon.

**Comment by s-urbaniak** [comment]
closing this out as per comments

**Pull request closed without merging**
