### PR TITLE
Add toleration

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
If we have a blanket toleration(`operator: Exists`), we don't need other tolerations.

Please feel free to close this PR, if you think, you just need to tolerate the current taint(s) you have.

/cc @sjenning @derekwaynecarr

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
@s-urbaniak - Can you lgtm this PR?

**Comment by s-urbaniak** [comment]
@ravisantoshgudimetla done, thanks for this fix! :+1:

**Pull request merged**
