### PR TITLE
Revert "OCPBUGS-3331: Pin Jsonnet Deps + Update go.mod for 4.12"

### PR DESCRIPTION
**Pull request by simonpasquier**
Reverts openshift/cluster-monitoring-operator#1814

The updated definition of the KubePodNotReady alerting rule breaks the CI as explained in https://issues.redhat.com//browse/OCPBUGS-1994.
To unrevert this revert, we'd need to incorporate the change in https://github.com/openshift/cluster-monitoring-operator/pull/1792 that keeps the previous alert definition.

### CODE REVIEW

**Comment by raptorsun** [comment]
Shall we merge [this PR patching the alert KubePodNotReady](https://github.com/openshift/cluster-monitoring-operator/pull/1792) instead? 
It restores the alert to the old definition.

**Comment by dgoodwin** [comment]
> Shall we merge [this PR patching the alert KubePodNotReady](https://github.com/openshift/cluster-monitoring-operator/pull/1792) instead? It restores the alert to the old definition.

A common and fair question, but with the goal of keeping nightlies stable, we've established widely agreed precedent throughout the org to favor reverts as they take us back to a known good state, whereas attempted fixes have a higher risk and we know from painful experience often don't work first try and then burn more time with payloads blocked. While the suggested PR is almost surely fine, we can be all but certain this revert is. 

We should merge this one and then for a followup PR you can unrevert this revert, layer in the new commit with the fix, and we can easily prove that works with /payload command and merge in when ready, without the pressure of a rush to get payloads back online.

**Comment by raptorsun** [comment]
> > Shall we merge [this PR patching the alert KubePodNotReady](https://github.com/openshift/cluster-monitoring-operator/pull/1792) instead? It restores the alert to the old definition.
> 
> A common and fair question, but with the goal of keeping nightlies stable, we've established widely agreed precedent throughout the org to favor reverts as they take us back to a known good state, whereas attempted fixes have a higher risk and we know from painful experience often don't work first try and then burn more time with payloads blocked. While the suggested PR is almost surely fine, we can be all but certain this revert is.
> 
> We should merge this one and then for a followup PR you can unrevert this revert, layer in the new commit with the fix, and we can easily prove that works with /payload command and merge in when ready, without the pressure of a rush to get payloads back online.

OK. After merging this revert, we will merge the patch to the alert KubePodNotReady and then re-apply the content of PR#1792.

**Pull request merged**
