### PR TITLE
OWNERS: Add myself, and move former team members to emeritus

### PR DESCRIPTION
**Pull request by juanrh**
OWNERS: Add myself, and move former team members to emeritus

Signed-off-by: Juan Rodriguez Hortala <juanrh@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by juanrh** [comment]
@simonpasquier

**Review by simonpasquier — COMMENTED** [review]
/lgtm
/label qe-approved
/label px-approved
/label docs-approved

Administrative change only.

**Review by slashpai — APPROVED** [review]

**Pull request merged**
