### PR TITLE
MON-3839: test: add skip tests for prometheus adapter tests

### PR DESCRIPTION
**Pull request by slashpai**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by slashpai** [comment]
ok I need to remove prometheus-adapter from metrics map when feature gate is enabled

```
prometheus_test.go:53: context deadline exceeded: error getting first value from response body "{\"status\":\"success\",\"data\":{\"resultType\":\"vector\",\"result\":[],\"analysis\":{}}}\n" for query "count(up{service=\"prometheus-adapter\",namespace=\"openshift-monitoring\"} == 1)": expected body to contain single timeseries but got 0
--- FAIL: TestPrometheusMetrics (645.17s)
    --- PASS: TestPrometheusMetrics/metrics-server (5.01s)
    --- FAIL: TestPrometheusMetrics/prometheus-adapter (600.02s)
```

**Comment by jan--f** [comment]
Ahh right, `WaitForQueryReturn` can't deal with no result.

**Comment by slashpai** [comment]
@jan--f please review again updated

**Pull request merged**
