### PR TITLE
Bug 1952032: jsonnet: add format changes made by make jsonnet-fmt

### PR DESCRIPTION
**Pull request by jan--f**
This is partly preparation of the upcomming jsonnet-fmt ci job, partly
just maintanence.

Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by jan--f** [comment]
/title  Bug 1952032 jsonnet: add format changes made by make jsonnet-fmt

**Comment by jan--f** [comment]
/retitle Bug 1952032 jsonnet: add format changes made by make jsonnet-fmt

**Comment by paulfantom** [comment]
/retitle Bug 1952032: jsonnet: add format changes made by make jsonnet-fmt
/bugzilla refresh

**Pull request merged**
