### PR TITLE
Bug 1846707: changing KubeQuotaExceeded to KubeQuotaFullyUsed

### PR DESCRIPTION
**Pull request by RiRa12621**
* [x] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by lilic** [comment]
Our tests are very flaky at the moment, so bear that in mind. :)

**Comment by RiRa12621** [comment]
The first couple of failures were on me @lilic  ;)
or rather my git stash

**Pull request merged**
