### PR TITLE
Bug 1946597: Backport Remove the "instance" and "pod" labels for kube-state-metrics metrics

### PR DESCRIPTION
**Pull request by jan--f**
Backport of #1052

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
The `generate` job is failing because the generation isn't deterministic for `manifests/0000_50_cluster-monitoring-operator_02-role.yaml`. We have a task to migrate from the hacky Python script to full jsonnet eventually but for now, you'd have to amend the last commit and rollback the changes on `manifests/0000_50_cluster-monitoring-operator_02-role.yaml`.

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.00

**Pull request merged**
