### PR TITLE
OCPBUGS-1626: update jsonnet dependencies

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

This PR builds on top of #1915 which is the pull request generated by `openshift-monitoring-bot`. In addition to the normal jsonnet bumps, I made changes to avoid shipping the ScrapeConfig and PrometheusAgent artefacts since they are not supported within CMO.

### CODE REVIEW

**Review by marioferh — COMMENTED** [review]
/lgtm 
I think we can skip the test, taking a look here to the flaky test
https://github.com/openshift/cluster-monitoring-operator/pull/1967/files

**Review by slashpai — APPROVED** [review]

**Comment by slashpai** [comment]
🎉

**Pull request merged**
