### PR TITLE
MON-3376: Remove deprecated --logtostderr argument

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by danielmellado** [comment]
Can we have some link into the commit message to show where the deprecation message has been published? Thanks!

**Comment by raptorsun** [comment]
looks good. didn't find missing logs. 👍

**Comment by simonpasquier** [comment]
> Can we have some link into the commit message to show where the deprecation message has been published? Thanks!

Done

**Pull request merged**
