### PR TITLE
Bug 2008540: remove alert HighlyAvailableWorkloadIncorrectlySpread

### PR DESCRIPTION
**Pull request by raptorsun**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by raptorsun** [comment]
/hold
wait some time to see if the changes in #1135 causes any new problems.
If everything goes well, we merge this PR to remove the alert HighlyAvailableWorkloadIncorrectlySpread

**Comment by simonpasquier** [comment]
Ideally we also need https://github.com/openshift/cluster-monitoring-operator/pull/1489 to be merged.

/retitle Bug 2008540: remove alert HighlyAvailableWorkloadIncorrectlySpread

**Comment by juzhao** [comment]
checked with PR, HighlyAvailableWorkloadIncorrectlySpread is removed, we need #1489 to be merged. will set qe-approved label after that

**Comment by raptorsun** [comment]
> @raptorsun can you rebase? we should be good to go now that #1489 merged.

Now rebased 🙂

**Pull request merged**
