### PR TITLE
[release-4.6] Bug 1987246: node exporter calls /proc/cpuinfo multiple times causing the node to freeze

### PR DESCRIPTION
**Pull request by arajkumar**
Cherry-pick #1272

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by juzhao** [comment]
tested with the PR, no issue
/label qe-approved

**Comment by deads2k** [comment]
/cherry-pick-approved
?

**Comment by deads2k** [comment]
sigh

**Comment by deads2k** [comment]
patch manager: urgent BZ, already qe-approved

**Pull request merged**
