### PR TITLE
Bug 1755242: jsonnet/rules: fix memory_usage_bytes recording rule

### PR DESCRIPTION
**Pull request by s-urbaniak**
Currently cluster:memory_usage_bytes:sum references
node:node_memory_bytes_total:sum and node:node_memory_bytes_available:sum.

These are not available any more.

This fixes it.

### CODE REVIEW

**Comment by LiliC** [comment]
Ah we should merge this first in master I think, then bring it into 4.2, right?

**Comment by s-urbaniak** [comment]
@LiliC it is already in master. i am still unsure how to proceed here, trying to clarify.

**Pull request merged**
