### PR TITLE
Bug 1997497: Backport etcd telemetry

### PR DESCRIPTION
**Pull request by lilic**
etcd telemetry data has already proved useful for the etcd team, but we need more data to be able to make recommendations for customers as well as customer support. This backports etcd telemetry data to 4.8 so we can make decisions and document things in 4.10.

@simonpasquier as per our discussion. @hexfusion for your information.

### CODE REVIEW

**Comment by lilic** [comment]
> To complete the pull request process, please assign paulfantom after the PR has been reviewed.

😢

**Comment by lilic** [comment]
/bugzilla refresh

🔀

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by lilic** [comment]
@simonpasquier had to rebase as another telemetry PR got merged, do you mind adding lgtm again :) thanks!

**Comment by dgrisonnet** [comment]
@lilic the generate step is failing, it seems that you need to regenerate `Documentation/telemeter_query`.

**Comment by lilic** [comment]
Strange make generate didn't work this time, but after running make generate-in-docker worked correctly. @dgrisonnet please take a look, thanks!

@geliu2016 please take a look, thanks!

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

adding cherry-pick approved

**Pull request merged**
