### PR TITLE
Bug 1812719: address missing resource requests

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by s-urbaniak** [comment]
```
level=error msg="Cluster operator monitoring Degraded is True with UpdatingAlertmanagerFailed: Failed to rollout the stack. Error: running task Updating Alertmanager failed: waiting for Alertmanager object changes failed: waiting for Alertmanager: expected 3 replicas, updated 0 and available 0"
```
this looks somehow consistent, will have a look.

**Comment by s-urbaniak** [comment]
failures seem to be related to user workload monitoring cc @lilic :

```

**Comment by lilic** [comment]
Could be related, I have a WIP PR out already, can't be fixed before that. But seems like tests passed fine now.

**Pull request merged**
