### PR TITLE
MON-1261: exposing topology spread constraints through config

### PR DESCRIPTION
**Pull request by prashbnair**
This PR exposes the [TopologySpreadConstraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) through the CMO config. 

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by prashbnair** [comment]
@simonpasquier PTAL

**Comment by simonpasquier** [comment]
would you mind adding some unit tests in pkg/manifests/manifests_test.go

**Comment by prashbnair** [comment]
/retitle MON-1261: exposing topology spread constraints through config

**Comment by prashbnair** [comment]
> would you mind adding some unit tests in pkg/manifests/manifests_test.go

Done.

**Comment by juzhao** [comment]
passed testing.
/label qe-approved

**Comment by simonpasquier** [comment]
/close
I assume that we don't need this version anymore :)

**Pull request closed without merging**
