### PR TITLE
Bug 1791211: Add alert for no routes configured in alertmanager

### PR DESCRIPTION
**Pull request by paulfantom**
Backporting #585 and #613

/cc @s-urbaniak @LiliC @smarterclayton

### CODE REVIEW

**Comment by paulfantom** [comment]
We need some changes in origin repo first
/hold
/bugzilla refresh

**Comment by lilic** [comment]
Hmm @paulfantom something is odd here

**Comment by paulfantom** [comment]
/hold
it needs a fix in origin repo

**Comment by paulfantom** [comment]
Needs https://github.com/openshift/origin/pull/24638 to be merged first.

**Comment by lilic** [comment]
/retest

PR was merged

**Pull request merged**
