### PR TITLE
jsonnet: remove kube-controller-manager service monitor

### PR DESCRIPTION
**Pull request by s-urbaniak**
It has been moved into the operator repository.

Note: This requires https://github.com/openshift/cluster-kube-controller-manager-operator/pull/258
to propagate into the installation payload.

/cc @brancz @paulfantom

### CODE REVIEW

**Comment by brancz** [comment]
Any particular reason this is in hold? I see the related PR being merged.

**Comment by s-urbaniak** [comment]
@brancz oh, whops, that was merged fast, indeed, we can cancel the hold, there is going to be some latency before the related payload will be available though.

**Comment by brancz** [comment]
Yeah, but we can have the bot take care of re-trying :)

/hold cancel
/retest

**Comment by s-urbaniak** [comment]
this is failing consistently, I'll have a look

**Comment by soltysh** [comment]
/hold
until the root cause it diagnosed and to stop messing with queue statistics :wink:

**Comment by s-urbaniak** [comment]
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/258 and https://github.com/openshift/cluster-kube-controller-manager-operator/pull/262 are merged, so this has a good possibility of passing, let's see.

**Comment by s-urbaniak** [comment]
ok, this is green @brancz @paulfantom , I guess we are good to go here :-)

**Pull request merged**
