### PR TITLE
jsonnet: add named tenancy port

### PR DESCRIPTION
**Pull request by s-urbaniak**
It is declared in the service but not in the kube-rbac-proxy sidecar.

cc @metalmatze @squat

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@squat: @metalmatze raised concerns about the grafana bump, I'll change this PR to only consider the target port changes.

**Comment by s-urbaniak** [comment]
@metalmatze PTAL

**Comment by spadgett** [comment]
@s-urbaniak did you mean to leave the hold on this pr?

**Comment by s-urbaniak** [comment]
@spadgett the PR is LGTM'ed, but we're having flakes on e2e :-/

**Comment by s-urbaniak** [comment]
@spadgett flakes resolved, this is merged now :-)

**Pull request merged**
