### PR TITLE
Bug 1803957: Backport trusted ca support for prometheus

### PR DESCRIPTION
**Pull request by paulfantom**
Backporting https://github.com/openshift/cluster-monitoring-operator/pull/559

/cc @lilic @s-urbaniak

### CODE REVIEW

**Comment by s-urbaniak** [comment]
let's tackle BZ logistics another time

**Comment by eparis** [comment]
I'm overriding the invalid bug flag. while the dependent bug is targeting 4.3.0 it was actually fixed, verified, and closed in that release. This is rare. But when it comes up talk to your group lead about overriding.

**Comment by paulfantom** [comment]
Switched back to different directories for holding certificates as holding them in `/etc/pki/ca-trust/extracted/pem/` didn't work and caused oauth-proxy to return 500.

This was verified manually and all components (alertmanager/prometheus/grafana) were accessible via console.

/cc @lilic @s-urbaniak

**Pull request merged**
