### PR TITLE
Fix admission reviews versions

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by paulfantom — APPROVED** [review]
/lgtm

**Comment by simonpasquier** [comment]
/hold

Failing with the same issue as https://github.com/prometheus-operator/prometheus-operator/pull/3574. We need to bump to the future v0.43.0 before being able to merge this :)

```
level=error msg="Cluster operator monitoring Degraded is True with UpdatingTelemeterclientFailed: Failed to rollout the stack. Error: running task Updating Telemeter client failed: reconciling Telemeter client Prometheus Rule failed: creating PrometheusRule object failed: Internal error occurred: failed calling webhook \"prometheusrules.openshift.io\": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind="
```

**Comment by simonpasquier** [comment]
cc @s-urbaniak @paulfantom

**Pull request merged**
