### PR TITLE
disabled unused node exporter metrics

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Can be verified with the tool I created which compares the existing rules to the node exported metrics and prints the unused metrics

Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@krasi-georgiev these settings need to be disabled in jsonnet, as assets are generated only files. The actual source file is https://github.com/openshift/cluster-monitoring-operator/blob/master/jsonnet/node-exporter.jsonnet#L118.

Once changed in there, you need to `make generate-in-docker`

**Comment by krasi-georgiev** [comment]
@s-urbaniak yep I figured from the logs, but thanks for the pointer about the make command

**Comment by pgier** [comment]
I might be missing something here, but could there be some metrics that we still want even though they are not used in any rules?

**Comment by krasi-georgiev** [comment]
Here is the diff.
https://www.diffchecker.com/uklmLy5m


The quickest way to test is by running the node_exported locally.

Old Config
```
go build && sudo ./node_exporter \
--collector.filesystem.ignored-mount-points="^/(dev|proc|sys|var/lib/docker/.+)($|/)" \
--collector.filesystem.ignored-fs-types="^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$" \
--collector.mountstats \
--collector.cpu.info \
--no-collector.wifi
```

New Config
```
go build && sudo ./node_exporter \
--collector.filesystem.ignored-mount-points="^/(dev|proc|sys|var/lib/docker/.+)($|/)" \
--collector.filesystem.ignored-fs-types="^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$" \
--collector.mountstats \
--collector.cpu.info \
--no-collector.wifi \
--web.disable-exporter-metrics \
--no-collector.hwmon \
--no-collector.netstat \
--no-collector.sockstat \
--no-collector.entropy \
--no-collector.filefd \
--no-collector.time \
--no-collector.textfile \
--no-collector.conntrack \
--no-collector.bcache \
--no-collector.stat \
--no-collector.schedstat \
--no-collector.pressure \
--no-collector.powersupplyclass \
--no-collector.uname \
--no-collector.arp \
--no-collector.thermal_zone
```

Another way could be
 1. start an openshift cluster
 1. run a query against the Prometheus API to get all avaialble metric names - `/api/v1/label/__name__/values`
 1. Start another cluster with the new changes and run the same prometheus query.

**Comment by LiliC** [comment]
From quick glance I would keep the `go_*` specific metrics and the `promhttp_*` ones. Letting @pgier have a look as well.

Your tests seem to be failing as well 🤔

**Comment by krasi-georgiev** [comment]
> From quick glance I would keep the go_* specific metrics and the promhttp_* ones. Letting @pgier have a look as well.

why do you think that go_* specific metrics and the promhttp_* should be kept?

**Comment by LiliC** [comment]
I think those are useful to query in the clusters themselves.

**Comment by krasi-georgiev** [comment]
could you give an example query that is usefull to give me a better idea on how these can be used?

**Comment by LiliC** [comment]
@krasi-georgiev I believe the SRE team uses the promhttp_* metrics to define the SLOs on Prometheus itself.

**Comment by brancz** [comment]
Go runtime metrics are extremely useful for troubleshooting, go routines, heap, allocations, etc etc. they're all extremely valuable. The exercise here was rather to find collectors and or metrics that are entirely unnecessary or even wrong, like wifi collector, or potentially just having one of either the ntp or timex collectors etc..

**Comment by brancz** [comment]
I just noticed that this is in the cluster monitoring operator. I would expect any useless metrics to be useless in upstream kube prometheus just as much.

**Comment by krasi-georgiev** [comment]
will post a diff soon for the before and after metrics with this change.

**Comment by krasi-georgiev** [comment]
here is the diff for the current changes
https://www.diffchecker.com/tWNcrXUF

**Comment by krasi-georgiev** [comment]
Waiting for the [node exporter upgrade](https://github.com/openshift/cluster-monitoring-operator/pull/601) and will revisit this as the node_exporter flags will be different and than will also update in kube-prometheus

**Comment by paulfantom** [comment]
/close

This will be done in #624

**Pull request closed without merging**
