### PR TITLE
Use access to Alertmanager CR to gate access to AM

### PR DESCRIPTION
**Pull request by cblecker**
This changes the permissions needed to access Alertmanager's UI, and the ability to view its config or create silences. Instead of having to rely in the ability to see all namespaces, this changes the permissions to the ability to view the Alertmanager CR. This way, access can be specifically granted to users based on the ability to view that CR.

Also fix a makefile syntax issue on systems (such as Darwin) that use a different file path for the make binary.

cc: @RiRa12621 @brancz @sichvoge 
ref: https://jira.coreos.com/browse/SREP-1983

### CODE REVIEW

**Comment by s-urbaniak** [comment]
thanks @cblecker, the e2e test failure is valid here. The following alerts are being fired:
```
✔ALERTS{alertmanager="https://10.131.0.5:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="pending",endpoint="web",instance="10.131.0.7:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-1",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.131.0.5:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="pending",endpoint="web",instance="10.129.2.13:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-0",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.131.0.5:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="firing",endpoint="web",instance="10.131.0.7:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-1",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.131.0.5:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="firing",endpoint="web",instance="10.129.2.13:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-0",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.129.2.10:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="pending",endpoint="web",instance="10.131.0.7:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-1",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.129.2.10:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="pending",endpoint="web",instance="10.129.2.13:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-0",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.129.2.10:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="firing",endpoint="web",instance="10.131.0.7:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-1",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.129.2.10:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="firing",endpoint="web",instance="10.129.2.13:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-0",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.128.2.8:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="pending",endpoint="web",instance="10.131.0.7:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-1",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.128.2.8:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="pending",endpoint="web",instance="10.129.2.13:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-0",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.128.2.8:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="firing",endpoint="web",instance="10.131.0.7:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-1",service="prometheus-k8s",severity="warning"}
✔ALERTS{alertmanager="https://10.128.2.8:9095/api/v1/alerts",alertname="PrometheusErrorSendingAlertsToSomeAlertmanagers",alertstate="firing",endpoint="web",instance="10.129.2.13:9091",job="prometheus-k8s",namespace="openshift-monitoring",pod="prometheus-k8s-0",service="prometheus-k8s",severity="warning"}
```

The resolution should be failry easy. We need to give Prometheus the permissions expressed in the oauth proxy SAR: `'-openshift-sar={"group": "monitoring.coreos.com", "resource": "alertmanagers",
      "namespace": "openshift-monitoring", "verb": "get"}'`

**Comment by s-urbaniak** [comment]
I believe adding another `amRole` here should do the trick: https://github.com/openshift/cluster-monitoring-operator/blob/33872681bc9699861a3a883715279de450420ea6/jsonnet/prometheus.jsonnet#L11-L33

**Comment by s-urbaniak** [comment]
and referencing it here:
https://github.com/openshift/cluster-monitoring-operator/blob/33872681bc9699861a3a883715279de450420ea6/jsonnet/prometheus.jsonnet#L114-L115

**Comment by cblecker** [comment]
@s-urbaniak Thanks for helping to identify the errors. Should this in *in addition* to the `namespacesRole`, or *instead of* the `namespacesRole`?

**Comment by cblecker** [comment]
@s-urbaniak I'm guessing *instead of*, and running tests now. If it turns out that prometheus needs both permissions, then I'll add namespaces back in.

**Comment by cblecker** [comment]
Turns out it needed to be an *in addition to*. I've updated the PR, as well as updated the docs to indicate how to grant permissions.

**Pull request merged**
