### PR TITLE
OCPBUGS-33512: fix Thanos ruler alert generator url

### PR DESCRIPTION
**Pull request by jan--f**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by juzhao** [comment]
tested with PR
`launch 4.15.0-0.nightly-2024-05-08-194059,openshift/cluster-monitoring-operator#2343 gcp`
configured custom email alertmanager and trigger user project alert, the "Source" links to console UI now, not thanos UI.
/label cherry-pick-approved
/label qe-approved

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Pull request merged**
