### PR TITLE
 test/e2e: Make sure Prometheus only fires Watchdog alert 

### PR DESCRIPTION
**Pull request by mxinden**
In my local cluster Prometheus fires the `KubeClientCertificateExpiration` alert. Once we resolved that we can continue here. Opening it up for early feedback.

### CODE REVIEW

**Comment by mxinden** [comment]
Added 9883d6878168d4922ba6a9923fee2b379e54bc73 to address minor after-merge comments in https://github.com/openshift/cluster-monitoring-operator/pull/263/.

I am sorry for interleaving the two concerns, but given that this is such a minor change, going through the end-to-end-retest process would be a lot of toil.

**Comment by brancz** [comment]
This needs a rebase, otherwise lgtm.

**Comment by s-urbaniak** [comment]
whoops, I missed that we are still firing `KubeClientCertificateExpiration`. I am :+1: on this change.

**Comment by mxinden** [comment]
No worries @s-urbaniak, I added the `[do-not-merge/hold]` anyways. I will look into templating proper expiration intervals into `KubeClientCertificateExpiration`.

**Comment by mxinden** [comment]
Kicking off a retest as https://github.com/openshift/cluster-monitoring-operator/pull/275 is merged.

/retest

**Comment by brancz** [comment]
I think we were talking about that this should rather be part of the `e2e-aws` test suite right? Because otherwise if another team breaks something that makes an alert fire we are blocked. I think @paulfantom was already looking into moving some of our e2e tests to  `e2e-aws`, could you take care of this one as well?

**Comment by mxinden** [comment]
Yes, that sounds good @brancz.

On a current Openshift 4.0 cluster *TargetDown* alert is firing for *job="catalog-operator-metrics"*, *job="sdn"* and *job="olm-operator-metrics"*.

**Comment by paulfantom** [comment]
> could you take care of this one as well?

This one might be a bit trickier, but I will move it into `e2e-aws`.

**Comment by brancz** [comment]
I don't think we've ever added a test to that suite, keep us updated :)

**Pull request closed without merging**
