### PR TITLE
Remove OADP metrics from the Telemetry

### PR DESCRIPTION
**Pull request by mpryc**
This PR reverts the PR #1536.

OADP disabled cluster monitoring in favor of workload monitoring, because there were many additional metrics and as such the OADP metrics can be removed from Telemetry.

Related PR:
  https://github.com/openshift/oadp-operator/pull/1081
  https://github.com/openshift/oadp-operator/pull/1082

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by mpryc** [comment]
/hold

Need to have a green light from the SD

**Comment by jan--f** [comment]
/lgtm
@maorfr can you chime in here or ping someone who would?

**Comment by maorfr** [comment]
perhaps @sre-alert-sme could take a look?

**Comment by cblecker** [comment]
ack on behalf of @openshift/sre-alert-sme . This should be fine to remove. Thanks!

**Comment by mpryc** [comment]
/unhold

Rebased, it's ready to merge.

**Comment by jan--f** [comment]
/lgtm
Thanks everyone!

**Pull request merged**
