### PR TITLE
Bug 1949123: assets: fix instance:node_filesystem_usage:sum

### PR DESCRIPTION
**Pull request by dgrisonnet**
The instance:node_filesystem_usage:sum was previously accounting only
for the `/` mountpoint. This led to some issues were for some nodes, the
query wasn't returning any data. This is caused by the fact that the
`/` mountpoint isn't the rootfs of the host, but a virtual device. The
root of the host is mounted on /host/root in the node-exporter container
and the path to the /host/root is not stripped. The CLI flag to strip
the rootfs path was only added in node-exporter 0.17 and we are shipping
0.16 in OpenShift 3.11.

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Note that I tested the new query on a 3.11 cluster provided by @juzhao and it seems to fix the issue.

**Comment by paulfantom** [comment]
/lgtm

> Holding until CI is fixed on release-3.11 branch.

That's a tech-debt and if it is necessary, we should create a ticket and work on it. As of right now, I wouldn't block on this.

**Comment by dgrisonnet** [comment]
Unholding as #1157 was merged.

/unhold

**Comment by dgrisonnet** [comment]
No new changes, I just restarted the Travis jobs since doing it on Travis doesn't seem to update the status in github.

**Review by paulfantom — APPROVED** [review]
/lgtm

**Pull request merged**
