### PR TITLE
Update node_exporter mixin and kubernetes mixin

### PR DESCRIPTION
**Pull request by paulfantom**
Merge https://github.com/openshift/cluster-monitoring-operator/pull/454 and https://github.com/openshift/cluster-monitoring-operator/pull/452 into one PR to bring in changes in one go.

### CODE REVIEW

**Comment by paulfantom** [comment]
stopping retests

/hold

**Comment by brancz** [comment]
Just curious: why not update the Prometheus adapter config in kube prometheus? I would assume it’s similarly broken there no?

**Comment by s-urbaniak** [comment]
@brancz yes, agreed, i just want to see this pass here.

**Comment by s-urbaniak** [comment]
@brancz do you mind to have a look at https://github.com/openshift/cluster-monitoring-operator/pull/456/commits/7324558dfb4b235cd5dc3662ffce716a611b60d0#diff-f2a7750f46cf51bb668f12735f70777dR19 ? Is the query looking fine?

**Comment by paulfantom** [comment]
This will close the following BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=1733825
https://bugzilla.redhat.com/show_bug.cgi?id=1701856
https://bugzilla.redhat.com/show_bug.cgi?id=1733830

Additionally, we will need to revendor kube-prometheus, so it would be good to also revendor kubernetes-mixin. This way we will also close
https://bugzilla.redhat.com/show_bug.cgi?id=1745877 (cc: @metalmatze)

**Comment by s-urbaniak** [comment]
leaving this on `/hold` until we merge https://github.com/openshift/console/pull/2486 otherwise we'll regress on the console.

**Comment by s-urbaniak** [comment]
Unfortunately I regressed one little thing in the resource overrides, submitting a fix to kube-prometheus.

**Comment by brancz** [comment]
Let me know when you’re ready to have this be re-reviewed.

**Comment by s-urbaniak** [comment]
@brancz alright, this is good to go :+1: 

Synced with @spadgett that this will temporarily break node metrics in console which we already have WIP for fixing in https://github.com/openshift/console/pull/2486

**Pull request merged**
