### PR TITLE
DFMS-59: whitelist mcg-addon metrics for telemeter

### PR DESCRIPTION
**Pull request by rexagod**
Whitelisted MCG addon metrics for the Telemeter dashboard. Please refer
to the document below to know more about these metrics.
* https://docs.google.com/document/d/19JST--IQyxTa_330D7mjJZUTEi2dqJ9NXcJ9J0SrhyY/edit?usp=sharing

Refer: https://issues.redhat.com/browse/DFMS-59 and https://coreos.slack.com/archives/C010A637DGB/p1655898917627299?thread_ts=1655364594.953299&cid=C010A637DGB for more context.

Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
> Not sure why ci/prow/versions is failing.

It's expected and the test isn't required.

**Review by simonpasquier — COMMENTED** [review]
For each metric being added, we would need to know the [cardinality](https://www.robustperception.io/cardinality-is-key/):
* NooBaa_num_buckets_claims
* NooBaa_num_namespace_buckets
* NooBaa_num_unhealthy_bucket_claims
* NooBaa_num_unhealthy_namespace_buckets
* noobaa_accounts_num
* noobaa_total_usage
* odf_system_health_status
* odf_system_iops_total_bytes
* odf_system_throughput_total_bytes

**Comment by rexagod** [comment]
@simonpasquier Opened a revert PR here: https://github.com/rhobs/configuration/pull/250. Posting the cardinality requirements in a bit.

**Comment by rexagod** [comment]
@simonpasquier All the aformentioned queries are used as `QUERY{namespace="redhat-data-federation, _id="$id"}`, where `_id` is one of (or all of (`.*`)) the cluster(s) where the addon is installed. I do not know what is the upper bound on the limit of clusters that can exist at any given point of time, but if we can assume it to be `n` then that would also be the cardinality for all of them IMO.

**Comment by rexagod** [comment]
@simonpasquier PTAL, thanks.

```
- NooBaa_num_buckets_claims{container="core", endpoint="mgmt", instance="10.129.2.25:8080", job="noobaa-mgmt", namespace="redhat-data-federation", pod="noobaa-core-0", prometheus="redhat-data-federation/managed-mcg-prometheus", prometheus_replica="prometheus-managed-mcg-prometheus-0", service="noobaa-mgmt"}
- NooBaa_num_namespace_buckets{container="core", endpoint="mgmt", instance="10.129.2.25:8080", job="noobaa-mgmt", namespace="redhat-data-federation", pod="noobaa-core-0", prometheus="redhat-data-federation/managed-mcg-prometheus", prometheus_replica="prometheus-managed-mcg-prometheus-0", service="noobaa-mgmt"}
- NooBaa_num_unhealthy_bucket_claims{container="core", endpoint="mgmt", instance="10.129.2.25:8080", job="noobaa-mgmt", namespace="redhat-data-federation", pod="noobaa-core-0", prometheus="redhat-data-federation/managed-mcg-prometheus", prometheus_replica="prometheus-managed-mcg-prometheus-0", service="noobaa-mgmt"}
- NooBaa_num_unhealthy_namespace_buckets{container="core", endpoint="mgmt", instance="10.129.2.25:8080", job="noobaa-mgmt", namespace="redhat-data-federation", pod="noobaa-core-0", prometheus="redhat-data-federation/managed-mcg-prometheus", prometheus_replica="prometheus-managed-mcg-prometheus-0", service="noobaa-mgmt"}
- noobaa_accounts_num{container="core", endpoint="mgmt", instance="10.129.2.25:8080", job="noobaa-mgmt", namespace="redhat-data-federation", pod="noobaa-core-0", prometheus="redhat-data-federation/managed-mcg-prometheus", prometheus_replica="prometheus-managed-mcg-prometheus-0", service="noobaa-mgmt"}
- noobaa_total_usage{container="core", endpoint="mgmt", instance="10.129.2.25:8080", job="noobaa-mgmt", namespace="redhat-data-federation", pod="noobaa-core-0", prometheus="redhat-data-federation/managed-mcg-prometheus", prometheus_replica="prometheus-managed-mcg-prometheus-0", service="noobaa-mgmt"}
- odf_system_health_status{container="core", endpoint="mgmt", instance="10.129.2.25:8080", job="noobaa-mgmt", namespace="redhat-data-federation", pod="noobaa-core-0", prometheus="redhat-data-federation/managed-mcg-prometheus", prometheus_replica="prometheus-managed-mcg-prometheus-0", service="noobaa-mgmt", system_type="OCS", system_vendor="Red Hat"}
- odf_system_iops_total_bytes{container="kube-rbac-proxy", endpoint="https", job="noobaa-mgmt", namespace="redhat-data-federation", pod="prometheus-managed-mcg-prometheus-0", prometheus="redhat-data-federation/managed-mcg-prometheus", prometheus_replica="prometheus-managed-mcg-prometheus-0", service="noobaa-mgmt", system_type="OCS", system_vendor="Red Hat"}
- odf_system_throughput_total_bytes{container="kube-rbac-proxy", endpoint="https", job="noobaa-mgmt", namespace="redhat-data-federation", pod="prometheus-managed-mcg-prometheus-0", prometheus="redhat-data-federation/managed-mcg-prometheus", prometheus_replica="prometheus-managed-mcg-prometheus-0", service="noobaa-mgmt", system_type="OCS", system_vendor="Red Hat"}
```

**Comment by simonpasquier** [comment]
Thanks for the details. In total, this pull request adds 9 series to Telemetry. Before proceeding with this PR, it would be good to create recording rules that strip away unnecessary labels (e.g. `pod`, `container`, `endpoint`, ...) as the data would easier to parse in Telemetry and it will avoid unneeded series churn on pod rollouts.

```
rules:
- expr: cluster:NooBaa_num_buckets_claims:max
  record: max(NooBaa_num_buckets_claims{namespace="redhat-data-federation"})
```

See also examples [here](https://github.com/openshift/cluster-monitoring-operator/blob/fae5848dc68704db90becf7fc8b7612859e70ba6/assets/cluster-monitoring-operator/prometheus-rule.yaml#L43-L45)

cc @jan--f @bill3tt

**Comment by rexagod** [comment]
Created a PR with the modified metrics here: https://github.com/openshift/cluster-monitoring-operator/pull/1721. Closing this one.

**Pull request closed without merging**
