### PR TITLE
STOR-1154: Add vSphere topology to telemetry

### PR DESCRIPTION
**Pull request by jsafrane**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

Added aggregated vSphere topology metrics to telemetry. Approved by @jan--f in https://issues.redhat.com/browse/MON-2966.

When at it, I moved all vSphere prometheus rules to a separate group (they IMO don't belong to `openshift-kubernetes.rules`) + added aggregation for the new metrics.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/lgtm
/hold
until https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/135 merges.

**Comment by jsafrane** [comment]
/hold cancel
the metric have been merged to vmware-vsphere-csi-driver-operator

/retest-required

**Pull request merged**
