### PR TITLE
static auth changes for telemeter client

### PR DESCRIPTION
**Pull request by prashbnair**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by raptorsun** [comment]
shall we set `keyFile` and `certFile` in assets/telemeter-client/service-monitor.yaml, too?

**Comment by raptorsun** [comment]
I have the impression we are on a very similar task 😅. 
I'm modifying the telemeter client to use TLS clients certificates, too. 
https://github.com/openshift/cluster-monitoring-operator/pull/1392

**Comment by prashbnair** [comment]
> shall we set keyFile and certFile in assets/telemeter-client/service-monitor.yaml, too?

IMO, they are different tasks. I feel that I should not be adding as it does not have anything to do with static auth.
Please refer to #1393

**Comment by raptorsun** [comment]
> > shall we set keyFile and certFile in assets/telemeter-client/service-monitor.yaml, too?
> 
> IMO, they are different tasks. I feel that I should not be adding as it does not have anything to do with static auth. Please refer to #1393

OK, I will add these in #1392 .

**Pull request merged**
