### PR TITLE
OCPBUGS-20073: Limit the value of GOMAXPROCS on node-exporter to 4

### PR DESCRIPTION
**Pull request by raptorsun**
backport of https://github.com/openshift/cluster-monitoring-operator/pull/2023
JIRA: https://issues.redhat.com/browse/OCPBUGS-15473

### CODE REVIEW

**Comment by Tai-RedHat** [comment]
test with cluster-bot, GOMAXPROCS is set to 4
/label qe-approved
/label cherry-pick-approved

**Comment by raptorsun** [comment]
/override ci/prow/golangci-lint
No golang files are changed, we can safely overlook it.

**Pull request merged**
