### PR TITLE
OWNERS: move @paulfantom to emeritus section

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by jan--f** [comment]
/hold
This can wait until after the 4.9 release.

**Review by PhilipGough — APPROVED** [review]

**Review by slashpai — APPROVED** [review]

**Comment by simonpasquier** [comment]
/label qe-approved
no qe required

**Comment by simonpasquier** [comment]
/label px-approved
no px required

**Comment by simonpasquier** [comment]
/label docs-approved
no docs required

**Pull request merged**
