### PR TITLE
Remove kube scheduler service monitor

### PR DESCRIPTION
**Pull request by paulfantom**
Fixes MON-673

/cc @brancz 

Hold until we apply Service Monitor in kube-scheduler operator repo (https://github.com/openshift/cluster-kube-scheduler-operator/pull/149).
/hold

### CODE REVIEW

**Comment by paulfantom** [comment]
Apparently kube-scheduler-operator is applying ServiceMonitor manifest since February 27: https://github.com/openshift/cluster-kube-scheduler-operator/commit/824389304be63d1ba5cab0a077bb45adc948d213#diff-6a8c8567697d95131582dfd8bae8693e

/hold cancel

**Comment by brancz** [comment]
That's to scrape the operator itself though no?

**Comment by paulfantom** [comment]
Right, missed it. I will create a PR.

/hold

**Pull request merged**
