### PR TITLE
OCPBUGS-864: sorted condition and update on change

### PR DESCRIPTION
**Pull request by eggfoobar**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

Added sorting of conditions for deep equal checks
Added conditional check for status updates on changes

### CODE REVIEW

**Comment by eggfoobar** [comment]
Hey @slashpai it seems the `versions` job is failing for all recent PRs. Should we wait for that to be resolved first or is this PR okay to continue?

/assign @slashpai

**Comment by slashpai** [comment]
Its ok to /skip versions test

**Comment by eggfoobar** [comment]
Thanks @slashpai ! Is this good to merge?

**Comment by simonpasquier** [comment]
A ticket in OCPBUGS would be ideal. @slashpai could you clone TRT-481 and associate it with this PR?

**Comment by eggfoobar** [comment]
Thanks guys, I went ahead and created the OCPBUGS.

/rename OCPBUGS-864: sorted condition and update on change

**Pull request merged**
