### PR TITLE
Bug 1929354: [4.6] jsonnet/prometheus.jsonnet: Apply openshift-user-critical class to cluster Prometheus

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

Backport of #987 (to deploy the new `openshift-user-critical` priority class) and #1062 (to apply the new priority class to Prometheus).

### CODE REVIEW

**Comment by lihongyan1** [comment]
Test with PR based on payload
# oc -n openshift-monitoring get sts prometheus-k8s -oyaml | grep priorityClassName
      priorityClassName: openshift-user-critical

**Review by lilic — COMMENTED** [review]
/lgtm

**Pull request merged**
