### PR TITLE
Bug 2033751: bump(k8s+openshift): to kubernetes 1.23

### PR DESCRIPTION
**Pull request by damemi**
Seeing failures around monitoring operator in the 1.23 rebase (https://github.com/openshift/kubernetes/pull/1087):
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1087/pull-ci-openshift-kubernetes-master-e2e-aws-downgrade/1472980756421677056

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by damemi** [comment]
These failures seem like they should be resolved by bumping Prometheus:
```
# github.com/prometheus-operator/prometheus-operator/pkg/alertmanager
vendor/github.com/prometheus-operator/prometheus-operator/pkg/alertmanager/statefulset.go:288:26: undefined: "k8s.io/api/core/v1".Handler
vendor/github.com/prometheus-operator/prometheus-operator/pkg/alertmanager/statefulset.go:295:27: undefined: "k8s.io/api/core/v1".Handler
vendor/github.com/prometheus-operator/prometheus-operator/pkg/alertmanager/statefulset.go:306:4: unknown field 'Handler' in struct literal of type "k8s.io/api/core/v1".Probe
vendor/github.com/prometheus-operator/prometheus-operator/pkg/alertmanager/statefulset.go:312:4: unknown field 'Handler' in struct literal of type "k8s.io/api/core/v1".Probe
# github.com/prometheus-operator/prometheus-operator/pkg/prometheus
vendor/github.com/prometheus-operator/prometheus-operator/pkg/prometheus/statefulset.go:599:28: undefined: "k8s.io/api/core/v1".Handler
vendor/github.com/prometheus-operator/prometheus-operator/pkg/prometheus/statefulset.go:625:3: unknown field 'Handler' in struct literal of type "k8s.io/api/core/v1".Probe
```

But when I try to do that in https://github.com/openshift/cluster-monitoring-operator/pull/1521/commits/8f292f8d8d5867289e2e2cf4c8089e0ba2e28d30 (using `go get` to grab the latest version that matches the sha `prometheus-operator` imports), I end up with the following go mod errors
```
$ go mod vendor
go: finding module for package github.com/prometheus/prometheus/pkg/labels
go: found github.com/prometheus/prometheus/pkg/labels in github.com/prometheus/prometheus v2.5.0+incompatible
go: finding module for package github.com/prometheus/prometheus/model/labels
go: finding module for package github.com/prometheus/prometheus/model/rulefmt
go: finding module for package github.com/prometheus/prometheus/promql/parser
github.com/openshift/cluster-monitoring-operator/hack/promql_rule imports
	github.com/prometheus/prometheus/promql/parser: module github.com/prometheus/prometheus@latest found (v2.5.0+incompatible), but does not contain package github.com/prometheus/prometheus/promql/parser
github.com/openshift/cluster-monitoring-operator/pkg/client imports
	github.com/prometheus-operator/prometheus-operator/pkg/prometheus imports
	github.com/prometheus/prometheus/model/rulefmt: module github.com/prometheus/prometheus@latest found (v2.5.0+incompatible), but does not contain package github.com/prometheus/prometheus/model/rulefmt
github.com/openshift/cluster-monitoring-operator/pkg/client imports
	github.com/prometheus-operator/prometheus-operator/pkg/prometheus imports
	github.com/prometheus-operator/prometheus-operator/pkg/namespace-labeler imports
	github.com/prometheus/prometheus/model/labels: module github.com/prometheus/prometheus@latest found (v2.5.0+incompatible), but does not contain package github.com/prometheus/prometheus/model/labels
```

**Comment by arajkumar** [comment]
@damemi I'm suppose to be bumping the versions as part of https://github.com/openshift/cluster-monitoring-operator/issues/1486. Currently I'm fixing the problem related to prometheus version mismatch.

**Comment by arajkumar** [comment]
@damemi FYI https://github.com/openshift/cluster-monitoring-operator/pull/1523

**Comment by simonpasquier** [comment]
> These failures seem like they should be resolved by bumping Prometheus

@damemi I'm not sure to understand how bumping the Prometheus dependency in CMO would change anything. Looking at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1087/pull-ci-openshift-kubernetes-master-e2e-aws-downgrade/1472980756421677056, prometheus-k8s-0 fails to start because it can't write to `/prometheus` which is mounted from a PV.

**Comment by simonpasquier** [comment]
I see also that a subsequent run of the same job passes: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1087/pull-ci-openshift-kubernetes-master-e2e-aws-downgrade/1473054992695824384

**Comment by damemi** [comment]
@simonpasquier at this point, we are trying to just narrow down failure cases and monitoring operator showed up in several runs. The first thing I checked for in that case was to see if it was updated to the latest libraries in sync with the rest of the release. I see @arajkumar opened another PR https://github.com/openshift/cluster-monitoring-operator/pull/1523 to take this over, so I'm going to close mine. Please feel free to use the Bugzilla I linked for this PR to allow it to be merged, thanks!
/close

**Pull request closed without merging**
