### PR TITLE
Bug 1832819: bump kubernetes-monitoring/kubernetes-mixin

### PR DESCRIPTION
**Pull request by simonpasquier**
Add 'short' and 'long' labels to differentiate between KubeAPIErrorBudgetBurn alerts and avoid ingestion errors on alert evaluations.

### CODE REVIEW

**Comment by simonpasquier** [comment]
cc @openshift/openshift-team-monitoring

**Comment by lilic** [comment]
Apparently we should be more detailed about what this kind of bumps include for some automation reasons, do you mind adding to the description that this adjusts apiserver SLO alerts. thanks!

**Comment by simonpasquier** [comment]
Hmm, ok...

**Comment by paulfantom** [comment]
> Apparently we should be more detailed about what this kind of bumps include for some automation reasons, do you mind adding to the description that this adjusts apiserver SLO alerts. thanks!

Wasn't that a guideline and not something enforced?

**Pull request merged**
