### PR TITLE
Bug 1969963: Recording rule for builds by strategy

### PR DESCRIPTION
**Pull request by adambkaplan**
Aggregate the number of builds run on a cluster by strategy, and export
the recording rule to Telemeter. This will help the Build API team
determine which build strategies are actively being used on a cluster.

The recording rule will produce a time series with the following
strategy labels:

- docker
- source
- jenkinspipeline
- custom

* [x] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/retitle Bug 1969963: Recording rule for builds by strategy

**Comment by wewang58** [comment]
Verified it in version:4.7.0-0.ci.test-2021-06-10-031605-ci-ln-2cnirrb-latest

**Comment by adambkaplan** [comment]
/assign @dgrisonnet 

This metric was previously approved by Clayton in #1136

**Pull request merged**
