### PR TITLE
add mapi specific resources to etcd_object_counts

### PR DESCRIPTION
**Pull request by elmiko**
This change adds MachineAutoscalers, MachineHealthChecks, and Machines
to the count of etcd resources that are exposed in telemetry through
etcd_object_counts. This change is being made to support the Machine API
Usage Telemetry enhancement[0].

[0]
https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/machine-api-usage-telemetry.md

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by elmiko** [comment]
i am not sure if this needs an entry in the changelog, but i am happy to add if it requested.

**Comment by elmiko** [comment]
i could use a little help with the CI here, it's not clear to me if my changes have caused these errors.

**Comment by elmiko** [comment]
ok, i'm trying to follow the contributing instructions but when i run `make generate` i am hitting an error:

```
$ make generate
Installing tools from hack/tools.go
-mod=mod not supported (can be '', 'readonly', or 'vendor')
make: *** [Makefile:150: /home/mike/workspace/go/src/github.com/openshift/cluster-monitoring-operator/tmp/bin/go-bindata] Error 1
```

using
```
$ go version
go version go1.13.11 linux/amd64
```

**Comment by elmiko** [comment]
i gather that i need a newer version of go lang binary. i'm working on that now

**Comment by elmiko** [comment]
i've made it a little further. i was able to get things working with go version 1.14, but now i'm hitting a python2 dependency:

```
# Check if files were properly generated
[ -f "assets/telemeter-client/trusted-ca-bundle.yaml" ] || exit 1
# Using "-modtime 1" to make generate target deterministic. It sets all file time stamps to unix timestamp 1
/home/mike/workspace/cluster-monitoring-operator/tmp/bin/go-bindata -mode 420 -modtime 1 -pkg manifests -o pkg/manifests/bindata.go assets/...
python2 hack/merge_cluster_roles.py hack/cluster-monitoring-operator-role.yaml.in `find assets | grep role | grep -v "role-binding" | sort` > manifests/0000_50_cluster_monitoring_operator_02-role.yaml
Traceback (most recent call last):
  File "hack/merge_cluster_roles.py", line 20, in <module>
    import yaml
ImportError: No module named yaml
make: *** [Makefile:97: manifests/0000_50_cluster_monitoring_operator_02-role.yaml] Error 1
```

unfortunately, i'm not sure how to solve this one. fedora 32 (which i'm using) doesn't seem to have a python2-pyyaml package. i will try creating a virtual environment and running from there.

**Comment by elmiko** [comment]
just an update, got it working by creating a virtual env, installing pyyaml, and then running the make command inside the virtual env.

**Comment by elmiko** [comment]
updated with files from `make generate` command

**Comment by lilic** [comment]
Sorry about that, yes thsoe are the dependencies. cc @paulfantom did we not end up documenting the dependencies? 🤔 

/retest

Seems like a strange failure:

>   * could not run steps: step generate failed: test "generate" failed: the pod ci-op-ixmxjgsz/generate failed after 1m43s (failed containers: test): ContainerFailed one or more containers exited

**Comment by elmiko** [comment]
looking at the error logs, it is unclear to me if i have introduced this problem. do i need to change something?

**Comment by lilic** [comment]
Can you try running `make clean` and then run `make generate` again. Thanks!

**Comment by elmiko** [comment]
> Can you try running `make clean` and then run `make generate` again. Thanks!

just ran this, but it produced no changes from the current commit.

**Comment by lilic** [comment]
hmm strange should work fine, we recently had generate passing on multiple PRs. @paulfantom introduced the generate make target changes maybe he has more ideas?

**Comment by elmiko** [comment]
it looks like the tooling is complaining because it is producing a different output, even though they are both the same content-wise (eg the difference is cosmetic not contextual).

**Comment by lilic** [comment]
Do you mind rebasing and checking out the docs here https://github.com/openshift/cluster-monitoring-operator/pull/895

**Comment by elmiko** [comment]
rebased and then i re-ran `make clean generate`

**Comment by paulfantom** [comment]
Sorry, but it seems you need to rebase again :( We have a ticket to make this process less prone to merge conflicts, but it is what it is for now.
I recommend separating your manual changes from generated ones in two separate commits to ease the process of rebasing.

We are also bringing back `make generate-in-docker` in https://github.com/openshift/cluster-monitoring-operator/pull/895 to simplify the process of generating assets.
If you need any more assistance, feel free to ping me on slack (@paulfantom) :)

**Comment by elmiko** [comment]
no worries, i'll split the commits and then push a new version of this. thanks @paulfantom !

**Comment by elmiko** [comment]
@paulfantom ok, i have rebased against master, separated into 2 commits with the rules.jsonnet in the first and the generated files in the second. let's hope this passes ;) :four_leaf_clover:

**Comment by elmiko** [comment]
@paulfantom not sure why the generate test is still failing, the aws and aws-operator tests _look_ like flakes but i'm not sure.

**Comment by lilic** [comment]
Seems like because there was a conflict, can you rebase. Sorry about this!

**Comment by elmiko** [comment]
thanks @lilic , updated again with rebase and fresh generated files

**Comment by lilic** [comment]
@elmiko  That was a strange failure, you did run make clean and make generate-in-docker?

**Comment by paulfantom** [comment]
I think our python script responsible for generating `manifests/0000_50_cluster_monitoring_operator_02-role.yaml` is non-deterministic and output depends on the runtime environment. Could you again rebase and regenerate stuff but not commit said file?

Sorry for the issues, we have on our radar a plan to rewrite that script to golang and make it deterministic.

**Comment by elmiko** [comment]
ok, i rebased, cleaned everything, and regenerated the files except this time i only added these files to the second commit:
* assets/prometheus-k8s/rules.yaml
* pkg/manifests/bindata.go

**Comment by simonpasquier** [comment]
there's still conflicts for ` pkg/manifests/bindata.go `.

**Comment by elmiko** [comment]
@simonpasquier any adivce?

should i rebase, clean, regenerate again?

**Comment by simonpasquier** [comment]
@elmiko yes please rebase on master and regenerate the artefacts. Note that we need a valid BZ id in the PR's title for merging.

**Comment by elmiko** [comment]
> @elmiko yes please rebase on master and regenerate the artefacts. Note that we need a valid BZ id in the PR's title for merging.

at this point i might just wait for the next devel cycle to open up, i don't think we need to bz this into the current release.

**Comment by elmiko** [comment]
hi, i am returning to this pr and i am noticing that the rule i was going to change doesn't seem to exist. where should i modify to ensure that that machine-api types from this pr are exposed in the etcd_object_counts through telemetry? (or is this not needed now)

**Comment by lilic** [comment]
@elmiko are you talking about `instance:etcd_object_counts:sum ` metric? This is defined here https://github.com/openshift/cluster-monitoring-operator/blob/57a33cb45dc97d23f0b77885c2acd10fd8b60717/jsonnet/rules.jsonnet#L198-L199

and the telemetry allowlist is here https://github.com/openshift/cluster-monitoring-operator/blob/1fcb682cad986c8a2b8437b6c93b5a66cdc9cbef/manifests/0000_50_cluster-monitoring-operator_04-config.yaml#L60-L63

**Comment by elmiko** [comment]
@lilic yes, but it seems like the operator has changed since i made my original pull request. are all the objects reported in that metric?

if all the resource objects are now exposed through that metric to telemetry, then it seems like i don't need to do anything. i'm just trying to figure out if that's accurate.

**Comment by lilic** [comment]
@elmiko you can try to query it in telemetry and see if you have enough information with the current metrics, in the end you know best for what you need this data.

**Comment by elmiko** [comment]
thanks @lilic, is this code live in 4.6?

**Comment by lilic** [comment]
@elmiko you mean how to query this on telemetry? Should be summed up here https://help.datahub.redhat.com/docs/interacting-with-telemetry-data otherwise ask the folks on #forum-telemetry slack channel. :)

**Comment by elmiko** [comment]
thanks @lilic !

**Comment by elmiko** [comment]
i am closing this request as i believe things have changed enough that it is no longer relevant.

thanks to everyone who helped =)

**Pull request closed without merging**
