### PR TITLE
Move alertmanager-proxy port to 9095

### PR DESCRIPTION
**Pull request by paulfantom**
Needed to merge https://github.com/openshift/prometheus-operator/pull/35 as we need to move alertmanager-proxy to not be on port 9094.

/cc @brancz @LiliC @s-urbaniak

### CODE REVIEW

**Comment by brancz** [comment]
Would it be possible to instead of changing the port to just bind against the pod ip? Alertmanager binds against localhost iirc. I feel that would be a less breaking and less unexpected setup.

**Comment by s-urbaniak** [comment]
ping @paulfantom can you comment on https://github.com/openshift/cluster-monitoring-operator/pull/411#issuecomment-515072249?

**Comment by brancz** [comment]
For context, we've had bugs opened for similar changes, and this one is rather extreme, as if someone integrated with the alertmanager endpoints (which we actively encourage), then we've just broken their alerting pipeline.

**Comment by paulfantom** [comment]
We can roll it back and even provide backwards compatibility by forcing alertmanager to advertise gossip not on port 9094 but on 6783 by using `--cluster.listen-address` alertmanager parameter. However this would need some changes in prometheus-operator, so maybe you are right and let's just bind against the pod ip.

I didn't want to have two different things on port with the same number as this might be confusing.

**Pull request merged**
