### PR TITLE
Bug 2065577:  CMO now creates by default an empty CM for UWM

### PR DESCRIPTION
**Pull request by JoaoBraveCoding**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by sthaha — COMMENTED** [review]
/lgtm

I wonder if this behaviour has to validated using a test

**Comment by juzhao** [comment]
@JoaoBraveCoding from assets/cluster-monitoring-operator/user-workload-config-edit-role.yaml file, we've added detailed `verbs` for configmaps, then it's no need to create an empty CM for UWM, see file: assets/prometheus-user-workload/config-map.yaml
FYI: in a fresh OCP cluster, cluster-monitoring-config cofigmap is not created by default, for UWM, we should not create user-workload-monitoring-config confimap either.
@simonpasquier WDYT?

**Comment by simonpasquier** [comment]
> @JoaoBraveCoding from assets/cluster-monitoring-operator/user-workload-config-edit-role.yaml file, we've added detailed `verbs` for user-workload-monitoring-config-edit role, then it's no need to create an empty CM for UWM, see file: assets/prometheus-user-workload/config-map.yaml FYI: in a fresh default OCP cluster, cluster-monitoring-config cofigmap is not created by default, for UWM, we should not create user-workload-monitoring-config confimap either. @simonpasquier WDYT?

IIUC the `create` verb can't be restrictd to a particular resource. From https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources

>  Note: You cannot restrict create or deletecollection requests by their resource name. For create, this limitation is because the name of the new object may not be known at authorization time. If you restrict list or watch by resourceName, clients must include a metadata.name field selector in their list or watch request that matches the specified resourceName in order to be authorized. For example, kubectl get configmaps --field-selector=metadata.name=my-configmap 

so we have to the following options
* CMO creates the `user-workload-monitoring-config` configmap (with no data) if it doesn't exist
* Allow the `user-workload-monitoring-config-edit` role to create configmaps in the `openshift-user-workload-monitoring` namespace.

The latter option means that a user could create as many configmaps as they want which isn't something that we want?

For consistency, CMO may create an empty `cluster-monitoring-config` configmap if missing but I feel that it's outside the scope of this PR.

**Comment by juzhao** [comment]
> so we have to the following options
> 
> * CMO creates the `user-workload-monitoring-config` configmap (with no data) if it doesn't exist
> * Allow the `user-workload-monitoring-config-edit` role to create configmaps in the `openshift-user-workload-monitoring` namespace.
Thanks, I thought any option would fix the issue, after checking, we need both of them together to fix the issue

**Comment by juzhao** [comment]
tested with PR, CMO now creates by default an empty CM for UWM and user with user-workload-monitoring-config-edit role could edit user-workload-monitoring-config configmap
/label qe-approved

**Pull request merged**
