### PR TITLE
Bug 2037073: pkg/manifests: account for slow DNS resolutions

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by bison — APPROVED** [review]
I see this is WIP, but it looks good to me. I guess this means it could take 60 (20 + 4 * 10) seconds total?

**Comment by EmilienM** [comment]
I tested this patch with OpenStack and it solved our issue, we managed to get AlertManager happy and no issue was found.

Thanks

**Comment by simonpasquier** [comment]
> I guess this means it could take 60 (20 + 4 * 10) seconds total?

@bison yes

**Review by bison — APPROVED** [review]
/lgtm

**Pull request merged**
