### PR TITLE
[release-4.15] OCPBUGS-36563: add runbook_url annotations

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
backport-risk-assessed

**Comment by juzhao** [comment]
compared with 4.16 PR: https://github.com/openshift/cluster-monitoring-operator/pull/2404
4.15 PR missed runbook_url annotations for TargetDown/PrometheusDuplicateTimestamps/KubeAggregatedAPIErrors alerts, these alerts exit in 4.15
````
# oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.15.0-0.nightly-2024-07-04-091603   True        False         6h54m   Cluster version is 4.15.0-0.nightly-2024-07-04-091603

# oc -n openshift-monitoring get prometheusrules cluster-monitoring-operator-prometheus-rules -o jsonpath='{.spec.groups[*].rules[?(@.alert=="TargetDown")]}' | jq '{alert: .alert, runbook_url: .annotations.runbook_url}'
{
  "alert": "TargetDown",
  "runbook_url": null
}

# oc -n openshift-monitoring get prometheusrules prometheus-k8s-prometheus-rules -o jsonpath='{.spec.groups[*].rules[?(@.alert=="PrometheusDuplicateTimestamps")]}' | jq '{alert: .alert, runbook_url: .annotations.runbook_url}'
{
  "alert": "PrometheusDuplicateTimestamps",
  "runbook_url": null
}

# oc -n openshift-monitoring get prometheusrules kubernetes-monitoring-rules -o jsonpath='{.spec.groups[*].rules[?(@.alert=="KubeAggregatedAPIErrors")]}' | jq '{alert: .alert, runbook_url: .annotations.runbook_url}'
{
  "alert": "KubeAggregatedAPIErrors",
  "runbook_url": null
}
```

**Comment by simonpasquier** [comment]
@juzhao the runbook links for TargetDown, PrometheusDuplicateTimestamps and KubeAggregatedAPIErrors were added during the 4.16 dev cycle but not backported. If they should then it's another OCPBUGS ticket IMHO.

**Pull request merged**
