### PR TITLE
OCPBUGS-1766: jsonnet: disable KubePersistentVolumeInodesFillingUp alert

### PR DESCRIPTION
**Pull request by jan--f**
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by juzhao** [comment]
tested with PR, KubePersistentVolumeInodesFillingUp alert is removed
/label qe-approved

**Comment by jan--f** [comment]
> It looks like there's a jsonnet formatting issue.

fixed now :grin:

**Review by simonpasquier — COMMENTED** [review]
we shouldn't need to disable the alert now that https://bugzilla.redhat.com/show_bug.cgi?id=2132270 is fixed and verified for ODF 4.12.0?

**Comment by jan--f** [comment]
> we shouldn't need to disable the alert now that https://bugzilla.redhat.com/show_bug.cgi?id=2132270 is fixed and verified for ODF 4.12.0?

yup, closing this.
/close

**Pull request closed without merging**
