### PR TITLE
[release-4.15] OCPBUGS-36312: inject trusted CA bundle into UWM Alertmanager

### PR DESCRIPTION
**Pull request by simonpasquier**
This is a manual cherry-pick of https://github.com/openshift/cluster-monitoring-operator/pull/2373.

Replaces https://github.com/openshift/cluster-monitoring-operator/pull/2399

### CODE REVIEW

**Review by slashpai — COMMENTED** [review]
/lgtm

**Review by marioferh — COMMENTED** [review]
/lgtm

**Pull request merged**
