### PR TITLE
Bug 1955464: drop container_memory_failures_total metric backport

### PR DESCRIPTION
**Pull request by slashpai**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
you need to run `make  pkg/manifests/bindata.go` too and commit the changes. For CMO <= 4.6, the static assets were embedded in the Go binary which adds one more step for the generation (it was also a pain because it creates many merge conflicts and mandatory rebases).

**Comment by slashpai** [comment]
> you need to run `make pkg/manifests/bindata.go` too and commit the changes. For CMO <= 4.6, the static assets were embedded in the Go binary which adds one more step for the generation (it was also a pain because it creates many merge conflicts and mandatory rebases).

Ran make command to regenerate manifests

**Comment by slashpai** [comment]
@simonpasquier It is fixed now. Can you review?

**Pull request merged**
