### PR TITLE
assets: move Kube*Down alerts to corresponding operators

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/openshift/cluster-kube-apiserver-operator/pull/622
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/298
https://github.com/openshift/cluster-kube-scheduler-operator/pull/180

### CODE REVIEW

**Comment by sjenning** [comment]
fyi @csrwng @derekwaynecarr

**Comment by sjenning** [comment]
aaand of course this is a generated file :man_facepalming: 
down the rabbit hole I go to figure out where this should actually be changed.

**Comment by sjenning** [comment]
likely either here
https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules/kubernetes-absent.yaml
or here
https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml

**Comment by LiliC** [comment]
Yes this is indeed generated manifets, these alerts trickle down from https://github.com/kubernetes-monitoring/kubernetes-mixin so its not as easy to just remove.

cc @brancz

**Comment by sjenning** [comment]
looks like this is the source
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/0d91b77bd64f9f83541fdbd394b9d8d6a1b87682/config.libsonnet#L15-L21

**Comment by s-urbaniak** [comment]
@sjenning yes, these alerts are maintained in upstream. We have to change those alerts there, then vendor those changes in here.

**Comment by brancz** [comment]
That's correct, we should refactor the alerts in the kubernetes-mixin so that they can be imported on a per component basis, and then individually remove them here and import them in the component operator repos.

**Comment by sjenning** [comment]
@brancz they have already started merging into the component repos (see PRs in the description).  If you could do this refactor, or tell me how to do it, that would be great.

**Comment by derekwaynecarr** [comment]
To provide context, this is desired to support deploying on IBM Cloud where we run control planes on management cluster, but still deploy the rest of cluster monitoring in the user cluster.

**Comment by brancz** [comment]
I went ahead and refactored the kubernetes mixin to allow importing recording and alerting rules by component (https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/281) so what we can do here is just filter out the rule groups related to the apiserver.

**Pull request closed without merging**
