### PR TITLE
Bug 1829244: Update kubernets-mixin to get improvements for kube-apiserver-availability

### PR DESCRIPTION
**Pull request by metalmatze**
/cc @lilic

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@metalmatze something is iffy with the generate target :thinking:

**Comment by paulfantom** [comment]
`generate` issues may be caused by different go-bindata versions.

**Comment by metalmatze** [comment]
Thanks for the hint @paulfantom I've updated (`go get -u`) my go-bindata binary and committed the changes. Let's see.

**Comment by paulfantom** [comment]
@metalmatze maybe try following:
```
docker pull quay.io/coreos/jsonnet-ci
make --always-make generate-in-docker
```

**Comment by simonpasquier** [comment]
I've started #781 to take over since it was easier than trying to resolve the conflicts.

**Comment by simonpasquier** [comment]
/close

thanks for the work @metalmatze :)

**Pull request closed without merging**
