### PR TITLE
OCPBUGS-44971: Add new metrics for OpenShift logging telemetry

### PR DESCRIPTION
**Pull request by xperimental**
Backport of #2512 to `release-4.17`. Updated with fixes from #2528.

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by juzhao** [comment]
@xperimental please refer to https://issues.redhat.com/browse/OCPBUGS-44724 and change to correct metrics format

**Comment by xperimental** [comment]
@juzhao Created a PR for the mentioned bug and targeting `release-4.18`. Is there already a bug for 4.19, because it looks like the branching just happened?

Also updated this PR with the new content.

**Comment by xperimental** [comment]
also cc @simonpasquier , because he's assigned to the other issue.

**Comment by juzhao** [comment]
> @juzhao Created a PR for the mentioned bug and targeting `release-4.18`. Is there already a bug for 4.19, because it looks like the branching just happened?
> 
> Also updated this PR with the new content.

thanks, branch is 4.19 now, need to fix in 4.19 then back port to 4.18

**Comment by juzhao** [comment]
seems it's no need to back-port to 4.17, the original PR https://github.com/openshift/cluster-monitoring-operator/pull/2512 is merged to 4.18

**Comment by xperimental** [comment]
> seems it's no need to back-port to 4.17, the original PR #2512 is merged to 4.18

This is not correct. The backport of the original change has not happened yet. This is what this PR is starting. It just also includes the changes of the fix, because it does not make sense to do this in two steps.

**Pull request merged**
