### PR TITLE
Bug 1872786: jsonnet: remove apiserver_request:availability30d

### PR DESCRIPTION
**Pull request by dgrisonnet**
The apiserver_request:availability30d recording rule evaluation fails in
big clusters. As this rule is currently neither used by customers nor by
the monitoring stack, it is safe to remove it for now until the rule is
fixed upstream.

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Holding this PR until we run the experiment with the potential upstream fix.

/hold

**Comment by simonpasquier** [comment]
/hold
waiting for #985

**Comment by simonpasquier** [comment]
you'd have to rebase because of bindata removal :)

**Comment by RiRa12621** [comment]
@simonpasquier I think tests pass, can we LGTM this so it gets to QA? We're getting a significant amount of those for OSD apparently

**Comment by RiRa12621** [comment]
/hold
depends on #1010

**Pull request merged**
