### PR TITLE
jsonnet: bump dependencies and regenerate

### PR DESCRIPTION
**Pull request by s-urbaniak**
This adds device mapper (dm-.+) disk devices.

xref https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/166
xref https://bugzilla.redhat.com/show_bug.cgi?id=1673787

A separate PR for the 3.11 is about to follow

cc @brancz @metalmatze

### CODE REVIEW

**Comment by s-urbaniak** [comment]
/hold

let me test this first.

**Comment by brancz** [comment]
preliminarily looks good, I just want to make sure we're unaffected by the cluster label addition

**Comment by brancz** [comment]
/hold
/lgtm

feel free to remove hold, once you verify that the dashboards still work as expected

**Comment by s-urbaniak** [comment]
/hold cancel
verified dashboards are working fine.

**Comment by s-urbaniak** [comment]
Also verified, the new `dm-.+` recording rules were working correctly.

**Pull request merged**
