### PR TITLE
OCPBUGS-1321: Node Exporter - ignore virtual NICs from OVNK cluster

### PR DESCRIPTION
**Pull request by raptorsun**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

These NICs are to ignore:

- tun[0-9]*
- br[0-9]*
- ovn-k8s-mp[0-9]*
- br-ex
- br-int
- br-ext

### CODE REVIEW

**Comment by raptorsun** [comment]
Hello @dcbw , could you please verify the patterns to ignore are correct?

**Comment by simonpasquier** [comment]
Any reason why the change doesn't make sense in prometheus-operator/kube-prometheus directly? If anything, the upstream jsonnet should at least provide a way to tune the list of ignored interfaces (rather than manipulating the args directly).

**Pull request merged**
