### PR TITLE
OCPBUGS-18643: address lint warnings

### PR DESCRIPTION
**Pull request by rexagod**
_Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>_

* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by rexagod** [comment]
/jira refresh
IIRC we also created a `MON`-ticket for the corresponding `OCPBUGS`-ticket, but I'm not sure.

**Comment by juzhao** [comment]
failed job ci/prow/versions link
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-monitoring-operator/2284/pull-ci-openshift-cluster-monitoring-operator-master-versions/1769545575235063808
```
2024/03/18 02:08:13 [DEBUG] GET https://raw.githubusercontent.com/openshift/kubernetes-metrics-server/master/manifests/release/kustomization.yaml
2024/03/18 02:08:13 couldn't fetch the new version for kubernetesMetricsServer: non 200 response
exit status 1
```
no file https://raw.githubusercontent.com/openshift/kubernetes-metrics-server/master/manifests/release/kustomization.yaml

**Comment by machine424** [comment]
For my curiosity, was this done manually or via a tool/linter?


> failed job ci/prow/versions link https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-monitoring-operator/2284/pull-ci-openshift-cluster-monitoring-operator-master-versions/1769545575235063808
> 
> ```
> 2024/03/18 02:08:13 [DEBUG] GET https://raw.githubusercontent.com/openshift/kubernetes-metrics-server/master/manifests/release/kustomization.yaml
> 2024/03/18 02:08:13 couldn't fetch the new version for kubernetesMetricsServer: non 200 response
> exit status 1
> ```
> 
> no file https://raw.githubusercontent.com/openshift/kubernetes-metrics-server/master/manifests/release/kustomization.yaml

https://github.com/openshift/cluster-monitoring-operator/pull/2286 fixes that I think.

**Comment by juzhao** [comment]
> #2286 fixes that I think.
#2286 was merged 5 days ago, the failed prow versions job was executed 3 weeks ago, which #2286 was not merged then, rerun the job, it passed now

**Comment by juzhao** [comment]
> For my curiosity, was this done manually or via a tool/linter?
> 
> > failed job ci/prow/versions link https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-monitoring-operator/2284/pull-ci-openshift-cluster-monitoring-operator-master-versions/1769545575235063808
> > ```
> > 2024/03/18 02:08:13 [DEBUG] GET https://raw.githubusercontent.com/openshift/kubernetes-metrics-server/master/manifests/release/kustomization.yaml
> > 2024/03/18 02:08:13 couldn't fetch the new version for kubernetesMetricsServer: non 200 response
> > exit status 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > no file https://raw.githubusercontent.com/openshift/kubernetes-metrics-server/master/manifests/release/kustomization.yaml
> 
> #2286 fixes that I think.

https://github.com/openshift/cluster-monitoring-operator/pull/2286 was merged 5 days ago, the failed prow versions job was executed 3 weeks ago, which https://github.com/openshift/cluster-monitoring-operator/pull/2286 was not merged then, rerun the job, it passed now

**Pull request merged**
