### PR TITLE
*: remove openshift-apiserver service monitor

### PR DESCRIPTION
**Pull request by s-urbaniak**
Fixes MON-670

/cc @paulfantom @brancz

### CODE REVIEW

**Comment by s-urbaniak** [comment]
We need to have the following merged first:
- https://github.com/openshift/cluster-openshift-apiserver-operator/pull/207
- https://github.com/openshift/cluster-openshift-apiserver-operator/pull/208

**Comment by paulfantom** [comment]
Rebased onto master.

/hold cancel

**Comment by paulfantom** [comment]
Rebased due to merge conflicts from #376.

**Comment by paulfantom** [comment]
Regenerated files as it was needed after rebase.

**Pull request merged**
