### PR TITLE
Add managed-by label to all objects

### PR DESCRIPTION
**Pull request by paulfantom**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

part of [MON-1291](https://issues.redhat.com/browse/MON-1291)

### CODE REVIEW

**Comment by dgrisonnet** [comment]
The e2e failures seems to be unrelated to the changes introduced by this PR.

/lgtm
/retest

**Comment by paulfantom** [comment]
Rebased to fix conflicts

**Comment by s-urbaniak** [comment]
@paulfantom the `generate` target seems to fail consistently.

**Comment by s-urbaniak** [comment]
/hold
just glanced over https://issues.redhat.com/browse/MON-1291?focusedCommentId=15678691&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15678691 and saw that we concluded that this shall wait until 4.8

**Comment by paulfantom** [comment]
Possibly will be superseded by #1044

**Comment by paulfantom** [comment]
Superseded by #1044 

/close

**Pull request closed without merging**
