### PR TITLE
MON-3380: replace OAuth proxy for prometheus-k8s

### PR DESCRIPTION
**Pull request by simonpasquier**
This commit replaces the oauth-proxy sidecar container by a kube-rbac-proxy container for the prometheus-k8s statefulset.

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by jan--f** [comment]
This
/lgtm
Thanks!

**Comment by simonpasquier** [comment]
/hold
I've got minor improvements in the way :)

**Comment by jan--f** [comment]
Nice!
/lgtm

**Comment by jan--f** [comment]
/retest
Seems like tests are taking too long right now?

**Comment by simonpasquier** [comment]
/hold
I've seen it already on this PR hence https://github.com/openshift/cluster-monitoring-operator/pull/2246/commits/4e93b165b47b7f65aabc2e97800ca46b1db7333e but it might not be an accident. I'll investigate further.

**Comment by simonpasquier** [comment]
I can see the timeout on other runs unrelated to this PR:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-monitoring-operator/2243/pull-ci-openshift-cluster-monitoring-operator-master-e2e-agnostic-operator/1755031388320436224

Let's see if we can decrease the test duration with a simple change: https://github.com/openshift/cluster-monitoring-operator/pull/2258

**Pull request merged**
