### PR TITLE
Bug 1907830: Backporting #965

### PR DESCRIPTION
**Pull request by paulfantom**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

Backporting https://github.com/openshift/cluster-monitoring-operator/pull/965

### CODE REVIEW

**Comment by paulfantom** [comment]
Backporting due to high number of customer cases.

**Review by lilic — COMMENTED** [review]
/lgtm

**Comment by juzhao** [comment]
tested with
`launch openshift/cluster-monitoring-operator#1022 aws`, no warin info in prometheus for "record: cluster:kube_persistentvolumeclaim_resource_requests_storage_bytes:provisioner:sum" and "record: cluster:kubelet_volume_stats_used_bytes:provisioner:sum" rules

/lgtm
/lgtm

**Comment by paulfantom** [comment]
Rebased. @openshift/openshift-team-monitoring PTAL

**Comment by paulfantom** [comment]
flakes
/retest

**Pull request merged**
