### PR TITLE
Bug 1868304: remove ValidatingWebhookConfiguration for downgrades

### PR DESCRIPTION
**Pull request by simonpasquier**
When downgrading from 4.6 to 4.5, the operator needs to remove the
ValidatingWebhookConfiguration resource used to validate rules in 4.6.

Signed-off-by: Simon Pasquier <spasquie@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
ping @bparees as discussed OOB to override the BZ rules here :-)

**Comment by bparees** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1868304 really should target 4.5.z since the change is to 4.5.z.

i'm going to fix its target.

i will also set https://bugzilla.redhat.com/show_bug.cgi?id=1869301 as a 4.6.0 target (which you've already closed as fixed, which is fine since it's not actually relevant to 4.6.0).

**Comment by s-urbaniak** [comment]
@simonpasquier i believe we need to add the delete permission to CMO:

```
is forbidden: User \"system:serviceaccount:openshift-monitoring:cluster-monitoring-operator\" cannot delete resource \"validatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\" at the cluster scope"
```

**Pull request merged**
