### PR TITLE
Sync with kube-prometheus

### PR DESCRIPTION
**Pull request by PhilipGough**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by jan--f** [comment]
I guess the permission change to `hack/merge_cluster_roles.py` was intentional? I don't think we need to change this PR but generally future me is a fan of mentioning such a change in the commit message/add a dedicated commit :)

**Comment by PhilipGough** [comment]
> I guess the permission change to `hack/merge_cluster_roles.py` was intentional? I don't think we need to change this PR but generally future me is a fan of mentioning such a change in the commit message/add a dedicated commit :)

Ack, no it wasn't I was fighting `make generate` and a Python install on OSX, will amend

**Comment by paulfantom** [comment]
> I guess the permission change to hack/merge_cluster_roles.py was intentional? 

We are removing that script in https://github.com/openshift/cluster-monitoring-operator/pull/1230 either way :)

/lgtm

**Pull request merged**
