### PR TITLE
Bug 1750283: Fix label as backport needs beta but 4.2 does not

### PR DESCRIPTION
**Pull request by chambridge**
* 4.2 has label: label_kubernetes_io_arch
* 4.1 has label: label_beta_kubernetes_io_arch

### CODE REVIEW

**Comment by LiliC** [comment]
@chambridge are you not part of openshift org on github, I think this is why I have to do the ok-to-test every time.

**Comment by chambridge** [comment]
@LiliC You are correct. I'm not in the OpenShift GitHub organization. Would be simpler if I was added, but I'm apart of the management business unit assisting to get all the necessary subscription related pieces in place.

**Comment by LiliC** [comment]
@chambridge up to you, just easier for you as then the tests would start on your own, you would not be blocked on us having to start them. :) I am fine either way.

**Comment by chambridge** [comment]
@LiliC @brancz  Needs `/cherry-pick-approved`? Or does someone else do that step?

**Comment by brancz** [comment]
Just needs cherrypick approval now. Release manager is automatically notified to review.

**Pull request merged**
