### PR TITLE
Bug 1732945: jsonnet: update telemeter client deployment

### PR DESCRIPTION
**Pull request by crawford**
This adds several series that have been backported to 4.1.

### CODE REVIEW

**Comment by crawford** [comment]
/retitle Bug 1732945: jsonnet: update telemeter client deployment

**Comment by crawford** [comment]
image

Huh?!? No, I didn't remove that label, GitHub. Your caching just sucks.

**Comment by jwforres** [comment]
/lgtm cancel

I don't think some of these were whitelisted in telemeter in master

**Pull request merged**
