### PR TITLE
fix typo Wether-->Whether

### PR DESCRIPTION
**Pull request by eranra**

### CODE REVIEW

**Comment by slashpai** [comment]
@simonpasquier I think now we are good to merge this

**Review by slashpai — APPROVED** [review]

**Comment by PhilipGough** [comment]
/docs-approved

no docs required

**Comment by PhilipGough** [comment]
/label docs-approved

no docs required

**Comment by PhilipGough** [comment]
/label qe-approved

none required, simple typo fix

**Pull request merged**
