### PR TITLE
WIP - Attempt less strict deployment anti affinity

### PR DESCRIPTION
**Pull request by omertuc**
* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.
* [ ]
*
Context https://bugzilla.redhat.com/show_bug.cgi?id=1950761

### CODE REVIEW

**Comment by paulfantom** [comment]
This seems to be reverting https://github.com/openshift/cluster-monitoring-operator/pull/1119. May I ask why?

**Comment by omertuc** [comment]
> This seems to be reverting #1119. May I ask why?

Context https://bugzilla.redhat.com/show_bug.cgi?id=1950761

**Comment by simonpasquier** [comment]
/close 
replaced by #1122

**Pull request closed without merging**
