### PR TITLE
assets: bump kubernetes-mixins

### PR DESCRIPTION
**Pull request by s-urbaniak**
This bumps the kubernetes-mixin dependency to add
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/76.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
(testing manually)

**Comment by brancz** [comment]
Can you confirm once you finished testing? This lgtm but if I put the label on it, it will be auto-merged.

**Comment by s-urbaniak** [comment]
ack, still testing the deployment. once done, I'll remove the wip flag

**Comment by s-urbaniak** [comment]
ok looking good :+1: 

image

**Comment by s-urbaniak** [comment]
@brancz from my side this is :+1: to merge

**Pull request merged**
