### PR TITLE
OCPBUGS-1676: Dedicated kubelet ServiceMonitor for prometheus-adapter

### PR DESCRIPTION
**Pull request by jan--f**
Backport of #1774 

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by juzhao** [comment]
tested with the PR, the output becomes uniform and very close to 1, detailed steps see from OCPBUGS-1676
/label cherry-pick-approved

**Pull request merged**
