### PR TITLE
Bug 1804455: Better memory calculations

### PR DESCRIPTION
**Pull request by paulfantom**
Port memory calculations from the latest node-exporter mixins as those are more accurate.

note: this is targeting 3.11 so procedures from 4.x regarding backports shouldn't apply here (especially "bugzilla/invalid-bug" label is expected). In short - click "merge" when green :smile: 

/cc @s-urbaniak @brancz

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@paulfantom something something travis! :thinking:

**Comment by paulfantom** [comment]
/hold cancel

issues with travis are solved now. Turned out jsonnet-bundler was problematic as we didn't pin to correct version of that binary.

Please click merge button as `tide` cannot merge things into `3.11` branch.

**Pull request merged**
