### PR TITLE
Bug 1982778: jsonnet: thanosquery: Use HTTP probes as opposed to exec

### PR DESCRIPTION
**Pull request by PhilipGough**
This is cherry pick of #1277 which backports to 4.8.z

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by aravindhp** [comment]
/retitle Bug 1982778: jsonnet: thanosquery: Use HTTP probes as opposed to exec

Removed an extra space to work around a patchmanager validation that needs to be loosened

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.20*
* Reason: *missed cutoff today, may make it tomorrow*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Pull request merged**
