### PR TITLE
Bug 1929278: [4.7] Adjust priority class of core platform prometheus

### PR DESCRIPTION
**Pull request by lilic**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by paulfantom — APPROVED** [review]
/lgtm

**Comment by bparees** [comment]
overriding bz so we can land this in 4.7 while waiting for it to land in master.

**Comment by rphillips** [comment]
Off by one
https://github.com/openshift/cluster-monitoring-operator/pull/1056/files#diff-1c3a94cd505f229b516603c090b53dbd0a9fc334a436b9b0e1eff4f313ed6290R56

**Comment by rphillips** [comment]
/hold
I created another PR here https://github.com/openshift/cluster-monitoring-operator/pull/1059

**Comment by bparees** [comment]
@lilic your e2e was broken (used ORs instead of ANDs), i've fixed it here:
https://github.com/openshift/cluster-monitoring-operator/pull/1060

/close

**Pull request closed without merging**
