### PR TITLE
STOR-1277: Add SELinux metrics to telemetry

### PR DESCRIPTION
**Pull request by jsafrane**
Added metrics for upstream SELinuxReadWriteOncePod feature.
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling#proposal

Request for approval: https://issues.redhat.com/browse/MON-3484

* [x] No user facing changes, so no entry in CHANGELOG was needed.

/hold
for https://issues.redhat.com/browse/MON-3484 to get approved + https://github.com/openshift/cluster-storage-operator/pull/422 to get merged first.

### CODE REVIEW

**Comment by machine424** [comment]
If https://github.com/openshift/cluster-storage-operator/pull/422/commits/4b2068e49904ec9200715fb792963099751a8bab doesn't change, LGTM.

But let's wait on the approval in https://issues.redhat.com/browse/MON-3484

**Comment by jsafrane** [comment]
Updated to `cluster:volume_manager_selinux_*` that wee agreed in https://github.com/openshift/cluster-storage-operator/pull/422#pullrequestreview-1752561599

**Pull request merged**
