### PR TITLE
MON-2148: Replace oauth-proxy with kube-rbac-proxy in prometheus

### PR DESCRIPTION
**Pull request by arajkumar**
This one supersedes https://github.com/openshift/cluster-monitoring-operator/pull/1594

* [X] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by raptorsun — APPROVED** [review]
looks good, just wait for the e2e test :) 

/lgtm

**Comment by arajkumar** [comment]
/hold

"ci/prow/e2e-agnostic" is failing with this PR, needs investigation.

**Comment by jan--f** [comment]
The test failure might go away on retry. The test ends up using the token of the `prometheus-adapter` service account. From the failing test case: `"Forbidden (user=system:serviceaccount:openshift-monitoring:prometheus-adapter, verb=create, resource=namespaces, subresource=)\n",`. A similar issues was fixed recently in a test. I pushed a PR to add a helper function to retrieve the right token, so the code is in one place in the future. https://github.com/openshift/origin/pull/27107

I'll trigger a retest, maybe we get lucky and don't have to wait for the origin PR to merge.

**Comment by jan--f** [comment]
/label docs-approved
/label px-approved
Adding docs and px labels as there are no user-facing changes.
Ping @juzhao for qe.

**Pull request closed without merging**
