### PR TITLE
Bug 1829974: pkg/tasks: remove grafana secret from thanos ruler

### PR DESCRIPTION
**Pull request by pgier**
The Grafana secret is not needed by Thanos Ruler.
Also, make the variable names clearer and fix ordering of deleting
resources.

### CODE REVIEW

**Comment by paulfantom** [comment]
/hold
seems like test failures are not flakes

**Comment by lilic** [comment]
@pgier We seem to have e2e tests where we asserts assets are deleted, do you mind expanding on the expected cases there, not urgent, just would be good I think. Didn't catch it until now. Thanks! https://github.com/openshift/cluster-monitoring-operator/blob/master/test/e2e/user_workload_monitoring_test.go#L523

**Pull request merged**
