### PR TITLE
Switch dns resolver to miekgdns

### PR DESCRIPTION
**Pull request by lilic**
I tested this in my cluster and 

cc @openshift/openshift-team-monitoring PTAL, thanks!

* [] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by lilic** [comment]
Screenshot 2020-12-01 at 11 25 28


On my cluster running with these changes, the DNS failure rate went down.

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by simonpasquier** [comment]
> Screenshot 2020-12-01 at 11 25 28
> 
> On my cluster running with these changes, the DNS failure rate went down.

same here, I went from 100% of DNS failures to 0% with your patch.

**Comment by lilic** [comment]
> level=error msg=Error: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.

/retest

**Comment by s-urbaniak** [comment]
fantastic, very promising results, thank you! :tada: looking forward to find out what the root cause is with the native Go resolver. :crossed_fingers:

**Comment by lilic** [comment]
/retest

seems like resource quotas were hit again.

**Comment by lilic** [comment]
/retest

nothing monitoring related...

**Pull request merged**
