### PR TITLE
BUG 1949145: Delete 0000_50_cluster-monitoring-operator_00_0user-priority-class.yaml

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Moving this priority class to [CCO](https://github.com/openshift/cluster-config-operator/pull/191) - as it is beneficial enough to be used by multiple components.

* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/lgtm
/hold
it needs to wait for https://github.com/openshift/cluster-config-operator/pull/191 to be merged.

**Comment by ravisantoshgudimetla** [comment]
https://github.com/openshift/cluster-config-operator/pull/191  merged

/retest

**Comment by ravisantoshgudimetla** [comment]
/hold

We don't have a CI build for openshift/cluster-config-operator#191, will hold till then

**Comment by ravisantoshgudimetla** [comment]
/hold

@wking mentioned that cluster-profile annotations are mandatory for CVO to load manifests if we have opted into the cluster-profile we're currently running. So once https://github.com/openshift/cluster-config-operator/pull/193 merges, we should see the priority class getting created.

**Comment by lihongyan1** [comment]
test with payload 4.8.0-0.nightly-2021-04-15-152737, the PR can be merged now

```
#oc get PriorityClass openshift-user-critical -oyaml
apiVersion: scheduling.k8s.io/v1
description: This priority class should be used for user facing OpenShift workload pods only.
kind: PriorityClass
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2021-04-15T23:10:07Z"
  - apiVersion: scheduling.k8s.io/v1
  name: openshift-user-critical
  resourceVersion: "1589"
  uid: 9a0fe9cb-7e3b-42e9-a799-f073ec1a89ba
preemptionPolicy: PreemptLowerPriority
value: 1000000000
```

**Pull request merged**
