### PR TITLE
configure user workload monitoring cpu (and memory) requests

### PR DESCRIPTION
**Pull request by s-urbaniak**
This adds cpu and memory requests for the user workload monitoring stack. The numbers are based on the following queries executed against an idle cluster (4.6.0-0.ci-2020-06-26-063230):

cpu query:

```
sum by (pod, container) (rate(container_cpu_usage_seconds_total{container!="POD",container!="",pod!="",namespace="openshift-user-workload-monitoring"}[5m])*1024)
```

```
{container="kube-rbac-proxy",pod="prometheus-operator-847f4f6d8b-kfc7m"}	0.1322166535812183
{container="kube-rbac-proxy",pod="prometheus-user-workload-0"}	0.12982535610620552
{container="kube-rbac-proxy",pod="prometheus-user-workload-1"}	0.13318507958075665
{container="prometheus",pod="prometheus-user-workload-0"}	6.513315714586842
{container="prometheus",pod="prometheus-user-workload-1"}	6.593808195632568
{container="prometheus-config-reloader",pod="prometheus-user-workload-0"}	0.016717700815347354
{container="prometheus-config-reloader",pod="prometheus-user-workload-1"}	0.015974725142363085
{container="prometheus-operator",pod="prometheus-operator-847f4f6d8b-kfc7m"}	0.9542130191800298
{container="rules-configmap-reloader",pod="prometheus-user-workload-0"}	0.0035767219270141006
{container="rules-configmap-reloader",pod="prometheus-user-workload-1"}	0.007119571725065891
{container="rules-configmap-reloader",pod="thanos-ruler-user-workload-0"}	0.009739780254686747
{container="rules-configmap-reloader",pod="thanos-ruler-user-workload-1"}	0.007235233584499463
{container="thanos-ruler",pod="thanos-ruler-user-workload-0"}	0.734103271282617
{container="thanos-ruler",pod="thanos-ruler-user-workload-1"}	0.6905953581450671
{container="thanos-ruler-proxy",pod="thanos-ruler-user-workload-0"}	0.6540643085929762
{container="thanos-ruler-proxy",pod="thanos-ruler-user-workload-1"}	0.6864613823800506
{container="thanos-sidecar",pod="prometheus-user-workload-0"}	0.37999520796438196
{container="thanos-sidecar",pod="prometheus-user-workload-1"}	0.4202756964031533
```

memory query:

```
sum by (pod,container) (container_memory_working_set_bytes{container!="POD",container!="",pod!="",namespace="openshift-user-workload-monitoring"})/1024/1024
```

```
{container="kube-rbac-proxy",pod="prometheus-operator-847f4f6d8b-kfc7m"}	9.25390625
{container="kube-rbac-proxy",pod="prometheus-user-workload-0"}	8.66015625
{container="kube-rbac-proxy",pod="prometheus-user-workload-1"}	9.87890625
{container="prometheus",pod="prometheus-user-workload-0"}	31.140625
{container="prometheus",pod="prometheus-user-workload-1"}	32.046875
{container="prometheus-config-reloader",pod="prometheus-user-workload-0"}	7.73828125
{container="prometheus-config-reloader",pod="prometheus-user-workload-1"}	7.55859375
{container="prometheus-operator",pod="prometheus-operator-847f4f6d8b-kfc7m"}	16.26171875
{container="rules-configmap-reloader",pod="prometheus-user-workload-0"}	4.5625
{container="rules-configmap-reloader",pod="prometheus-user-workload-1"}	4.4140625
{container="rules-configmap-reloader",pod="thanos-ruler-user-workload-0"}	4.56640625
{container="rules-configmap-reloader",pod="thanos-ruler-user-workload-1"}	4.53125
{container="thanos-ruler",pod="thanos-ruler-user-workload-0"}	20.5625
{container="thanos-ruler",pod="thanos-ruler-user-workload-1"}	21.9375
{container="thanos-ruler-proxy",pod="thanos-ruler-user-workload-0"}	12.57421875
{container="thanos-ruler-proxy",pod="thanos-ruler-user-workload-1"}	10.6328125
{container="thanos-sidecar",pod="prometheus-user-workload-0"}	15.828125
{container="thanos-sidecar",pod="prometheus-user-workload-1"}	16.36328125
```

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by s-urbaniak** [comment]
starting a cluster in parallel to verify the numbers.

**Comment by s-urbaniak** [comment]
Verified on a local cluster

```
$ kubectl -n openshift-user-workload-monitoring get pod -o yaml | gojsontoyaml -yamltojson | jq '.items[] | .spec.containers[] | .name, .resources.requests'

"prometheus-operator"
{
  "cpu": "1m",
  "memory": "17Mi"
}
"kube-rbac-proxy"
{
  "cpu": "1m",
  "memory": "10Mi"
}
"prometheus"
{
  "cpu": "6m",
  "memory": "30Mi"
}
"prometheus-config-reloader"
{
  "cpu": "1m",
  "memory": "8Mi"
}
"rules-configmap-reloader"
{
  "cpu": "1m",
  "memory": "5Mi"
}
"thanos-sidecar"
{
  "cpu": "1m",
  "memory": "17Mi"
}
"kube-rbac-proxy"
{
  "cpu": "1m",
  "memory": "10Mi"
}
"prometheus"
{
  "cpu": "6m",
  "memory": "30Mi"
}
"prometheus-config-reloader"
{
  "cpu": "1m",
  "memory": "8Mi"
}
"rules-configmap-reloader"
{
  "cpu": "1m",
  "memory": "5Mi"
}
"thanos-sidecar"
{
  "cpu": "1m",
  "memory": "17Mi"
}
"kube-rbac-proxy"
{
  "cpu": "1m",
  "memory": "10Mi"
}
"thanos-ruler"
{
  "cpu": "1m",
  "memory": "21Mi"
}
"rules-configmap-reloader"
{
  "cpu": "1m",
  "memory": "5Mi"
}
"thanos-ruler-proxy"
{
  "cpu": "1m",
  "memory": "12Mi"
}
"thanos-ruler"
{
  "cpu": "1m",
  "memory": "21Mi"
}
"rules-configmap-reloader"
{
  "cpu": "1m",
  "memory": "5Mi"
}
"thanos-ruler-proxy"
{
  "cpu": "1m",
  "memory": "12Mi"
}
```

**Comment by s-urbaniak** [comment]
it looks like the failures here are the same as in #831 hence i believe it is not related to the changes here, but let's observe :thinking:

**Comment by lilic** [comment]
I think it has to do with CI, as other jobs were failing as well, but yes lets see.

**Comment by paulfantom** [comment]
Test failure was possibly related to github problems
/retest
/lgtm

**Pull request merged**
