### PR TITLE
Bug 1939412: remove managed-by label as it is conflicting with prometheus-operator

### PR DESCRIPTION
**Pull request by paulfantom**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by simonpasquier** [comment]
/retitle Bug 1939412: remove managed-by label as it is conflicting with prometheus-operator

**Comment by simonpasquier** [comment]
/retitle Bug 1954421: remove managed-by label as it is conflicting with prometheus-operator

**Comment by juzhao** [comment]
checked in a normal cluster, alertmanager-main pod has managed-by label
```
# oc -n openshift-monitoring get pod alertmanager-main-0 --show-labels
NAME                  READY   STATUS    RESTARTS   AGE     LABELS
alertmanager-main-0   5/5     Running   0          3h41m   alertmanager=main,app.kubernetes.io/component=alert-router,app.kubernetes.io/managed-by=cluster-monitoring-operator,app.kubernetes.io/name=alertmanager,app.kubernetes.io/part-of=openshift-monitoring,app.kubernetes.io/version=0.21.0,app=alertmanager,controller-revision-hash=alertmanager-main-8f7577d96,statefulset.kubernetes.io/pod-name=alertmanager-main-0
```

**Comment by dgrisonnet** [comment]
I am still seeing the prometheus pods being down even after this changes. From the last CI runs, we have the following logs in CMO: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/1138/pull-ci-openshift-cluster-monitoring-operator-master-e2e-agnostic-operator/1387341674325217280/artifacts/e2e-agnostic-operator/gather-extra/artifacts/pods/openshift-monitoring_cluster-monitoring-operator-796696cb7c-9kxs6_cluster-monitoring-operator.log
```
I0428 11:05:31.707372       1 operator.go:474] Updating ClusterOperator status to failed. Err: running task Updating Prometheus-k8s failed: waiting for Prometheus object changes failed: waiting for Prometheus openshift-monitoring/k8s: expected 2 replicas, got 0 updated replicas
E0428 11:05:31.722193       1 operator.go:399] Syncing "openshift-monitoring/cluster-monitoring-config" failed
E0428 11:05:31.722265       1 operator.go:400] sync "openshift-monitoring/cluster-monitoring-config" failed: running task Updating Prometheus-k8s failed: waiting for Prometheus object changes failed: waiting for Prometheus openshift-monitoring/k8s: expected 2 replicas, got 0 updated replicas
I0428 11:05:31.750540       1 operator.go:466] Updating ClusterOperator status to in progress.
```

**Comment by dgrisonnet** [comment]
Hum also in prometheus-operator: 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/1138/pull-ci-openshift-cluster-monitoring-operator-master-e2e-agnostic-operator/1387341674325217280/artifacts/e2e-agnostic-operator/gather-extra/artifacts/pods/openshift-monitoring_prometheus-operator-576667c9d8-6vv9j_prometheus-operator.log
```
level=info ts=2021-04-28T10:45:20.489074566Z caller=operator.go:1236 component=prometheusoperator msg="resolving illegal update of Prometheus StatefulSet" details="&StatusDetails{Name:prometheus-k8s,Group:apps,Kind:StatefulSet,Causes:[]StatusCause{StatusCause{Type:FieldValueForbidden,Message:Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden,Field:spec,},},RetryAfterSeconds:0,UID:,}"
```

**Comment by paulfantom** [comment]
I think we need to solve this in prometheus-operator. For now, I think it would be best to revert prometheus-operator update and unlock CI.

@simonpasquier WDYT?

**Comment by simonpasquier** [comment]
@paulfantom sure lets revert.

**Comment by paulfantom** [comment]
Revert PR: https://github.com/openshift/prometheus-operator/pull/116

**Comment by simonpasquier** [comment]
@paulfantom can you rebase?

**Comment by simonpasquier** [comment]
/retitle Bug 1939412: remove managed-by label as it is conflicting with prometheus-operator

since we need this PR to be merged before bumping (again) prometheus operator to v0.47.0

**Comment by simonpasquier** [comment]
/close 

Bug 1939412 has been fixed by reverting the bump of prometheus operator in https://github.com/openshift/prometheus-operator/pull/116. This change will be included as part of #1127: once it is merged, we can try again to bump prometheus operator to v0.47.0.

**Comment by paulfantom** [comment]
/reopen

This is still needed for potential prometheus-operator 0.47 bump. Without it ServiceMonitors for prometheus and alertmanager won't match respective Services.

**Comment by paulfantom** [comment]
Ah, it is included in #1127. Nothing to see here :)

/close

**Pull request closed without merging**
