### PR TITLE
Bug 1799057: Send apiserver_current_inflight_requests in telemeter.

### PR DESCRIPTION
**Pull request by tkashem**
cluster:apiserver_current_inflight_requests:sum:max_over_time:2m gives
maximum number of requests in flight over a 2-minute window. This
metric is a constant 4 time series that monitors concurrency of
kube-apiserver and openshift-apiserver with request type which can be
either 'mutating' or 'readonly'. We want to have an idea of how loaded
our api server(s) are globally.

### CODE REVIEW

**Comment by tkashem** [comment]
New process, carrying it from https://github.com/openshift/telemeter/pull/304.

Also, related PRs that should merge first:
- https://github.com/openshift/cluster-openshift-apiserver-operator/pull/307
- https://github.com/openshift/cluster-kube-apiserver-operator/pull/737

**Comment by LiliC** [comment]
@tkashem just ping us again when the PRs are merged.

/hold

until the PRs are merged.

**Comment by sttts** [comment]
Sgtm.

**Comment by tkashem** [comment]
> @tkashem just ping us again when the PRs are merged.
> 
> /hold
> 
> until the PRs are merged.

@LiliC I addressed the feedback @brancz posted, so these just need `lgtm` from someone from your team.
https://github.com/openshift/cluster-openshift-apiserver-operator/pull/307
https://github.com/openshift/cluster-kube-apiserver-operator/pull/737

**Comment by tkashem** [comment]
@LiliC, the dependent PRs have merged:
https://github.com/openshift/cluster-openshift-apiserver-operator/pull/307
https://github.com/openshift/cluster-kube-apiserver-operator/pull/737

**Pull request merged**
