### PR TITLE
clusteroperator: Report the appropriate injected status version

### PR DESCRIPTION
**Pull request by smarterclayton**
In order to indicate we have reached our desired level, we accept an opaque
token from the payload and pass it through to status only after we have
fully rolled out our new components. This allows the CVO to know that we
have hit the desired state.

See https://github.com/openshift/cluster-image-registry-operator/pull/219 for more context and discussion

### CODE REVIEW

**Comment by smarterclayton** [comment]
Correctly set into 
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/278/pull-ci-openshift-cluster-monitoring-operator-master-e2e-aws/580/artifacts/e2e-aws/clusteroperators.json

**Comment by smarterclayton** [comment]
@brancz if you can assign a reviewer

**Comment by brancz** [comment]
Sorry actually had an open tab to review myself. The comment you added reflects exactly the way the done is set in the cluster-monitoring-operator. So lgtm.

/lgtm

**Pull request merged**
