### PR TITLE
Add runbook for kube persistent volume inodes filling up

### PR DESCRIPTION
**Pull request by simonpasquier**
* [ ] I added CHANGELOG entry for this change.
* [X] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by PhilipGough — APPROVED** [review]
/lgtm

**Review by simonpasquier — COMMENTED** [review]
/label px-approved
/label docs-approved

No need to PX or docs approval.

**Comment by simonpasquier** [comment]
ping @openshift/team-monitoring-qe-approvers for approval :)

**Pull request merged**
