### PR TITLE
Bug 1957704: [4.6]: Add hard anti-affinity constraints to Prometheuses

### PR DESCRIPTION
**Pull request by dgrisonnet**
Backport of #1150 to release-4.6.

* [ ] I added CHANGELOG entry for this change.
* [x] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by juzhao** [comment]
tested with the not merged PR, hard anti-affinity to Prometheuses is added, prometheus-k8s and prometheus-user-workload pods are scheduled to different nodes
/label qe-approved

**Comment by dgrisonnet** [comment]
Holding as the backport to `release-4.7` introduced a regression: https://bugzilla.redhat.com/show_bug.cgi?id=1967614

/hold

**Comment by dgrisonnet** [comment]
Closing for now because of the regression.

**Pull request closed without merging**
