### PR TITLE
Add crio metrics as an endpoint of nodes

### PR DESCRIPTION
**Pull request by brancz**
As this needs a bit of a hack, I went ahead and did the relabelling rules to make this work.

@squat @s-urbaniak @mxinden @metalmatze 

cc @runcom

### CODE REVIEW

**Comment by brancz** [comment]
Still testing this so putting a hold on this for now.

/hold

**Comment by brancz** [comment]
I am currently seeing a problem where consistently there are nodes that cannot be scraped. @runcom is investigating.

screenshot from 2019-01-31 17-00-28

**Comment by runcom** [comment]
so, I've been testing this on a brand new cluster from today and I'm perfectly able to grab metrics from each node

**Comment by brancz** [comment]
Got it, in that case I will give it another try.

**Comment by brancz** [comment]
I think I have an idea what's happening. This seems to only happen to workers, I think the security group rules are probably off.

**Comment by runcom** [comment]
latest installer now has https://github.com/openshift/installer/pull/1201 which should open ports for worker<->worker communication for metrics

**Comment by brancz** [comment]
Awesome. I'm going to give this a try soon.

**Comment by s-urbaniak** [comment]
@brancz can we add the `up` query to the existing e2e tests too?

https://github.com/openshift/cluster-monitoring-operator/blob/e536f4fea32bf02944f583d57eb29951e8c70481/test/e2e/main_test.go#L93-L128

**Pull request merged**
