### PR TITLE
serviceMonitorKubeControllerManager: enable TLS

### PR DESCRIPTION
**Pull request by s-urbaniak**
In accordance to 
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/207 
we can now enable TLS for the controller manager.

### CODE REVIEW

**Comment by paulfantom** [comment]
I think this won't pass `ci/prow/e2e-aws` due to this line: https://github.com/openshift/origin/blob/ef64f91ed01979e4ee327f5af5fd1fe11ba2428b/test/extended/prometheus/prometheus.go#L131

**Comment by brancz** [comment]
That failed so much I think there’s actually a failure.

**Comment by s-urbaniak** [comment]
agreed, also I just recognized https://github.com/openshift/cluster-kube-scheduler-operator/pull/88 is not merged yet, I'll split this into two PRs.

**Comment by s-urbaniak** [comment]
The logs were a bit hidden, but indeed it's the scheduler that didn't bubble up in the image builds yet.

**Comment by s-urbaniak** [comment]
changes in controller manager operator merged, retesting

**Comment by s-urbaniak** [comment]
missing permissions in controller manager tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1697875

**Comment by s-urbaniak** [comment]
closing in favor of #316

**Pull request closed without merging**
