### PR TITLE
Revert 586 revertremotewrite

### PR DESCRIPTION
**Pull request by brancz**
This is a second attempt at using remote write for OpenShift telemetry, now that the backend has authz caching and this PR additionally reduces concurrency by 50x while increasing batch size.

cc @squat @metalmatze @s-urbaniak @LiliC @simonpasquier @pgier @paulfantom @kakkoyun

### CODE REVIEW

**Comment by s-urbaniak** [comment]
unhold at will once ready :+1:

**Comment by LiliC** [comment]
/lgtm

/hold

free feel to cancel the hold when ready to be merged

**Comment by LiliC** [comment]
:shipit:

**Pull request merged**
