### PR TITLE
Bug 1955454: [release-4.6] removing crio metric

### PR DESCRIPTION
**Pull request by prashbnair**
* [ ] I added CHANGELOG entry for this change.
* [ ] No user facing changes, so no entry in CHANGELOG was needed.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
@prashbnair you need to push the `pkg/manifests/bindata.go` file that should have been updated by running `make generate`.

**Comment by simonpasquier** [comment]
`e2e-aws-operator` also fails because of DNS unmarshal errors in Thanos Ruler. We need https://github.com/openshift/thanos/pull/57 before it can pass again.

**Comment by juzhao** [comment]
tested with the PR not merged, no container_runtime_crio_image_* metrics now
/label qe-approved

**Pull request merged**
