### PR TITLE
jsonnet/main.jsonnet: Bump Prometheus to v2.7.1

### PR DESCRIPTION
**Pull request by mxinden**
This version should only give the Prometheus Operator the hint, to configure the given Prometheus instance with command line flags compatible with Prometheus v2.7.1.

### CODE REVIEW

**Comment by simonpasquier** [comment]
LGTM but I'm not sure what the [version](https://github.com/openshift/cluster-monitoring-operator/pull/246/files#diff-0e89493bf083b0ef3344b10269a96578R31) in `jsonnet/main.jsonnet` is for.

**Comment by mxinden** [comment]
> I'm not sure what the [version](https://github.com/openshift/cluster-monitoring-operator/pull/246/files#diff-0e89493bf083b0ef3344b10269a96578R31) in `jsonnet/main.jsonnet` is for.

Hope I understand your question correctly: `main.jsonnet` holds the values that are going to be templated, resulting in the manifests in `assets`. The change in `promtheus.yaml` results directly from the change in `main.jsonnet`.

As this is not super urgent, I would wait for @brancz to give this a review as well.

**Comment by simonpasquier** [comment]
@mxinden thanks for the explanation, I missed that `assets/prometheus-k8s/prometheus.yaml` was generated which sounds obvious now that you said it.

**Comment by brancz** [comment]
fwiw this version here is only the version specified in origin, OCP overrides the version through the payload. Even for origin I'm not entirely sure starting with 4.0. Either way it doesn't hurt to update this as it's what we're already using in OCP.

**Comment by brancz** [comment]
looks like this needs a rebase

**Pull request merged**
